### ISSUE TITLE
Kitchen converge fails for vagrant kensykora-windows-2012-r2-standard

### ISSUE THREAD

**Issue by mister-lister** [test-kitchen/test-kitchen#1010]
## Description

When running `kitchen converge` in my win2k12 repo it fails to converge and outputs an error log. 

## Kitchen Version

```ruby
Test Kitchen version 1.7.3
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 0.12.0
chef-client version: 12.10.3
berks version: 4.3.0
kitchen version: 1.7.3
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin13.0]
```

## Platform Version

```
Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

* run `kitchen init`
* edit kitchen.yml like so:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[ad-join::default]
    attributes:
```
* `kitchen create`
* run `kitchen converge` and that's when I see the error

## Kitchen Output

[Pastebin Link](http://pastebin.com/SXRAjZF6)

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

[Pastebin Link for Diagnose](http://pastebin.com/G9NAxNF3)

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by mwrock** [comment]
It looks like kitchen does not know you are windows and is trying to talk SSH and send bash commands. Test-Kitchen detects you are windows if your platform name starts with "win". You can change your platform yaml to:
```
platforms:
  - name: windows_2012_r2_standard
    driver_config:
      box: kensykora/windows_2012_r2_standard
```
This should allow Test-Kitchen to identify that you are windows and talk the correct dialect.
