### ISSUE TITLE
`chef-long_script.ps1` giving error when trying to spin up windows box

### ISSUE THREAD

**Issue by joshoohaah** [test-kitchen/test-kitchen#1013]
## Description

I was having issues of my windows box trying to spin up chef-client in the linux location (same as issue  #565 ).  Was getting this error.

```
       Transferring files to <default-win2012r2-chef>
$$$$$$ &amp; : The term '\bin\chef-client.bat' is not recognized as the name of a cmdlet,
$$$$$$ function, script file, or operable program. Check the spelling of the name, or
$$$$$$ if a path was included, verify that the path is correct and try again.
$$$$$$ At line:9 char:3
$$$$$$ + &amp; \bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb
$$$$$$ --log_l ...
$$$$$$ +   ~~~~~~~~~~~~~~~~~~~~
$$$$$$     + CategoryInfo          : ObjectNotFound: (\bin\chef-client.bat:String) []
$$$$$$    , CommandNotFoundException
$$$$$$     + FullyQualifiedErrorId : CommandNotFoundException
>>>>>> Converge failed on instance <default-win2012r2-chef>.
>>>>>> Please see .kitchen/logs/default-win2012r2-chef.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [$env:http_proxy = "http://3.20.109.241:88/"
```

Changed kitchen.yml as follows:

```

---
driver:
  name: vagrant
  driver_config:
    customize:
      natdnshostresolver1: "on"

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2_chef
    require_chef_omnibus: false
    # os_type: windows
    # shell_type: powershell
    driver_config:
       box: win2012r2_chef
       gui: true
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    run_list:
      - recipe[hc_ad_config::default]
    attributes:
```

New Error:

```
       Preparing validation.pem
       Preparing client.rb
$$$$$$ The argument 'C:\Users\vagrant\AppData\Local\Temp/kitchen/default-win2012r2-chef-long_script.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
>>>>>> Converge failed on instance <default-win2012r2-chef>.
>>>>>> Please see .kitchen/logs/default-win2012r2-chef.log for more details
```
## Kitchen Version

```
kitchen version: 1.6.0
```
## ChefDK Version

``` ruby
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```
## Platform Version

Mac OS X 10.9.  Running virtualbox VM Windows 2012 R2

``` ruby
# Copy-paste your results here
```
## Kitchen Diagnose

```
$ kitchen diagnose --all

---
timestamp: 2016-04-20 14:00:57 UTC
kitchen_version: 1.6.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 0.20.0
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.6.0
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.6.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.6.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
    filename: "/Users/joshuaschneider/.kitchen/config.yml"
    raw_data: {}
  project_config:
    filename: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
        driver_config:
          customize:
            natdnshostresolver1: 'on'
      provisioner:
        name: chef_zero
      platforms:
      - name: win2012r2_chef
        require_chef_omnibus: false
        driver_config:
          box: win2012r2_chef
          gui: true
        transport:
          name: winrm
          winrm_transport: negotiate
      suites:
      - name: default
        run_list:
        - recipe[hc_ad_config::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        driver_config:
          customize:
            natdnshostresolver1: 'on'
      provisioner:
        name: chef_zero
      platforms:
      - name: win2012r2_chef
        require_chef_omnibus: false
        driver_config:
          box: win2012r2_chef
          gui: true
        transport:
          name: winrm
          winrm_transport: negotiate
      suites:
      - name: default
        run_list:
        - recipe[hc_ad_config::default]
        attributes:
instances:
  default-win2012r2-chef:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 127.0.0.1
      last_action: create
      password: vagrant
      port: '5985'
      rdp_port: '3389'
      username: vagrant
    driver:
      boot_timeout:
      box: win2012r2_chef
      box_check_update:
      box_download_insecure:
      box_url:
      box_version:
      customize: {}
      driver_config:
        customize:
          natdnshostresolver1: 'on'
      gui: true
      kitchen_root: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/Users/joshuaschneider/.chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-0.20.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname:
    provisioner:
      attributes: {}
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options:
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config"
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      profile_ruby: false
      require_chef_omnibus: true
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[hc_ad_config::default]
      sudo:
      sudo_command:
      test_base_path: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config/test/integration"
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config/test/integration"
      username: administrator
      winrm_transport: :negotiate
    verifier:
      busser_bin: "$env:TEMP\\verifier\\bin\\busser.bat"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config"
      log_level: :info
      name: busser
      root_path: "$env:TEMP\\verifier"
      ruby_bindir: "$env:systemdrive\\opscode\\chef\\embedded\\bin"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: "/Users/joshuaschneider/healthcare-dev/cookbooks/hc_ad_config/test/integration"
      version: busser
```

**Comment by mwrock** [comment]
Can you run with `-l debug` and see if there are powershell errors above from the MSI install? (currently those only show up in debug output). Also try 1.7.3. A new chef-dk is imminent that will have 1.7.3.

**Comment by smurawski** [comment]
I hit that with 1.6.0 as well, I think it is mixlib-install related.  1.7.3 fixed it.

**Comment by joshoohaah** [comment]
Updated to test-kitchen 1.7.3.
New/different error on now it can't handshake with win-rm.

```
           default: WinRM execution_time_limit: PT2H
           default: WinRM transport: plaintext
       An error occurred executing a remote WinRM command.

       Shell: powershell
       Command: $ProgressPreference='SilentlyContinue';
       hostname
       if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
       Message: Unable to parse WinRM response: Missing end tag for 'br' (got "p")
       Line: 3
       Position: 225
       Last 80 unconsumed characters:
        (504).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
```
debug output of the different error now. 
## Kitchen output -debug
https://gist.github.com/joshoohaah/3ad88750b7fa43bfe8828ba54f0232ff

**Comment by joshoohaah** [comment]
it's worth noting that i am running on a proxied environment. I have the proxy declared globally though and winrm was working on test-kitchen gem 1.6.0.   just updated my `.kitchen.yml` to have my proxies declared explicitly in the yml with the same result as above.
```
---
driver:
  forward_agent: yes
  name: vagrant
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>
  driver_config:
    customize:
      natdnshostresolver1: "on"
      natdnsproxy1: "on"


provisioner:
  name: chef_zero
  client_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
  solo_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>

platforms:
  - name: win2012r2_chef
    require_chef_omnibus: false
    # os_type: windows
    # shell_type: powershell
    driver_config:
       box: win2012r2_chef
       gui: true
       vm_hostname: false
    transport:
      name: winrm
      winrm_transport: negotiate

suites:
  - name: default
    ```

**Comment by mwrock** [comment]
I keep meaning to look into the proxy settings there. I've heard others complain that it doesn't work but I have never tried it or intentionally reviewed the code. However, there is a way to work around that by setting the `HTTP_PROXY`/`HTTPS_PROXY` environment variables.

**Comment by joshoohaah** [comment]
yes. that was how it 'used' to work with test-kitchen gem 1.6.0.  I was able to get winrm to connect by setting those. now updating to 1.7.3 the same method does not work.  I've blurred out my proxies, but here is a pic that I do have the HTTP_PROXY/HTTPS_PROXY env vars set on my shell
![screen shot 2016-04-20 at 1 48 14 pm](https://cloud.githubusercontent.com/assets/8366405/14686604/18d9fa20-06ff-11e6-82a5-c85b65d150f0.png)

**Comment by glennmate** [comment]
Seeing the exact same root issue as well on Kitchen 1.6.0 with ChefDK 0.12.0. Pushing an update to 1.7.3 for Kitchen to see if issue resolves.

**Comment by glennmate** [comment]
Confirmed that updating test-kitchen resolved the issue. Also the new chef-dk is out, 0.13.21, which includes the newer test-kitchen.

**Comment by joshoohaah** [comment]
@glennmate I updated to the new chefdk and still get this error in a proxied environment
```
       Transferring files to <default-win2012r2-chef>
$$$$$$ &amp; : The term 'C:\opscode\chef\bin\chef-client.bat' is not recognized as the
$$$$$$ name of a cmdlet, function, script file, or operable program. Check the
$$$$$$ spelling of the name, or if a path was included, verify that the path is
$$$$$$ correct and try again.
```

**Comment by mwrock** [comment]
Proxys are tricky here because there are multiple boundaries where proxies may exist.

First there is between the Test-Kitchen workstation/host and the test instance. This is where you need to set your local HTTP_PROXY and HTTPS_PROXY environment variables which winrm will honor to go through a proxy between where test-kitchen is running from and the test instance. If, for instance this is a localhost virtualbox VM, this is probably not an issue.

Second is between the test instance and the internet. Unless you have configured the provisioner otherwise, it will go to bin tray to get a chef client to download and depending on the recipes you are running, there may be other things grabbing bits off the internet. This is where you need to set the `http_proxy` and `https_proxy` provisioner settings. Here is an example:
```
provisioner:
  name: chef_zero
  http_proxy: http://192.168.137.126:808
  https_proxy: http://192.168.137.126:808
```
This will set the HTTP_PROXY and HTTPS_PROXY environment variables on the instance and also set the `System.Net.WebProxy` address to the `http_proxy` value when going to grab the chef client MSI. If these provisioner settings are not set, the chef-client download will fail and that results in the exact error @joshoohaah is seeing.

**Comment by joshoohaah** [comment]
ok. interestingly enough now I get past winrm authentication issues now.  but in the convergence phase (in this example I'm using the chocolatey cookbook to install chocolatey and then some apps), its now giving these types of errors
```
       STDERR: C:\Users\vagrant\AppData\Local\Temp\chef-script20160503-3376-kv58vp.ps1 : The
       underlying connection was closed: Could not establish trust relationship for
       the SSL/TLS secure channel.
```

I have the chocolatey cookbook setup for proxy use as well in my kitchen.yml file
```
    attributes:
      chocolatey:
        install_vars:
          chocolateyProxyLocation: <%= ENV['http_proxy'] %>
```
