### ISSUE TITLE
Windows RDP Port Forward Issue

### ISSUE THREAD

**Issue by wstaples** [test-kitchen/test-kitchen#1017]
## Description
When the default RDP port of 3306 is in use and vagrant automatically forwards to a different port the `kitchen login` command stops working.

I opened this ticket with vagrant but I'm lead to believe this might be a test-kitchen issue:
https://github.com/mitchellh/vagrant/issues/7174

## Kitchen Version
I started in the 1.4.x
I then upgraded to 1.5.x and 1.6.0 in an attempt to fix the issue.

## ChefDK Version
Chef Development Kit Version: 0.11.2
chef-client version: 12.8.1
berks version: 4.3.2
kitchen version: 1.6.0

## Platform Version
Windows 7 64-bit

## Replication Case
Run:
`berks cookbook bugtest`

Then update kitchen.yml file to look like:
```yaml
---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.225.217"}]
    - - forwarded_port
      - guest: 3389
        host: 33389
        auto_correct: true
  synced_folders:
    - [".", "/vagrant"]

provisioner:
  name: chef_solo

platforms:
  - name: win2012
    driver_config:
      box: maddhatter/windows-2012r2
      box_url: maddhatter/windows-2012r2
      communicator: winrm
    transport:
      name: winrm
      winrm_transport: plaintext
    os_type: windows
    shell_type: powershell

suites:
  - name: default
    run_list:
    attributes:
```
Run:
`kitchen create`

You will then see this in the output:
`==> default: Fixed port collision for 3389 => 33389. Now on port 2220.`

Then try:
`kitchen login`

You will see that it always attempts to connect to port 3389.

## Kitchen Output
if you look at the file .kitchen/default-win2012.yml that is created you will see it lists rdp_port as 3389.

```yml
---
hostname: 127.0.0.1
port: '2221'
username: vagrant
password: vagrant
rdp_port: '3389'
last_action: create
```

## Kitchen Diagnose
https://gist.github.com/wstaples/7cb31cbf2b7d79ac436b52e6f1ea36c8
