### ISSUE TITLE
Docker provisioner converge fails: [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by humboldtux** [test-kitchen/test-kitchen#1018]
## Description

I can't converge a docker kitchen conf. There is a (curl?) *converge fails: [SSL: CERTIFICATE_VERIFY_FAILED]*  error.

## Kitchen Version / ChefDK Version / Platform Version

```
$ uname -a
Linux S760P02 4.4.0-0.bpo.1-amd64 #1 SMP Debian 4.4.6-1~bpo8+1 (2016-03-20) x86_64 GNU/Linux
$ chef --version
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```
## Replication Case

My .kitchen.yml:

```
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  environments_path: ../../environments
  roles_path: ../../roles

platforms:
  - name: debian-8.4

suites:
  - name: default
    run_list:
      - recipe[myrecipe]
    attributes:
```

## Kitchen Output

```
$ kitchen converge
...
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying curl...
       Download complete.
       debian 8 x86_64
       Getting information for chef stable  for debian...
       downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=debian&pv=8&m=x86_64
         to file /tmp/install.sh.167/metadata.txt
       trying curl...
       sha1     ee9f52e9fabec20979c1b79e91d57d055a87896f
       sha256   6ee8e2f463593f5a78aa3c085348803933e9424c637da37e92dce2db792beaf9
       url      https://packages.chef.io/stable/debian/8/chef_12.9.38-1_amd64.deb
       version  12.9.38
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/stable/debian/8/chef_12.9.38-1_amd64.deb
         to file /tmp/install.sh.167/chef_12.9.38-1_amd64.deb
       trying curl...
       trying perl...
       trying python...
       Unable to retrieve a valid package!
       Version: 
       
       Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
       More Chef support resources can be found at https://www.chef.io/support
       
       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.
       
       Metadata URL: https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=debian&pv=8&m=x86_64
       Download URL: https://packages.chef.io/stable/debian/8/chef_12.9.38-1_amd64.deb
       DEBUG OUTPUT FOLLOWS:                                                                                                                                                                             [254/3619]
       
       STDERR from curl:
       
       HTTP/1.1 302 
       Server: nginx
       Date: Tue, 26 Apr 2016 07:30:15 GMT
       Content-Length: 0
       Connection: keep-alive
       Location: https://akamai.bintray.com/6e/6ee8e2f463593f5a78aa3c085348803933e9424c637da37e92dce2db792beaf9?__gda__=exp=1461656535~hmac=865cc0a4f39538d636644db4472c2fd479a7b9f528efae803ec2c719e9e627fd&respon
se-content-disposition=attachment%3Bfilename%3D%22chef_12.9.38-1_amd64.deb%22&response-content-type=application%2Foctet-stream
       
       
       STDERR from perl:
       
       perl: warning: Setting locale failed.
       perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_TIME = "fr_FR.UTF-8",
        LC_MONETARY = "fr_FR.UTF-8",
        LC_MEASUREMENT = "fr_FR.UTF-8",
        LC_NUMERIC = "fr_FR.UTF-8",
        LC_PAPER = "fr_FR.UTF-8",
        LANG = "fr_FR.utf8"
           are supported and installed on your system.
       perl: warning: Falling back to the standard locale ("C").
       Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux
-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at -e line 1.
       BEGIN failed--compilation aborted at -e line 1.
       
       STDERR from python:

       Traceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
           return opener.open(url, data, timeout)
         File "/usr/lib/python2.7/urllib2.py", line 437, in open
           response = meth(req, response)
         File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
           'http', request, response, code, msg, hdrs)
         File "/usr/lib/python2.7/urllib2.py", line 469, in error
           result = self._call_chain(*args)
         File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
           result = func(*args)
         File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
           return self.parent.open(new, timeout=req.timeout)
         File "/usr/lib/python2.7/urllib2.py", line 431, in open
           response = self._open(req, data)
         File "/usr/lib/python2.7/urllib2.py", line 449, in _open
           '_open', req)
         File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
           result = func(*args)
         File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
           context=self._context)
         File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
           raise URLError(err)
       urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
...

```

## Kitchen Diagnose

```
kitchen diagnose --all
---
timestamp: 2016-04-26 07:31:22 UTC
kitchen_version: 1.6.0
plugins:
  driver:
    Docker:
      class: Kitchen::Driver::Docker
      version: 
      api_version: 
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.6.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.6.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.6.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/.kitchen.yml"
    raw_data:
      driver:
        name: docker
        use_sudo: false
      provisioner:
        name: chef_zero
        environments_path: "../../environments"
        roles_path: "../../roles"
      platforms:
      - name: debian-8.4
      suites:
      - name: default
        run_list:
        - recipe[desktop-visualstudiocode]
        attributes: 
  local_config: 
  combined_config:                                                                                                                                                                                        [80/3109]
    filename: 
    raw_data:
      driver:
        name: docker
        use_sudo: false
      provisioner:
        name: chef_zero
        environments_path: "../../environments"
        roles_path: "../../roles"
      platforms:
      - name: debian-8.4
      suites:
      - name: default
        run_list:
        - recipe[desktop-visualstudiocode]
        attributes: 
instances:
  default-debian-84:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      container_id: 1bbd9a0735daf2208661e82788f497571e5e9aa122701808b5e3bd587bb66270
      hostname: localhost
      image_id: 58405b483dc3
      last_action: create
      port: 32769
      ssh_key: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/.kitchen/docker_id_rsa"
    driver:
      binary: docker
      build_context: true
      cap_add: 
      cap_drop: 
      disable_upstart: true
      image: debian:8.4
      kitchen_root: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode"
      log_level: :info
      name: docker
      password: kitchen
      platform: debian
      port: 22
      private_key: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/.kitchen/docker_id_rsa"
      privileged: false
      public_key: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/.kitchen/docker_id_rsa.pub"
      publish_all: false
      remove_images: false
      run_command: "/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes
        -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid"
      security_opt: 
      socket: unix:///var/run/docker.sock
      sudo: true
      test_base_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/test/integration"
      tls: false                                                                                                                                                                                          [27/3109]
      tls_cacert: 
      tls_cert: 
      tls_key: 
      tls_verify: false
      use_cache: true
      use_sudo: false
      username: kitchen
      wait_for_sshd: true
    provisioner:
      attributes: {}
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/environments"
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode"
      log_file: 
      log_level: :info
      name: chef_zero
      nodes_path: 
      profile_ruby: false
      require_chef_omnibus: true
      roles_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/roles"
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[desktop-visualstudiocode]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/test/integration"
    transport:
      compression: true
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode"
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key: 
      test_base_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/test/integration"
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode"
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/home/benben/dev/src/forge-iutinfo.unice.fr/benedett/chef-repo/cookbooks/desktop-visualstudiocode/test/integration"
      version: busser
```

**Comment by cheeseplus** [comment]
This isn't really a test-kitchen failure as such, this is the Chef Omnibus installer failing to be able to grab a package. The reason it can't is that I imagine the container doesn't have curl or wget and also is likely the certificate store isn't configured correctly so perl and python fail out.

Closing the issue as there isn't anything in TK that can or would resolve this particular issue, it occurs in outside software.

**Comment by bdangit** [comment]
for what its worth, I modified my docker container for debian as follows:

Pay attention to the provision_command ref: https://github.com/portertech/kitchen-docker#provision_command

```yaml
- name: debian-8.2-chef-127
    driver_config:
      box: debian:8.2
      platform: debian
      run_command: /sbin/init
      privileged: true
      provision_command:
        - apt-get install wget -y
    provisioner:
      require_chef_omnibus: 12.7
```
