### ISSUE TITLE
Make it easier to troubleshoot the Dummy driver

### ISSUE THREAD

**Issue by tpetchel** [test-kitchen/test-kitchen#1029]
## Description

It's easy enough to make a small mistake in your .kitchen.yml.

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
driver:
  customize:
   memory: 256

suites:
  - name: default
    run_list:
      - recipe[foo::default]
    attributes:
```

```
$ kitchen list
Instance             Driver  Provisioner  Verifier  Transport  Last Action
default-ubuntu-1404  Dummy   ChefZero     Busser    Ssh        <Not Created>
```

Notice that the second `driver` stanza is not properly nested ('properly' in the sense of what the user likely intended), thus overriding the first one completely.  

I understand how Test Kitchen allows you to override certain aspects throughout the file, and that this is not a malformed config per se. But the Dummy driver is likely not what the user wants. Perhaps when the Dummy driver is detected, we can throw a warning and link the user to documentation. (Or perhaps tell the user we expected a `name` under the `driver` section, although not sure if that tells the use what to fix.)

Maybe there are other ways to make this better. I'm open to suggestions.

I'm reporting this because this happened to a Learn Chef user: https://learn.chef.io/local-development/ubuntu/get-started-with-test-kitchen/#comment-2647212850
## Kitchen Version

```
$ kitchen --version
Test Kitchen version 1.7.3
```
## ChefDK Version

```
$ chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
```
## Platform Version

Mac OS
## Replication Case

Create a cookbook, modify your .kitchen.yml like the following, run `kitchen list`.

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
driver:
  customize:
   memory: 256

suites:
  - name: default
    run_list:
      - recipe[foo::default]
    attributes:
```
## Kitchen Output

```
$ kitchen list
Instance             Driver  Provisioner  Verifier  Transport  Last Action
default-ubuntu-1404  Dummy   ChefZero     Busser    Ssh        <Not Created>
```
## Kitchen Diagnose

```
$ kitchen diagnose
kitchen diagnose

---
timestamp: 2016-05-14 13:59:17 UTC
kitchen_version: 1.7.3
instances:
  default-ubuntu-1404:
    platform:
      os_type: unix
      shell_type: bourne
    state_file: {}
    driver:
      customize:
        memory: 256
      kitchen_root: "/private/tmp/chef-server"
      log_level: :info
      name: dummy
      random_failure: false
      sleep: 0
      test_base_path: "/private/tmp/chef-server/test/integration"
    provisioner:
      attributes: {}
...
```
