### ISSUE TITLE
SCP Error 127

### ISSUE THREAD

**Issue by donwlewis** [test-kitchen/test-kitchen#1040]
## Description

Converge is failed with SCP did not finish successfully 127 error.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.8.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0
```

## Platform Version

Windows 8.1

## Replication Case

Run a normal converge on RHEL6.x customer vagrant box.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]
D      ---Nested Exception---
D      Class: Net::SCP::Error
D      Message: SCP did not finish successfully (127):
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/channel.rb:607:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/channel.rb:607:in `do_close'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:598:in `channel_close'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:476:in `dispatch_incoming_packets'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:206:in `process'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/session.rb:170:in `loop'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.1.1/lib/net/ssh/connection/channel.rb:269:in `wait'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:151:in `block in upload'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:148:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:148:in `upload'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner/base.rb:70:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/base.rb:86:in `initialize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:350:in `new'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:350:in `create_new_connection'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/transport/ssh.rb:85:in `connection'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/provisioner/base.rb:66:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:373:in `block in converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:478:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:477:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:369:in `converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:347:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/instance.rb:138:in `converge'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.8.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
zlib(finalizer): the stream was freed prematurely.
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

```yaml
timestamp: 2016-05-27 02:32:00 UTC
kitchen_version: 1.8.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 0.20.0
      api_version: 2
  provisioner:
    ChefSolo:
      class: Kitchen::Provisioner::ChefSolo
      version: 1.8.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.8.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.8.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/lewisd01/Code/chef/cookbooks/rioja/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: rhel6x
      suites:
      - name: default
        run_list:
        - recipe[rio::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: rhel6x
      suites:
      - name: default
        run_list:
        - recipe[rio::default]
        attributes:
instances:
  default-rhel6x:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      port: '2222'
      ssh_key: C:/Users/lewisd01/Code/chef/cookbooks/rioja/.kitchen/kitchen-vagrant/kitchen-rioja-default-rhel6x/.vagrant/machines/default/virtualbox/private_key
      username: vagrant
    driver:
      boot_timeout:
      box: rhel6x
      box_check_update:
      box_download_insecure:
      box_url:
      box_version:
      customize: {}
      gui:
      kitchen_root: C:/Users/lewisd01/Code/chef/cookbooks/rioja
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/Users/lewisd01/Code/chef/cookbooks/rioja/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.20.0/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-rhel6x
    provisioner:
      attributes: {}
      chef_omnibus_install_options:
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_solo_path: "/bin/chef-solo"
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/lewisd01/Code/chef/cookbooks/rioja
      log_file:
      log_level: auto
      name: chef_solo
      nodes_path:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      roles_path:
      root_path: "/tmp/kitchen"
      run_list:
      - recipe[rio::default]
      solo_rb: {}
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Users/lewisd01/Code/chef/cookbooks/rioja/test/integration
    transport:
      compression: true
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/Users/lewisd01/Code/chef/cookbooks/rioja
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: C:/Users/lewisd01/Code/chef/cookbooks/rioja/test/integration
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/lewisd01/Code/chef/cookbooks/rioja
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Users/lewisd01/Code/chef/cookbooks/rioja/test/integration
      version: busser
```

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
