### ISSUE TITLE
Feature Reqeust: Suit Includes/Excludes should take regex

### ISSUE THREAD

**Issue by shortdudey123** [test-kitchen/test-kitchen#1087]
## Description

Currently it looks like (and partially confirmed by @coderanger) test-kitchen suites do not support regex on the includes or excludes directives.  It would be nice to have it supported.

Use case: exclude all versions of one OS and not have to change the excludes list when versions of that OS are added or removed (i.e. `ubuntu-*` when `ubuntu-16.04` is added to the platforms list)

## Current

```
suites:
  - name: default
    excludes:
      - ubuntu-12.04
      - ubuntu-14.04
      - ubuntu-16.04
```

## Requested

```
suites:
  - name: default
    excludes:
      - ubuntu-*
```
