### ISSUE TITLE
WinRM Transport requires the vagrant-winrm Vagrant plugin

### ISSUE THREAD

**Issue by devlife** [test-kitchen/test-kitchen#1109]
## Description

I am trying to run `kitchen list` but am getting the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

However, I have verified that `vagrant-winrm` is installed:

```
C:\source\cookbooks\role_windows_webserver [BETA-89-AddServerSpecTests +2 ~1 -0 !]> vagrant plugin list
vagrant-scp (0.5.7)
vagrant-share (1.1.5, system)
vagrant-winrm (0.7.0)
```
## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

``` ruby
Test Kitchen version 1.11.1
```
## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

``` ruby
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

``` ruby
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
## Platform Version

Windows 10 1607 (Anniversary Update)
## Replication Case

Add the following in `.kitchen.yml` and run `kitchen list`:

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[role_windows_webserver::default]
    attributes:
```
## Kitchen Output

See [this gist](https://gist.github.com/devlife/c565580f77939af58070a6467fa8f248) for debug output
## Kitchen Diagnose

See [this gist](https://gist.github.com/devlife/6444a7e7f4b2779049adc8a1c07546ec)
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by smurawski** [comment]
You may need to pass `communicator: winrm` as part of the driver config if the box file doesn't have that by default in it's Vagrantfile.

**Comment by smurawski** [comment]
Oh, and possibly map some ports.

**Comment by interpeix** [comment]
I have the same problem, any workaround? the machine have in its vagranfile config.vm.communicator = "winrm" but the problem persists.

**Comment by mwrock** [comment]
I suspect you are running an old version of vagrant. You shouldn't need that plugin with modern vagrant versions.

Also unrelated but likely to cause other problems, you should name your platform a string beginning with "win". Example:
```
platforms:
- name: windows-2012R2
  driver_config:
    box: kensykora/windows_2012_r2_standard
```
