### ISSUE TITLE
kitchen test or verify with --parallel option fails

### ISSUE THREAD

**Issue by steinfoc** [test-kitchen/test-kitchen#1125]
## Description

Running this command:
kitchen verify  --concurrency 4 --parallel
Fails with error :
E, [2016-09-21T17:31:01.637023 #7157] ERROR -- Kitchen: Message: Failed to complete #verify action: [undefined method `>' for nil:NilClass]
## Kitchen Version

Test Kitchen version 1.11.1
## ChefDK Version

[root@jim 7zip]# chef --version
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
[root@jim 7zip]#
## Platform Version

Running this command on centos-7 produces a failure, running on windows passes.
## Replication Case

I am using the chef openstack driver https://github.com/test-kitchen/kitchen-openstack and launching 4 windows VMs in parrallel with 4 different windows OS's with kitchen test or kitchen verify.   

If I run sequentially (no --parallel flag) it passes:

> kitchen verify
> PASS
> kitchen verify  --concurrency 4 --parallel
> FAIL  
## Kitchen Output

```
kitchen verify  --concurrency 4 --parallel
....
-----> Verifying <default-WindowsServer2016>...
-----> Verifying <default-Windows7x64>...
-----> Verifying <default-Windows10Enterprise>...
-----> Verifying <default-Windows2012R2>...
       Use `/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes/default` for testing
       Use `/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes/default` for testing
       Use `/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes/default` for testing
       Use `/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes/default` for testing

Target:  winrm://chef@http://10.199.12.54:5985/wsman:3389

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 4 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `>' for nil:NilClass] on default-Windows7x64
>>>>>>     Failed to complete #verify action: [undefined method `>' for nil:NilClass] on default-Windows2012R2
>>>>>>     Failed to complete #verify action: [undefined method `>' for nil:NilClass] on default-WindowsServer2016
>>>>>>     Failed to complete #verify action: [undefined method `>' for nil:NilClass] on default-Windows10Enterprise
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


Below is stack trace from log file:
E, [2016-09-21T17:56:33.544761 #8696] ERROR -- Kitchen: ---Nested Exception---
E, [2016-09-21T17:56:33.544770 #8696] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-09-21T17:56:33.544780 #8696] ERROR -- Kitchen: Message: Failed to complete #verify action: [undefined method `>' for nil:NilClass]
E, [2016-09-21T17:56:33.544795 #8696] ERROR -- Kitchen: ----------------------
E, [2016-09-21T17:56:33.544808 #8696] ERROR -- Kitchen: ------Backtrace-------
E, [2016-09-21T17:56:33.544818 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/rspec_json_formatter.rb:279:in `block in current_control_infos'
E, [2016-09-21T17:56:33.544828 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/rspec_json_formatter.rb:277:in `each'
E, [2016-09-21T17:56:33.544838 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/rspec_json_formatter.rb:277:in `current_control_infos'
E, [2016-09-21T17:56:33.544849 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/rspec_json_formatter.rb:368:in `flush_current_control'
E, [2016-09-21T17:56:33.544859 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/rspec_json_formatter.rb:236:in `close'
E, [2016-09-21T17:56:33.544869 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:189:in `block in notify'
E, [2016-09-21T17:56:33.544880 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:188:in `each'
E, [2016-09-21T17:56:33.544890 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:188:in `notify'
E, [2016-09-21T17:56:33.544900 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:214:in `close'
E, [2016-09-21T17:56:33.544910 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:177:in `ensure in close_after'
E, [2016-09-21T17:56:33.544933 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:177:in `close_after'
E, [2016-09-21T17:56:33.544943 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:156:in `finish'
E, [2016-09-21T17:56:33.544954 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:79:in `report'
E, [2016-09-21T17:56:33.544965 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:111:in `run_specs'
E, [2016-09-21T17:56:33.544976 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/inspec-0.29.0/lib/inspec/runner_rspec.rb:78:in `run'
E, [2016-09-21T17:56:33.544987 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-inspec-0.15.0/lib/kitchen/verifier/inspec.rb:75:in `call'
E, [2016-09-21T17:56:33.545007 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:423:in `block in verify_action'
E, [2016-09-21T17:56:33.545018 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:513:in `call'
E, [2016-09-21T17:56:33.545028 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:513:in `synchronize_or_call'
E, [2016-09-21T17:56:33.545043 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:478:in `block in action'
E, [2016-09-21T17:56:33.545055 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-09-21T17:56:33.545065 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:477:in `action'
E, [2016-09-21T17:56:33.545076 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:415:in `verify_action'
E, [2016-09-21T17:56:33.545086 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-09-21T17:56:33.545097 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `each'
E, [2016-09-21T17:56:33.545107 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-09-21T17:56:33.545118 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:160:in `verify'
E, [2016-09-21T17:56:33.545128 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `public_send'
E, [2016-09-21T17:56:33.545139 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `run_action_in_thread'
E, [2016-09-21T17:56:33.545161 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
E, [2016-09-21T17:56:33.545177 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
E, [2016-09-21T17:56:33.545189 #8696] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
E, [2016-09-21T17:56:33.545200 #8696] ERROR -- Kitchen: ----End Backtrace-----
```
## Kitchen Diagnose

```
---
timestamp: 2016-09-21 17:58:20 UTC
kitchen_version: 1.11.1
plugins:
  driver:
    Openstack:
      class: Kitchen::Driver::Openstack
      version: 3.1.0
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.11.1
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.11.1
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.15.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
      verifier:
        name: inspec
      platforms:
      - name: win10x64-enterprise
        transport:
          name: winrm
      suites:
      - name: default
        run_list:
        - recipe[7zip::default]
  local_config:
    filename: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/.kitchen.cloud.yml"
    raw_data:
      driver:
        name: openstack
        openstack_username: <removed>
        openstack_api_key: <removed>
        openstack_auth_url: <removed>
        require_chef_omnibus: true
        flavor_ref: m2.try.small
        openstack_domain_name: <removed>
        openstack_project_name: <removed>
        openstack_network_name: <removed>
        network_ref: Test_VLAN
        key_name: Craig
        private_key_path: "/dev/null/"
        security_groups:
        - STEX_Security_Group
        server_wait: 45
        block_device_mapping:
          make_volume: true
          device_name: vda
          availability_zone: nova
          delete_on_termination: true
          creation_timeout: 120
      transport:
        name: winrm
        username: chef
        password: asdfasdf.123
      driver_config:
        user_data: cloudbase-init.txt
      provisioner:
        name: chef_zero
      verifier:
        name: inspec
      platforms:
      - name: Windows10Enterprise
        driver:
          image_ref: 93cda271-82e1-4b0a-b668-9333d3e20772
          block_device_mapping:
            snapshot_id: d7431ace-a56c-4eb4-b721-b0972f09347e
      - name: WindowsServer2016
        driver:
          image_ref: 6f8e0130-4865-48dd-a2f4-a359316dc14b
          block_device_mapping:
            snapshot_id: 143d2997-abba-4de0-8653-47c9bc02f5bf
      - name: Windows7x64
        driver:
          image_ref: 3bd72eaa-ac4e-487e-ac36-3fd33be1c1a2
          block_device_mapping:
            snapshot_id: bc8b395d-ccee-4c23-b35f-3aa392d28a47
      - name: Windows2012R2
        driver:
          image_ref: 3e8429f0-f1f4-4570-89ff-7b483a938da4
          block_device_mapping:
            snapshot_id: 07e3f514-c374-482d-be3b-0bc78faa4621
      suites:
      - name: default
        run_list:
        - recipe[7zip::default]
  combined_config:
    filename:
    raw_data:
      driver:
        name: openstack
        openstack_username: <removed>
        openstack_api_key: <removed>
        openstack_auth_url: <removed>
        require_chef_omnibus: true
        flavor_ref: m2.try.small
        openstack_domain_name: <removed>
        openstack_project_name: <removed>
        openstack_network_name: <removed>
        network_ref: Test_VLAN
        key_name: Craig
        private_key_path: "/dev/null/"
        security_groups:
        - STEX_Security_Group
        server_wait: 45
        block_device_mapping:
          make_volume: true
          device_name: vda
          availability_zone: nova
          delete_on_termination: true
          creation_timeout: 120
      provisioner:
        name: chef_zero
      verifier:
        name: inspec
      platforms:
      - name: Windows10Enterprise
        driver:
          image_ref: 93cda271-82e1-4b0a-b668-9333d3e20772
          block_device_mapping:
            snapshot_id: d7431ace-a56c-4eb4-b721-b0972f09347e
      - name: WindowsServer2016
        driver:
          image_ref: 6f8e0130-4865-48dd-a2f4-a359316dc14b
          block_device_mapping:
            snapshot_id: 143d2997-abba-4de0-8653-47c9bc02f5bf
      - name: Windows7x64
        driver:
          image_ref: 3bd72eaa-ac4e-487e-ac36-3fd33be1c1a2
          block_device_mapping:
            snapshot_id: bc8b395d-ccee-4c23-b35f-3aa392d28a47
      - name: Windows2012R2
        driver:
          image_ref: 3e8429f0-f1f4-4570-89ff-7b483a938da4
          block_device_mapping:
            snapshot_id: 07e3f514-c374-482d-be3b-0bc78faa4621
      suites:
      - name: default
        run_list:
        - recipe[7zip::default]
      transport:
        name: winrm
        username: chef
        password: asdfasdf.123
      driver_config:
        user_data: cloudbase-init.txt
instances:
  default-Windows10Enterprise:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 10.199.12.55
      last_action: verify
      server_id: b9405437-5b18-48c9-8d05-db7e51119a46
    driver:
      availability_zone:
      block_device_mapping:
        make_volume: true
        device_name: vda
        availability_zone: nova
        delete_on_termination: true
        creation_timeout: 120
        snapshot_id: d7431ace-a56c-4eb4-b721-b0972f09347e
      flavor_ref: m2.try.small
      floating_ip:
      floating_ip_pool:
      glance_cache_wait_timeout: 600
      image_ref: 93cda271-82e1-4b0a-b668-9333d3e20772
      key_name: Craig
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: openstack
      network_ref: Test_VLAN
      no_ssh_tcp_check: false
      no_ssh_tcp_check_sleep: 120
      openstack_api_key: <removed>
      openstack_auth_url: <removed>
      openstack_domain_name: <removed>
      openstack_network_name: <removed>
      openstack_project_name: <removed>
      openstack_region:
      openstack_service_name:
      openstack_tenant:
      openstack_username: <removed>
      port: '22'
      private_ip_order: 0
      private_key_path: "/dev/null/"
      public_ip_order: 0
      public_key_path: "/dev/null/.pub"
      security_groups:
      - STEX_Security_Group
      server_name:
      server_name_prefix:
      server_wait: 45
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      use_ipv6: false
      user_data: cloudbase-init.txt
    provisioner:
      attributes: {}
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_file:
      log_level: auto
      max_retries: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[7zip::default]
      sudo:
      sudo_command:
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: asdfasdf.123
      port: 5985
      rdp_port: 3389
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      username: chef
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: inspec
      root_path: "$env:TEMP\\verifier"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes"
  default-WindowsServer2016:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 10.199.12.56
      last_action: verify
      server_id: 20084c42-1ddc-41d5-83da-61b44a8ba285
    driver:
      availability_zone:
      block_device_mapping:
        make_volume: true
        device_name: vda
        availability_zone: nova
        delete_on_termination: true
        creation_timeout: 120
        snapshot_id: 143d2997-abba-4de0-8653-47c9bc02f5bf
      flavor_ref: m2.try.small
      floating_ip:
      floating_ip_pool:
      glance_cache_wait_timeout: 600
      image_ref: 6f8e0130-4865-48dd-a2f4-a359316dc14b
      key_name: Craig
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: openstack
      network_ref: Test_VLAN
      no_ssh_tcp_check: false
      no_ssh_tcp_check_sleep: 120
      openstack_api_key: <removed>
      openstack_auth_url: <removed>
      openstack_domain_name: <removed>
      openstack_network_name: <removed>
      openstack_project_name: <removed>
      openstack_region:
      openstack_service_name:
      openstack_tenant:
      openstack_username: <removed>
      port: '22'
      private_ip_order: 0
      private_key_path: "/dev/null/"
      public_ip_order: 0
      public_key_path: "/dev/null/.pub"
      security_groups:
      - STEX_Security_Group
      server_name:
      server_name_prefix:
      server_wait: 45
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      use_ipv6: false
      user_data: cloudbase-init.txt
    provisioner:
      attributes: {}
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_file:
      log_level: auto
      max_retries: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[7zip::default]
      sudo:
      sudo_command:
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: asdfasdf.123
      port: 5985
      rdp_port: 3389
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      username: chef
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: inspec
      root_path: "$env:TEMP\\verifier"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes"
  default-Windows7x64:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 10.199.12.54
      last_action: verify
      server_id: 41a3be1f-11f9-4e4a-ae1c-e4664ff9f434
    driver:
      availability_zone:
      block_device_mapping:
        make_volume: true
        device_name: vda
        availability_zone: nova
        delete_on_termination: true
        creation_timeout: 120
        snapshot_id: bc8b395d-ccee-4c23-b35f-3aa392d28a47
      flavor_ref: m2.try.small
      floating_ip:
      floating_ip_pool:
      glance_cache_wait_timeout: 600
      image_ref: 3bd72eaa-ac4e-487e-ac36-3fd33be1c1a2
      key_name: Craig
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: openstack
      network_ref: Test_VLAN
      no_ssh_tcp_check: false
      no_ssh_tcp_check_sleep: 120
      openstack_api_key: <removed>
      openstack_auth_url: <removed>
      openstack_domain_name: <removed>
      openstack_network_name: <removed>
      openstack_project_name: <removed>
      openstack_region:
      openstack_service_name:
      openstack_tenant:
      openstack_username: <removed>
      port: '22'
      private_ip_order: 0
      private_key_path: "/dev/null/"
      public_ip_order: 0
      public_key_path: "/dev/null/.pub"
      security_groups:
      - STEX_Security_Group
      server_name:
      server_name_prefix:
      server_wait: 45
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      use_ipv6: false
      user_data: cloudbase-init.txt
    provisioner:
      attributes: {}
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_file:
      log_level: auto
      max_retries: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[7zip::default]
      sudo:
      sudo_command:
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: asdfasdf.123
      port: 5985
      rdp_port: 3389
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/integration"
      username: chef
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/var/lib/jenkins/workspace/ChefTestUpload/7zip"
      log_level: :info
      name: inspec
      root_path: "$env:TEMP\\verifier"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: "/var/lib/jenkins/workspace/ChefTestUpload/7zip/test/recipes"
  default-Windows2012R2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 10.199.12.58
      last_action: verify
      server_id: f5906549-2e8b-488f-b82c-4379c340677a
    driver:
      availability_zone:
      block_device_mapping:
        make_volume: true
        device_name: vda
        availability_zone: nova
        delete_on_termination: true
        creation_timeout: 120
        snapshot_id: 07e3f514-c374-482d-be3b-0bc78faa4621
      flavor_ref: m2.try.small
      floating_ip:
      floating_ip_pool:
      glance_cache_wait_timeout: 600
      image_ref: 3e8429f0-f1f4-4570-89ff-7b483a938da4
      key_name: <removed>
      kitchen_root: "/var/lib/jenkins
```
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
