### ISSUE TITLE
Vagrant drivers brings up virtualbox machine with 'cable connected' disabled option

### ISSUE THREAD

**Issue by etki** [test-kitchen/test-kitchen#1143]
## Description

When i create vagrant machine via `kitchen converge`, it starts with unplugged NAT interface, so kitchen can't connect to it.

**I'm not yet familiar with kitchen infrastructure. This may refer to bento image rather than test kitchen.**

## Kitchen Version

```ruby
Test Kitchen version 1.13.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: ERROR
kitchen version: ERROR
```
**I'm not using chef shell-init**

## Ruby Version

```ruby
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
```

## Platform Version

Linux Mint 17.2

## Replication Case

I have following `.kitchen.yml`

```yml---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[<redacted>::default]
    attributes:
```

When i run `kitchen converge`, resulting virtualbox machine is created with `connected` NAT switch turned off.

Virtualbox version: 5.0.28r111378
Vagrant version: Vagrant 1.8.4
Image version: bento/ubuntu-16.04 (virtualbox, 2.3.0)
