### ISSUE TITLE
Failed to complete #create action: [undefined method `[]' for nil:NilClass]

### ISSUE THREAD

**Issue by gsaslis** [test-kitchen/test-kitchen#1157]
## Description

So, my test kitchen decided to stop working today and I've been banging my head on the wall for the last hour trying to work out what it was that might have changed in my environment that could be causing the below issue: 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

BOTH 1.13.2 and 1.14.0

```ruby
kitchen --version
Expected array default value for '--driver'; got "kitchen-vagrant" (string)
Test Kitchen version 1.14.0
```

```ruby
kitchen --version
Test Kitchen version 1.13.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
chef --version                         
Chef Development Kit Version: 0.18.30
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.2
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby --version    
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin13]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

macOS Sierra 10.12.1

## Replication Case

Use following .kitchen.yml and run `kitchen converge` 

```
---
driver:
  name: ec2
  instance_type: m3.medium
  region: eu-west-1
  availability_zone: a

transport:
  name: sftp
  ssh_key: ~/.ssh/cytech.pem
  connection_timeout: 10
  connection_retries: 5
  username: root

provisioner:
  name: chef_zero
  root_path: /tmp/packer-chef-client
  sudo: false

platforms:
  - name: opensuse-13.2
    driver:
      name: ec2
      image_id: ami-3a6cc64d

suites:
  - name: default
    run_list:
    attributes:
```

## Kitchen Output / Diagnose

All outputs here: https://gist.github.com/gsaslis/798bb00ffbfc9b489cb209932d97fbc7
