### ISSUE TITLE
ssh_key is not read and sent to the args for ssh transport

### ISSUE THREAD

**Issue by rtacconi** [test-kitchen/test-kitchen#1169]
## Description
In this line https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L274 opts do not have the ssh key so Test Kitchen cannot connect to the instance. This is my config:
```
---
driver:
  name: ec2
  transport:
    ssh_key: /Users/me/.ssh/uswest2-emv
    username: ubuntu
  aws_ssh_key_id: uswest2-env
  region: us-west-2
  availability_zone: us-west-2a
  instance_type: t2.micro
  associate_public_ip: true
  # subnet_id: subnet-208d9XXX
  subnet_id: subnet-1a003xxx
  security_group_ids: ["sg-604e7dxx"]
  tags:
    Name: 'test-kitchen x-cookbyzook <%= Time.now.strftime("%d/%m/%Y %H:%M") %>'

platforms:
  - name: ubuntu1404
    driver:
      image_id: ami-5e02dbxx # a custom image coming from ubuntu1004 just use an Ubuntu image

suites:
  - name: test1
    run_list:
```

Briefly describe the issue

## Kitchen Version
Test Kitchen version 1.14.2

```ruby
# Copy-paste your results here
```

## ChefDK Version
ChefDK, not use, these are the gems I am using
```
chef -v 12.8.1
chef-vault -v 2.9.0
test-kitchen -v 1.14.2
kitchen-vagrant -v 0.20.0
kitchen-inspec -v 0.12.5
berkshelf -v 4.3.5
chefspec -v 5.2.0
inspec -v 0.35.0
ffi -v 1.5.0
docker-api -v 1.26.2
net-ssh -v 3.2.0
```
## Ruby Version

```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
```

## Platform Version

OXS 10.12.1 (Sierra). I am not using ChefDK, the the gems above.

## Replication Case

`transport.key` is not sent to https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/ssh.rb#L274. So Test Kitchen never connects to a created instance.

## Kitchen Output

```
-----> Creating <test1-ubuntu1404>...
D      Image for test1-ubuntu1404: m2x-ubuntu1404 1475558149.  Architecture: x86_64, Virtualization: hvm, Storage: ebs standard, Created: 2016-10-04T05:26:37.000Z
       Detected platform: ubuntu version 1475558149 on x86_64. Instance Type: t2.micro. Default username: ubuntu (default).
D      No SSH username specified: using default username ubuntu  for image ami-5e02db3e, which we detected as ubuntu 1475558149 x86_64.
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      Creating EC2 instance in region us-west-2 with properties:
D      - instance_type = "t2.micro"
D      - ebs_optimized = false
D      - image_id = "ami-5e02db3e"
D      - key_name = "uswest2-stage"
D      - private_ip_address = nil
D      - placement = {:availability_zone=>"us-west-2a"}
D      - network_interfaces = [{:device_index=>0, :associate_public_ip_address=>true, :delete_on_termination=>true, :subnet_id=>"subnet-1a00326c", :groups=>["sg-604e7d07"]}]
       Instance <i-095f955fdbc92f25d> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-095f955fdbc92f25d> created.
       Waited 0/300s for instance <i-095f955fdbc92f25d> to become ready.
       Waited 5/300s for instance <i-095f955fdbc92f25d> to become ready.
       Waited 10/300s for instance <i-095f955fdbc92f25d> to become ready.
       Waited 15/300s for instance <i-095f955fdbc92f25d> to become ready.
       Waited 20/300s for instance <i-095f955fdbc92f25d> to become ready.
       Waited 25/300s for instance <i-095f955fdbc92f25d> to become ready.
       EC2 instance <i-095f955fdbc92f25d> ready.
D      [SSH] opening connection to ubuntu@35.166.93.113<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 35.166.93.113:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@35.166.93.113<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"ubuntu"}>
D      [SSH] connection failed (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       Waiting for SSH service on 35.166.93.113:22, retrying in 3 seconds
D      [SSH] opening connection to ubuntu@35.166.93.113<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"ubuntu"}>
```

```ruby
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
```

## Kitchen Diagnose

It runs without any issue but I cannot paste it here since it has sensitive values.

## NOTE:

I am using ec2-kitchen plugin but transport.sskh_key is a test-kitchen functionality

**Comment by cheeseplus** [comment]
The issue here is that transport doesn't go under `driver:`, it's either Global or platform specific

See: https://github.com/test-kitchen/kitchen-ec2#quick-start

ex.
```
driver:
  name: ec2
  instance_type: t2.medium
  security_group_ids: ["sg-a1c3b1db"]
  subnet_id: subnet-46b55431
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>

transport:
  ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
```

**Comment by rtacconi** [comment]
Thank you. I would like to point out that the quick start, at step 2, it is not clear at all:

`2. Edit .kitchen.yml and add the aws_ssh_key_id to driver and a transport with an ssh_key:`

I understand:
```
driver:
  aws_ssh_key_id:
  transport:
    ssh_key:
```
