### ISSUE TITLE
kitchen login doesn't pass ssh password from kitchen.yml

### ISSUE THREAD

**Issue by ifeltsweet** [test-kitchen/test-kitchen#1175]
## Description

`kitchen login` doesn't pass ssh password from kitchen.yml. My config is below. What happens is that when doing `kitchen login` a prompt to enter password for requested username is shown instead of automatically authenticating.

```
$ myuser@127.0.0.1's password: 
```

```
platforms:
  - name: debian-7.3.0
    driver:
      username: myuser
      password: mypass
```

## Kitchen Version

```ruby
Test Kitchen version 1.14.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2
```

## Platform Version

macosx 10.9.5
