### ISSUE TITLE
Message: SCP upload failed (open failed (1)) when additional_copy_path = '.'

### ISSUE THREAD

**Issue by stephenconnolly1** [test-kitchen/test-kitchen#1191]
## Description

Unable to converge Ansible playbooks. Failure occurs during transfer of the ansible playbook directory structure up to the remote host

## Kitchen Version

Test Kitchen version 1.15.0

## ChefDK Version
Not applicable

## Ansible version

ansible 2.2.1.0

## Ruby Version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

MacOs client, Running against Centos 7.1

## Replication Case

Running a very basic ansible playbook with ~15 files. 
Added logging to the output as:

## Kitchen Output

```
       Transferring files to <default-centos-71>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/ansible.cfg to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/callback_plugins to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/chefignore to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/filter_plugins to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/Gemfile to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/Gemfile.lock to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/group_vars to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/host_vars to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/hosts to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/inventory to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/library to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/lookup_plugins to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/makefile to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/modules to /tmp/kitchen
D      Async uploading /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs/playbook.yml to /tmp/kitchen
D      Cleaning up local sandbox in /var/folders/ly/f2fhypt108d4ykkyxh4ycr3c0000gn/T/default-centos-71-sandbox-20170208-52526-4gozvs
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [SCP did not finish successfully (): ] on default-centos-71
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [SCP did not finish successfully (): ] on default-centos-71
```

## Kitchen Diagnose

```
(aws) Stephens-MacBook-Pro:platform-beta-build stephenconnolly$ bundle exec kitchen diagnose --all
---
timestamp: 2017-02-08 15:34:03 UTC
kitchen_version: 1.15.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.0.0
      api_version: 2
  provisioner:
    AnsiblePlaybook:
      class: Kitchen::Provisioner::AnsiblePlaybook
      version:
      api_version:
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.15.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.15.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/Users/stephenconnolly/src/platform-beta-build/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: ansible_playbook
        hosts: localhost
        require_chef_for_busser: false
        require_ruby_for_busser: false
      platforms:
      - name: centos-7.1
      suites:
      - name: default
        provisioner:
          name: ansible_playbook
          playbook: test/integration/default/test.yml
          additional_copy_path:
          - "."
      verifier:
        ruby_bindir: "/usr/bin"
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: ansible_playbook
        hosts: localhost
        require_chef_for_busser: false
        require_ruby_for_busser: false
      platforms:
      - name: centos-7.1
      suites:
      - name: default
        provisioner:
          name: ansible_playbook
          playbook: test/integration/default/test.yml
          additional_copy_path:
          - "."
      verifier:
        ruby_bindir: "/usr/bin"
instances:
  default-centos-71:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      last_error: Net::SCP::Error
      port: '2222'
      ssh_key: "/Users/stephenconnolly/src/platform-beta-build/.kitchen/kitchen-vagrant/kitchen-platform-beta-build-default-centos-71/.vagrant/machines/default/virtualbox/private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: bento/centos-7.1
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      gui:
      kitchen_root: "/Users/stephenconnolly/src/platform-beta-build"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - "/Users/stephenconnolly/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/Users/stephenconnolly/src/platform-beta-build/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/Users/stephenconnolly/src/platform-beta-build/vendor/bundle/ruby/2.4.0/gems/kitchen-vagrant-1.0.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-centos-71.vagrantup.com
    provisioner:
      additional_copy_path:
      - "."
      additional_copy_role_path: false
      ansible_apt_repo: ppa:ansible/ansible
      ansible_cfg_path:
      ansible_check: false
      ansible_connection: local
      ansible_diff: false
      ansible_host_key_checking: true
      ansible_inventory:
      ansible_inventory_file:
      ansible_limit:
      ansible_omnibus_remote_path: "/opt/ansible"
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      ansible_platform: ''
      ansible_playbook_command:
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/SLE_12/systemsmanagement.repo
      ansible_source_rev:
      ansible_sudo: true
      ansible_vault_password_file:
      ansible_verbose: false
      ansible_verbosity: 1
      ansible_version:
      ansible_yum_repo:
      ansiblefile_path:
      callback_plugins_path:
      chef_bootstrap_url: https://www.getchef.com/chef/install.sh
      command_prefix:
      enable_yum_epel: false
      env_vars: {}
      extra_vars: {}
      filter_plugins_path:
      ftp_proxy:
      group_vars_path: "/Users/stephenconnolly/src/platform-beta-build/group_vars"
      host_vars_path:
      hosts: localhost
      http_proxy:
      https_proxy:
      idempotency_test:
      ignore_extensions_from_root:
      - ".pyc"
      ignore_paths_from_root: []
      kerberos_conf_file:
      kitchen_root: "/Users/stephenconnolly/src/platform-beta-build"
      library_plugins_path:
      lookup_plugins_path:
      max_retries: 1
      modules_path:
      name: ansible_playbook
      no_proxy:
      playbook: test/integration/default/test.yml
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/SLE_12/devel:languages:python.repo
      recursive_additional_copy_path:
      require_ansible_omnibus: false
      require_ansible_repo: true
      require_ansible_source: false
      require_chef_for_busser: false
      require_pip: false
      require_ruby_for_busser: false
      require_windows_support: false
      requirements_path: false
      retry_on_exit_code: []
      role_name:
      roles_path: "/Users/stephenconnolly/src/platform-beta-build/roles"
      root_path: "/tmp/kitchen"
      shell_command: sh
      ssh_known_hosts:
      sudo: true
      sudo_command: sudo -E
      tags: []
      test_base_path: "/Users/stephenconnolly/src/platform-beta-build/test/integration"
      update_package_repos: true
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/stephenconnolly/src/platform-beta-build"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/Users/stephenconnolly/src/platform-beta-build/test/integration"
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/Users/stephenconnolly/src/platform-beta-build"
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/usr/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/Users/stephenconnolly/src/platform-beta-build/test/integration"
      version: busser
```
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
