### ISSUE TITLE
Message: Could not load the 'ansible_playbook' provisioner from the load path

### ISSUE THREAD

**Issue by ACDoyle** [test-kitchen/test-kitchen#1197]
## Description
I cannot create kitchen.  [root@dev1 ansible-kitchen]# bundle exec kitchen create

```
[root@dev1 ansible-kitchen]# bundle exec kitchen create
-----> Starting Kitchen (v1.15.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ansible_playbook' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Kitchen Version
Test Kitchen version 1.15.0

```ruby
[root@dev1 ansible-kitchen]# gem list

*** LOCAL GEMS ***

artifactory (2.7.0)
bigdecimal (1.2.0)
bundler (1.14.5)
diff-lcs (1.3)
io-console (0.4.2)
json (1.7.7)
kitchen-ansible (0.45.10)
kitchen-vagrant (1.0.2)
mixlib-install (2.1.12)
mixlib-shellout (2.2.7)
mixlib-versioning (1.1.0)
multi_json (1.12.1)
net-scp (1.2.1)
net-ssh (4.1.0)
net-ssh-gateway (1.3.0)
net-telnet (0.1.1)
psych (2.0.0)
rdoc (4.0.0)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
safe_yaml (1.0.4)
serverspec (2.38.0)
sfl (2.3)
specinfra (2.67.1)
test-kitchen (1.15.0)
thor (0.19.4)

```
## Platform Version

Red Hat Enterprise Linux Server release 7.3 (Maipo)
Ansible & VirtualBox & Vagrant
```
[root@dev1 ansible-kitchen]# ansible --version
ansible 2.2.0.0

[root@dev1 ansible-kitchen]# vagrant --version
Vagrant 1.9.1

```

```
[root@dev1 ansible-kitchen]# cat .kitchen.yml
---
driver:
 name: vagrant

provisioner:
 name: ansible_playbook
 playbook: playbook.yml
 hosts: all
 require_chef_for_busser: false
 require_ruby_for_busser: true

platforms:
 - name: ubuntu
   driver_config:
    box: "ubuntu/trusty64"
suites:
 - name: default

verifier:
 ruby_bindir: '/usr/bin'
````
## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
[root@dev1 ansible-kitchen]# bundle exec kitchen create
-----> Starting Kitchen (v1.15.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ansible_playbook' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

```
[root@dev1 ansible-kitchen]# kitchen diagnose --all
---
timestamp: '2017-02-24 14:06:38 UTC'
kitchen_version: 1.15.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.0.2
      api_version: 2
  provisioner:
    AnsiblePlaybook:
      class: Kitchen::Provisioner::AnsiblePlaybook
      version:
      api_version:
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.15.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.15.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: /ANSIBLE/ansible-kitchen/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: ansible_playbook
        playbook: playbook.yml
        hosts: all
        require_chef_for_busser: false
        require_ruby_for_busser: true
      platforms:
      - name: ubuntu
        driver_config:
          box: ubuntu/trusty64
      suites:
      - name: default
      verifier:
        ruby_bindir: /usr/bin
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: ansible_playbook
        playbook: playbook.yml
        hosts: all
        require_chef_for_busser: false
        require_ruby_for_busser: true
      platforms:
      - name: ubuntu
        driver_config:
          box: ubuntu/trusty64
      suites:
      - name: default
      verifier:
        ruby_bindir: /usr/bin
instances:
  default-ubuntu:
    platform:
      os_type: unix
      shell_type: bourne
    state_file: {}
    driver:
      boot_timeout:
      box: ubuntu/trusty64
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: /tmp/omnibus/cache
      cachier:
      customize: {}
      gui:
      kitchen_root: /ANSIBLE/ansible-kitchen
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - /root/.kitchen/cache
        - /tmp/omnibus/cache
        - 'create: true'
      test_base_path: /ANSIBLE/ansible-kitchen/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: /usr/local/share/gems/gems/kitchen-vagrant-1.0.2/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-ubuntu.vagrantup.com
    provisioner:
      additional_copy_path:
      additional_copy_role_path: false
      ansible_apt_repo: ppa:ansible/ansible
      ansible_cfg_path:
      ansible_check: false
      ansible_connection: local
      ansible_diff: false
      ansible_host_key_checking: true
      ansible_inventory:
      ansible_inventory_file:
      ansible_limit:
      ansible_omnibus_remote_path: /opt/ansible
      ansible_omnibus_url: https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh
      ansible_platform: ''
      ansible_playbook_command:
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/SLE_12/systemsmanagement.repo
      ansible_source_rev:
      ansible_source_url: git://github.com/ansible/ansible.git
      ansible_sudo: true
      ansible_vault_password_file:
      ansible_verbose: false
      ansible_verbosity: 1
      ansible_version:
      ansible_yum_repo:
      ansiblefile_path:
      callback_plugins_path:
      chef_bootstrap_url: https://www.getchef.com/chef/install.sh
      command_prefix:
      enable_yum_epel: false
      env_vars: {}
      extra_vars: {}
      filter_plugins_path:
      ftp_proxy:
      group_vars_path:
      host_vars_path:
      hosts: all
      http_proxy:
      https_proxy:
      idempotency_test:
      ignore_extensions_from_root:
      - .pyc
      ignore_paths_from_root: []
      kerberos_conf_file:
      kitchen_root: /ANSIBLE/ansible-kitchen
      library_plugins_path:
      lookup_plugins_path:
      max_retries: 1
      modules_path:
      name: ansible_playbook
      no_proxy:
      playbook: playbook.yml
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/SLE_12/devel:languages:python.repo
      recursive_additional_copy_path:
      require_ansible_omnibus: false
      require_ansible_repo: true
      require_ansible_source: false
      require_chef_for_busser: false
      require_pip: false
      require_ruby_for_busser: true
      require_windows_support: false
      requirements_path: false
      retry_on_exit_code: []
      role_name:
      roles_path: /ANSIBLE/ansible-kitchen
      root_path: /tmp/kitchen
      shell_command: sh
      ssh_known_hosts:
      sudo: true
      sudo_command: sudo -E
      tags: []
      test_base_path: /ANSIBLE/ansible-kitchen/test/integration
      update_package_repos: true
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: /ANSIBLE/ansible-kitchen
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: /ANSIBLE/ansible-kitchen/test/integration
      username: root
    verifier:
      busser_bin: /tmp/verifier/bin/busser
      chef_omnibus_root: /opt/chef
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: /ANSIBLE/ansible-kitchen
      log_level: :info
      name: busser
      root_path: /tmp/verifier
      ruby_bindir: /usr/bin
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: /ANSIBLE/ansible-kitchen/test/integration
      version: busser
```
