### ISSUE TITLE
Suites not merged between config files

### ISSUE THREAD

**Issue by lobsterdore** [test-kitchen/test-kitchen#1199]
## Description

I have two .kitchen.yml config files, .kitchen.yml and .kitchen.vagrant.yml, my main list of suites lives inside .kitchen.yml.

I have a need to override some of the driver settings on a per suite basis in .kitchen.vagrant.yml, eg.

```YAML
# .kitchen.yml
...

suites:
  - name: suite_one

  - name: suite_two

  - name: suite_three

  - name: suite_four
```

```YAML
# .kitchen.vagrant.yml
...

suites:
  - name: suite_three
    driver:
      provision: true
      vagrantfiles:
        - test/vagrant.rb
```

I can override settings just fine for suite_three when using my vagrant config file, however I will not be able to execute any of the non-overridden suites (eg. suite_one, two or four).

It seems that the suite list in my secondary config file replaces. rather than merges with, the suite list in my main config file.

## Kitchen Version

v1.15.0

## Ruby Version

```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Platform Version

OS X El Capitan  10.11.6

## Replication Case

See description

## Kitchen Output

```
No instances for regex `suite_one', try running `kitchen list'
```

Kitchen list just shows suite_three
