### ISSUE TITLE
Shell verifier clobbers environment variables

### ISSUE THREAD

**Issue by smith** [test-kitchen/test-kitchen#1209]
## Description

When using the shell verifier and setting

```yaml
verifier:
  name: shell
  shellout_opts:
    environment:
      FOO: bar
```

the command will not be run with `FOO=bar`, because [`merge_state_to_env`](https://github.com/test-kitchen/test-kitchen/blob/3768d09fd1f0383fce57a261267bbfcf9a4f2a10/lib/kitchen/verifier/shell.rb#L87-L96) does a shallow merge, wiping out the `:environment` key.
