### ISSUE TITLE
Kitchen converge fails on second converge

### ISSUE THREAD

**Issue by ssirobertreilly** [test-kitchen/test-kitchen#1212]
## Description
Running kitchen converge a second time after a successful run fails with:

FYI, I have also seen this behavior with chef and test kitchen when I have 5 or 6 suites one or two would fail second converge ( if you think that might be relevant I will create a gist)

```
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: connection closed by remote host>)
```

## Kitchen Version
kitchen -v
Test Kitchen version 1.16.0

### Ruby Version
```ruby
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

## ChefDK Version
using ansible, 
```
ansible --version
ansible 2.2.1.0
  config file = /Users/robert_reilly/ansible-test/ansible.cfg
  configured module search path = Default w/o overrides
```

## Platform Version

universal.x86_64-darwin15 dev machine
centos-7.2 is the target machine

## Kitchen Output

```
   "module_name": "command"
           },
           "rc": 0,
           "start": "2017-03-28 15:13:15.128901",
           "stderr": "Shutdown scheduled for Tue 2017-03-28 15:14:15 UTC, use 'shutdown -c' to cancel.",
           "stdout": "",
           "stdout_lines": [],
           "warnings": [
        "Consider using 'become', 'become_method', and 'become_user' rather than running sudo"
           ]
       }
        [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather
       than running sudo


       PLAY RECAP *********************************************************************
       localhost                  : ok=5    changed=3    unreachable=0    failed=0

       Finished converging <default-centos-72> (1m21.02s).
-----> Kitchen is finished. (1m56.54s)
-----> Starting Kitchen (v1.16.0)
-----> Converging <default-centos-72>...
       Preparing files for transfer
       Preparing playbook
       Preparing inventory
       Preparing modules
       nothing to do for modules
       Preparing roles
       Preparing ansible.cfg file
       Found existing ansible.cfg
       Preparing group_vars
       nothing to do for group_vars
       Preparing additional_copy_path
       Preparing host_vars
       nothing to do for host_vars
       Preparing hosts file
       Preparing spec
       nothing to do for spec
       Preparing library plugins
       nothing to do for library plugins
       Preparing callback plugins
       nothing to do for callback plugins
       Preparing filter_plugins
       nothing to do for filter_plugins
       Preparing lookup_plugins
       nothing to do for lookup_plugins
       Preparing additional_ssh_private_keys
       nothing to do for additional_ssh_private_keys
       Finished Preparing files for transfer
       Installing ansible, will try to determine platform os
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: connection closed by remote host>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: connection closed by remote host>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: connection closed by remote host>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::Disconnect: connection closed by remote host>)
$$$$$$ [SSH] connection failed, terminating (#<Net::SSH::Disconnect: connection closed by remote host>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-72>.  Please see .kitchen/logs/default-centos-72.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by ssirobertreilly** [comment]
Here is the .kitchen.yml
```
---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all
  require_chef_for_busser: false
  # name: ansible_playbook
  # roles_path: roles
  # playbook: playbooks/nginx.yaml
  # require_ansible_repo: true
  # ansible_verbose: true
  # hosts: default
  # require_ansible_repo: true

platforms:
  - name: centos-7.2

suites:
  - name: default
    provisioner:
      hosts: default-centos-72
      require_ansible_repo: true
      playbook: playbooks/nginx.yml
```
