### ISSUE TITLE
Message: Could not load the 'propeller' driver from the load path. 

### ISSUE THREAD

**Issue by rj-reilly** [test-kitchen/test-kitchen#1219]
## Description
I am reaching out here because i have not  been able to get any help on irc or else where. 
I really appreciate any help i can get i have spent many hours on this and I stumped...( i am sure it is obvious, i just cant see it) the env works for kitchen if use vagrant driver no problem.

I created a driver with kitchen driver create, added my logic. published my gem

can be installed with gem install kitchen-propeller

here is the source: [https://github.com/rj-reilly/kitchen-propeller](https://github.com/rj-reilly/kitchen-propeller)
Briefly describe the issue
no matter what version of ruby i use or how i install this gem test-kitchen cannot find it. I have compared it to other drivers but cannot get kitchen to find it
## Kitchen Version
Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.16.0

```

## ChefDK Version
using ansible 

```ruby
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

/home/vagrant/.rvm/rubies/ruby-2.2.0/bin/gem
/home/vagrant/.rvm/rubies/ruby-2.2.0/bin/ruby
```

## Platform Version

centos 7.2

## Replication Case

Install the gem and try to use it 

## Kitchen Output

```ruby
[https://gist.github.com/rj-reilly/b49837359305816de5fddbebb07d031f](https://gist.github.com/rj-reilly/b49837359305816de5fddbebb07d031f)
```

## Kitchen Diagnose
see above

```yaml
---
driver:
   name: propeller
   driver_options:
   tenantName: 'XX-LAB'
   emailAddress:  'robert_reilly@xx.com'
   networkName:  'XX-LAB'
   flavorName:  'm1.large'
   vmName: 'testkitchen.utl'
   volumes:  [{volumeSize: 1, volumeName: services03-volume, device: /dev/vdb}]
   securityGroup:  ['default']
   endpoint: http://xx:8080/v2/api/server


provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: centos-7.2

verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      hosts: default-centos-72
      require_ansible_repo: true
      playbook: playbooks/teamcity.yml
    verifier:
      patterns:
      - roles/teamcity/spec/*_spec.rb
```

## gem env 
```ruby

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/vagrant/.rvm/gems/ruby-2.2.0
  - RUBY EXECUTABLE: /home/vagrant/.rvm/rubies/ruby-2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /home/vagrant/.rvm/gems/ruby-2.2.0/bin
  - SPEC CACHE DIRECTORY: /home/vagrant/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/vagrant/.rvm/gems/ruby-2.2.0
     - /home/vagrant/.rvm/gems/ruby-2.2.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/vagrant/.rvm/gems/ruby-2.2.0/bin
     - /home/vagrant/.rvm/gems/ruby-2.2.0@global/bin
     - /home/vagrant/.rvm/rubies/ruby-2.2.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /home/vagrant/.rvm/bin
     - /home/vagrant/.rvm/bin
```

## ruby -e 'puts $:'

```ruby 

/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/x86_64-linux
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/vendor_ruby/2.2.0
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/vendor_ruby
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0
/home/vagrant/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux
```
## gem list
```ruby
*** LOCAL GEMS ***

...
kitchen-ansible (0.46.4)
kitchen-inspec (0.18.0)
kitchen-propeller (0.1.8)
test-kitchen (1.16.0)
...
```
