### ISSUE TITLE
synced_folders not mounted on Windows guests

### ISSUE THREAD

**Issue by kevinjpickard** [test-kitchen/test-kitchen#1221]
## Description

The folders specified with `synced_folders` do not mount on Windows hosts. No error message is displayed, but all tests that depend on these files fail, saying the file doesn't exist. Manual inspection shows that these folders were not accessible via Windows Explorer nor Powershell. Files are mounted just fine in linux guests. The vagrant boxes were created following [this guide](http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/). I have tested this against Windows 7 and Windows 10, both Enterprise and 64 bit.

## Kitchen Version

```ruby
Test Kitchen version 1.15.0
```

## ChefDK Version

_not using chef_

## Ruby Version

```ruby
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

## Platform Version

macOS Sierra 10.12.4

## Replication Case

```
---
driver:
  name: vagrant
  synced_folders:
    - ['.', 'C:\home\vagrant']
  ssh_key: ~/.vagrant.d/insecure_private_key
  ssh:
    insert_key: false

platforms:
  - name: windows-2012r2
    shell_type: powershell
    transport:
      name: winrm

suites:
  - name: default
```

## Kitchen Output

```ruby
       ==> default: Mounting shared folders...
           default: C:\home\vagrant => /Users/kevin/Documents/github/kitchen/test
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [WinRM] Established
```

## Kitchen Diagnose
[gist](https://gist.github.com/kevinjpickard/280020b9846a82498167665624eb4c98)
