### ISSUE TITLE
kitchen converge Failed to complete #converge action: [no implicit conversion of nil into String]

### ISSUE THREAD

**Issue by dvenrao** [test-kitchen/test-kitchen#1238]
## Description

When I run kitchen create no issues. after this when i run kitchen converge it always giving error no implicit conversion of nil into String. Using test-kitchen via ChefDK

## Kitchen Version
```ruby
Test Kitchen version 1.16.0
```

## ChefDK Version
```ruby
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-05-24T09:45:44.801656 20928] 2017-05-24T09:45:44.802156 20928] 2017-05-24T09:45:44.802656 20928] 2017-05-24T09:45:44.802656 20928] 2017-05-24T09:45:44.918679 20928] 2017-05-24T09:45:44.918679 20928] 5.6.0
kitchen version: 1.16.0
```

## Platform Version
Windows 7

## Kitchen Output

```ruby
> kitchen converge default-centos65 -l debug
-----> Starting Kitchen (v1.16.0)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/Berksfile, loading Berkshelf
D      Berkshelf 6.0.1 library loaded
-----> Converging <default-centos65>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/vdonthin/Local Settings/Temp/default-centos65-sandbox-20170524-19136-18jx331
       Preparing dna.json
D      Creating dna.json from {:run_list=>["recipe[apache::default]"]}
       Resolving cookbook dependencies with Berkshelf 6.0.1...
D      Using Berksfile from C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/Berksfile
D      Cleaning up local sandbox in C:/Users/vdonthin/Local Settings/Temp/default-centos65-sandbox-20170524-19136-18jx331
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [no implicit conversion of nil into String] on default-centos65
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [no implicit conversion of nil into String] on default-centos65
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:24:in `load'
D      C:/opscode/chefdk/bin/kitchen:24:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [no implicit conversion of nil into String] on default-centos65
D      ----------------------
D      ------Backtrace-------
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/file_syncer.rb:66:in `join'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/file_syncer.rb:66:in `sync'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/berksfile.rb:676:in `block in vendor'
D      C:/opscode/chefdk/embedded/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/berksfile.rb:633:in `vendor'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/berkshelf.rb:66:in `block in resolve'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/berkshelf.rb:61:in `resolve'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:329:in `block in resolve_with_berkshelf'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:326:in `synchronize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:326:in `resolve_with_berkshelf'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:260:in `prepare_cookbooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:48:in `populate'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef_base.rb:130:in `create_sandbox'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef_solo.rb:46:in `create_sandbox'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:65:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [no implicit conversion of nil into String]
D      ----------------------
D      ------Backtrace-------
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/file_syncer.rb:66:in `join'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/file_syncer.rb:66:in `sync'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/berksfile.rb:676:in `block in vendor'
D      C:/opscode/chefdk/embedded/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
D      C:/Users/vdonthin/AppData/Local/chefdk/gem/ruby/2.3.0/gems/berkshelf-6.0.1/lib/berkshelf/berksfile.rb:633:in `vendor'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/berkshelf.rb:66:in `block in resolve'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/berkshelf.rb:61:in `resolve'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:329:in `block in resolve_with_berkshelf'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:326:in `synchronize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:326:in `resolve_with_berkshelf'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:260:in `prepare_cookbooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef/common_sandbox.rb:48:in `populate'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef_base.rb:130:in `create_sandbox'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/chef_solo.rb:46:in `create_sandbox'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/provisioner/base.rb:65:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:384:in `block in converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:380:in `converge_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## Kitchen Diagnose

```
---
timestamp: 2017-05-24 04:08:22 UTC
kitchen_version: 1.16.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.1.0
      api_version: 2
  provisioner:
    ChefSolo:
      class: Kitchen::Provisioner::ChefSolo
      version: 1.16.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.16.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.16.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
        network:
        - - private_network
          - ip: 192.168.33.34
        customize:
          memory: 1536
      provisioner:
        name: chef_solo
      platforms:
      - name: centos65
        driver:
          box: learningchef/centos65
          box_url: learningchef/centos65
      suites:
      - name: default
        run_list:
        - recipe[apache::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
        network:
        - - private_network
          - ip: 192.168.33.34
        customize:
          memory: 1536
      provisioner:
        name: chef_solo
      platforms:
      - name: centos65
        driver:
          box: learningchef/centos65
          box_url: learningchef/centos65
      suites:
      - name: default
        run_list:
        - recipe[apache::default]
        attributes:
instances:
  default-centos65:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      last_error: TypeError
      port: '2222'
      ssh_key: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/.kitchen/kitchen-vagrant/kitchen-enterprisechef-default-centos65/.vagrant/machines/default/virtualbox/private_key
      username: vagrant
    driver:
      boot_timeout:
      box: learningchef/centos65
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url: learningchef/centos65
      box_version:
      cache_directory: false
      cachier:
      customize:
        memory: 1536
      gui:
      kitchen_cache_directory: C:/Users/vdonthin/.kitchen/cache
      kitchen_root: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef
      linked_clone:
      log_level: :info
      name: vagrant
      network:
      - - private_network
        - ip: 192.168.33.34
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-vagrant-1.1.0/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-centos65.vagrantup.com
    provisioner:
      always_update_cookbooks: false
      attributes: {}
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_solo_path: "/bin/chef-solo"
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      deprecations_as_errors: false
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_solo
      nodes_path:
      policyfile:
      policyfile_path:
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code: []
      roles_path:
      root_path: "/tmp/kitchen"
      run_list:
      - recipe[apache::default]
      solo_rb: {}
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/test/integration
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Users/vdonthin/code/chef-repo/cookbooks/enterprisechef/test/integration
      version: busser
```
