### ISSUE TITLE
Inherit data_bags_path from run_list's recipe

### ISSUE THREAD

**Issue by manuelmazzuola** [test-kitchen/test-kitchen#1250]
Is it possible to inherit data_bags_path from the kitchen file's cookbooks included in the run_list?

I have a kitchen file to test a recipe that needs data_bags.
It works.

```
suites:
  - name: cd-base
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[cd-base]
```

I have another kitchen file that includes the recipe that I test in the kitchen file above.
This suite fails because it can't find the data bags, I have to add  `data_bags_path: "../cd-base/test/integration/data_bags"` in this kitchen file:
```
suites:
  - name: cd-tomcat
    run_list:
      - recipe[cd-base]
      - recipe[cd-tomcat]
```
