### ISSUE TITLE
get rid of provisioner, platforms, suites in custom driver from kitchen.yml

### ISSUE THREAD

**Issue by ighouri** [test-kitchen/test-kitchen#1257]
## Description
Hi,
I have a use case where I am able to create a new kitchen driver and then hook it up successfully with my kitchen.yml config. My driver's create/destroy methods does nothing but makes a call to my application that basically runs my tests. Since provisioner, platforms, suites are of no use for me in this case, I would like to get rid if them from kitchen.yml file. I just wanted to know what methods I need to override from my driver's code such that i doesn't require these phases. With current implementation i have, if I remove provisioner, platforms, suites from my kitchen.yml, it gives me an error during kitchen create command execution.
https://github.com/test-kitchen/test-kitchen/tree/master/lib
Here is my .kitchen.ym looks like:

```
---
driver:
  name: oneops
  auth_token: 'changeme'
  server_url: 'https://localhost.com'
  org_name: 'my_org'
  assembly_name: 'my_assembly'
  owner_email: 'imaad.ghouri@gmail.com'

provisioner:
  name: chef_solo

platforms:
  - name: platform_name

suites:
  - name: suit_name
```
Thanks in advance for the help.
