### ISSUE TITLE
kitchen destroy targets wrong vm

### ISSUE THREAD

**Issue by bjwschaap** [test-kitchen/test-kitchen#1264]
## Description

I have a `.kitchen.yml` with around 30 suites (=vm's). When I do a `kitchen list` I correctly see all my vms. Converging a specific suite works as intended, however when doing a `kitchen destroy` it tries to destroy another, completely unrelated vm.

I can't figure out where this unrelated box comes from, and why it is not destroying the box I specified.

## Kitchen Version

```ruby
Test Kitchen version 1.17.0
```

## Ruby Version

```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Platform Version
```
macOS Sierra 10.12.6 (16G29)
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64)
```

## Replication Case

I'm not sure on how to replicate this behaviour, although it is persistent on my set-up and 2 co-workers with a similar kitchen set-up. Any help in figuring out a reproducible testcase would be nice, I'd love to provide one.

## Kitchen Output

```
> kitchen list
...
bovaris-jamq1-bento-centos-72                Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
ci-artifactory1-bento-centos-72              Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
monitoring-nagios1-bento-centos-72           Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
bovaris-jbossas1-bento-centos-72             Vagrant  PuppetApply  Serverspec  Rsync      Converged      <None>
bovarisadapters-jbossas1-bento-centos-72     Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
master-opensmtpd1-bento-centos-72            Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
failover-opensmtpd1-bento-centos-72          Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
bovaris-apiman1-bento-centos-72              Vagrant  PuppetApply  Serverspec  Rsync      <Not Created>  <None>
...

> kitchen converge bovaris-jbossas1
-----> Starting Kitchen (v1.17.0)
-----> Creating <bovaris-jbossas1-bento-centos-72>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/centos-7.2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/centos-7.2' is up to date...
       ==> default: Setting the name of the VM: bovaris-jbossas1-bento-centos-72_default_1503909451130_27834
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Remote connection disconnect. Retrying...
...
...
       Notice: Applied catalog in 401.69 seconds
       Finished converging <bovaris-jbossas1-bento-centos-72> (7m47.86s).
-----> Kitchen is finished. (9m5.26s)

> kitchen login bovaris-jbossas1
[vagrant@bovaris-jbossas-01l ~]$ exit

> kitchen destroy -f bovaris-jbossas1
-----> Starting Kitchen (v1.17.0)
-----> Destroying <ftp-ftp1-bento-centos-72>...
       Finished destroying <ftp-ftp1-bento-centos-72> (0m0.00s).
-----> Kitchen is finished. (0m0.21s)
```
Why is kitchen trying to destroy the `ftp-ftp1` box?!

## Kitchen Diagnose

```yaml
---
timestamp: 2017-08-28 10:05:09 UTC
kitchen_version: 1.17.0
instances:
  bovaris-jbossas1-bento-centos-72:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: converge
      last_error:
      port: '2222'
      ssh_key: "/Users/bjwschaap/workspace/devbox/.kitchen/kitchen-vagrant/bovaris-jbossas1-bento-centos-72/.vagrant/machines/default/virtualbox/private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: bento/centos-7.2
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize:
        cableconnected1: 'on'
        memory: 1024
      gui:
      kitchen_cache_directory: "/Users/bjwschaap/.kitchen/cache"
      kitchen_root: "/Users/bjwschaap/workspace/devbox"
      linked_clone:
      log_level: :info
      name: vagrant
      network:
      - - private_network
        - ip: 192.168.50.211
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - "/Users/bjwschaap/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/Users/bjwschaap/workspace/devbox/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/Users/bjwschaap/.rvm/gems/ruby-2.3.1/gems/kitchen-vagrant-1.2.1/templates/Vagrantfile.erb"
      vagrantfiles:
      - "/Users/bjwschaap/workspace/devbox/data/Vagrantfile-extra-sata-disk1.rb"
      vm_hostname: bovaris-jbossas-01l.kitchen
    provisioner:
      chef_bootstrap_url: https://www.getchef.com/chef/install.sh
      command_prefix:
      custom_facts:
        tenant:
        role: jbossas
        application: bovaris
        provisioner_name: puppet_apply
      custom_install_command: sudo yum install -y rsync
      custom_pre_apply_command:
      custom_pre_install_command:
      facter_file:
      facter_version:
      facterlib:
      files_path: files
      fileserver_config_path:
      ftp_proxy:
      hiera_config_path: hiera.yaml
      hiera_data_path: "../hiera"
      hiera_data_remote_path:
      hiera_deep_merge: true
      hiera_eyaml: false
      hiera_eyaml_gpg: false
      hiera_eyaml_gpg_pubring: false
      hiera_eyaml_gpg_recipients: false
      hiera_eyaml_gpg_remote_path: "/home/vagrant/.gnupg"
      hiera_eyaml_gpg_secring: false
      hiera_eyaml_key_path:
      hiera_eyaml_key_remote_path: "/etc/puppet/secure/keys"
      hiera_package: hiera-puppet
      hiera_version:
      hiera_writer_files:
      http_proxy:
      https_proxy:
      ignore_spec_fixtures: false
      ignored_paths_from_root:
      - spec
      install_custom_facts: true
      install_hiera: false
      kitchen_root: "/Users/bjwschaap/workspace/devbox"
      librarian_puppet_ssl_file:
      manifest: site.pp
      manifests_path: manifests
      max_retries: 1
      metadata_json_path:
      modulefile_path:
      modules_path: "../environments/lab/modules"
      name: puppet_apply
      no_proxy:
      platform: bento/centos-7.2
      puppet_apply_command:
      puppet_apt_collections_repo: http://apt.puppetlabs.com/puppet5-release-wheezy.deb
      puppet_apt_repo: http://apt.puppetlabs.com/puppetlabs-release-precise.deb
      puppet_coll_remote_path: "/opt/puppetlabs"
      puppet_config_path:
      puppet_debug: false
      puppet_detailed_exitcodes:
      puppet_enc:
      puppet_environment: lab
      puppet_environment_config_path:
      puppet_environment_hiera_config_path: "/Users/bjwschaap/workspace/devbox/hiera.yaml"
      puppet_environment_remote_hieradata_path: hieradata
      puppet_environment_remote_manifests_path: manifests
      puppet_environment_remote_modules_path: modules
      puppet_environmentpath_remote_path: "/etc/puppetlabs/puppet"
      puppet_future_parser: false
      puppet_git_init:
      puppet_git_pr:
      puppet_logdest:
      puppet_no_sudo: false
      puppet_noop: false
      puppet_omnibus_url: https://raw.githubusercontent.com/petems/puppet-install-shell/master/install_puppet_5_agent.sh
      puppet_show_diff: false
      puppet_verbose: true
      puppet_version: 1.8.3-1.el7
      puppet_whitelist_exit_code:
      puppet_yum_collections_repo: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      puppet_yum_repo: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
      puppetfile_path: "../environments/lab/Puppetfile"
      remove_puppet_repo: false
      require_chef_for_busser: false
      require_puppet_collections: true
      require_puppet_omnibus: false
      require_puppet_repo: true
      resolve_with_librarian_puppet: false
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      spec_files_path:
      spec_files_remote_path: "/etc/puppet/spec"
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/bjwschaap/workspace/devbox/test/integration"
      update_package_repos: true
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/bjwschaap/workspace/devbox"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: rsync
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/Users/bjwschaap/devbox/test/integration"
      username: root
    verifier:
      additional_install_command:
      additional_serverspec_command:
      bundler_path:
      chef_omnibus_root: "/opt/chef"
      color: true
      command_prefix:
      custom_install_command:
      custom_serverspec_command:
      default_path: "/tmp/kitchen"
      default_pattern: false
      env_vars: {}
      extra_flags:
      format: documentation
      ftp_proxy:
      gemfile: ServerspecGemfile
      http_proxy:
      https_proxy:
      kitchen_root: "/Users/bjwschaap/workspace/devbox"
      live_stream: !ruby/object:IO {}
      log_level: :info
      name: serverspec
      patterns: []
      remote_exec: true
      remove_default_path: false
      require_runner: false
      root_path: "/tmp/verifier"
      rspec_path:
      runner_url: https://raw.githubusercontent.com/neillturner/serverspec-runners/master/ansiblespec_runner.rb
      serverspec_command:
      shellout_opts: {}
      sleep: 0
      sudo: true
      sudo_command: sudo -E -H
      suite_name: bovaris-jbossas1
      test_base_path: "/Users/bjwschaap/workspace/devbox/test/integration"
      test_serverspec_installed: true
```
