### ISSUE TITLE
Support for ENV varialbles in .kitchen.yml

### ISSUE THREAD

**Issue by es1o** [test-kitchen/test-kitchen#1278]
## Description

I would like to support environment variables in .kitchen.yml file.

I work in company that has internal http and https proxy with authentication. I don't want to have my username and password in .kitchen.yml file. I would like kitchen to use ENV variables because I can easilly pass that variables using Jenkins secrets.

I would like something like this:
```
---
driver:
  name: docker
  use_sudo: false
  http_proxy: ENV['http_proxy']
  https_proxy: ENV['https_proxy']
```

No I have that code:
```
---
driver:
  name: docker
  use_sudo: false
  http_proxy: http://user:mysupersecretpassword@mycompanyproxy:1234
  https_proxy: https://user:mysupersecretpassword@mycompanyproxy:1234
```

Does kitchen support that feature?

## Kitchen Version

1.17.0

## Ruby Version

ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

## Platform Version

Fedora release 26 (Twenty Six)

**Comment by MarkGibbons** [comment]
We use something like this at the beginning of our .kitchen.yml files to access environment variables.

<% proxy_vars = {} %>
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<%   if ENV.key?(envvar) %>
<%     proxy_vars[envvar] = ENV[envvar] %>
<%   end %>
<% end %>
---
driver:
  name: vagrant

<% if proxy_vars.size > 0 %>
driver_config:
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
  <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>

<% end %>

**Comment by coderanger** [comment]
That's a bit overkill as Erb stuffs goes, but this is also generally not needed. All drivers should already use those env vars if they are set. You can do other thing like this though

```yaml
driver:
  name: whatever
  something: <%= ENV['asdf'] %>
```
