### ISSUE TITLE
Cookbook is not copying to instance

### ISSUE THREAD

**Issue by asif-alam** [test-kitchen/test-kitchen#1299]
## Description

In temp directory sandbox folder "..Local/Temp/default-windows-2012r2-sandbox-20171012-7276" has the files but when it creating the zip file to transfer to instance, it is missing the cookbook files

no cookbook in ...\kitchen\cookbooks in the instance

## Kitchen Version

Test Kitchen version 1.17.0

## ChefDK Version

Chef Development Kit Version: 2.2.1
chef-client version: 13.3.42
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.35.1

# Kitchen yml

```
driver:
  name: ec2
  aws_ssh_key_id: xx
  region: xx
  availability_zone: b
  subnet_id: subnet-485b9020
  instance_type: m1.small
  image_id: ami-8a9a78e8
  security_group_ids: ["xx"]
  associate_public_ip: true
  interface: dns
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /root/.ssh/asif-aws-ec2-key.pem

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

# Debug info

```
I, [2017-10-12T18:13:09.051255 #7276]  INFO -- default-windows-2012r2: Transferring files to <default-windows-2012r2>
D, [2017-10-12T18:13:09.052145 #7276] DEBUG -- default-windows-2012r2: creating hash for directory $env:TEMP\kitchen
D, [2017-10-12T18:13:09.054051 #7276] DEBUG -- default-windows-2012r2: Populating files
D, [2017-10-12T18:13:09.054901 #7276] DEBUG -- default-windows-2012r2: === All files added.
D, [2017-10-12T18:13:09.060549 #7276] DEBUG -- default-windows-2012r2: creating hash for file $env:TEMP\kitchen
D, [2017-10-12T18:13:09.061867 #7276] DEBUG -- default-windows-2012r2: creating hash for directory $env:TEMP\kitchen
D, [2017-10-12T18:13:09.064377 #7276] DEBUG -- default-windows-2012r2: Populating files
D, [2017-10-12T18:13:09.065879 #7276] DEBUG -- default-windows-2012r2: +++ Adding C:/Users/Asif.Alam/AppData/Local/Temp/default-windows-2012r2-sandbox-20171012-7276-1pflgw7/cookbooks/learn_chef_iis/README.md
D, [2017-10-12T18:13:09.067894 #7276] DEBUG -- default-windows-2012r2: +++ Adding C:/Users/Asif.Alam/AppData/Local/Temp/default-windows-2012r2-sandbox-20171012-7276-1pflgw7/cookbooks/learn_chef_iis/metadata.json
D, [2017-10-12T18:13:09.069963 #7276] DEBUG -- default-windows-2012r2: +++ Adding C:/Users/Asif.Alam/AppData/Local/Temp/default-windows-2012r2-sandbox-20171012-7276-1pflgw7/cookbooks/learn_chef_iis/recipes/default.rb
D, [2017-10-12T18:13:09.073693 #7276] DEBUG -- default-windows-2012r2: +++ Adding C:/Users/Asif.Alam/AppData/Local/Temp/default-windows-2012r2-sandbox-20171012-7276-1pflgw7/cookbooks/learn_chef_iis/templates/Default.htm.erb
D, [2017-10-12T18:13:09.084380 #7276] DEBUG -- default-windows-2012r2: === All files added.
D, [2017-10-12T18:13:09.088892 #7276] DEBUG -- default-windows-2012r2: creating hash for file $env:TEMP\kitchen
D, [2017-10-12T18:13:09.089901 #7276] DEBUG -- default-windows-2012r2: creating hash for file $env:TEMP\kitchen

-----

D, [2017-10-12T18:13:10.491015 #7276] DEBUG -- default-windows-2012r2: Finished uploading C:/Users/ASIF~1.ALA/AppData/Local/Temp/tmpzip-20171012-7276-1ipif9d.zip to $env:TEMP\winrm-upload\tmpzip-d8afb3d7adc3f1ca008342125c3b7d34.zip (2.788 KB over 1 chunks) in (0m0.73s)
D, [2017-10-12T18:13:10.493052 #7276] DEBUG -- default-windows-2012r2: File $env:TEMP\kitchen/dna.json is up to date, skipping
D, [2017-10-12T18:13:10.494026 #7276] DEBUG -- default-windows-2012r2: File $env:TEMP\kitchen/validation.pem is up to date, skipping
D, [2017-10-12T18:13:10.495426 #7276] DEBUG -- default-windows-2012r2: Running extract_files.ps1

-----
D, [2017-10-12T18:13:11.399798 #7276] DEBUG -- default-windows-2012r2: Parsing CSV Response
D, [2017-10-12T18:13:11.400682 #7276] DEBUG -- default-windows-2012r2: "src_md5","tmpzip","dst"
"d8afb3d7adc3f1ca008342125c3b7d34","C:\Users\ADMINI~1\AppData\Local\Temp\winrm-upload\tmpzip-d8afb3d7adc3f1ca008342125c3b7d34.zip","C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cookbooks"
"76cdb2bad9582d23c1f6f4d868218d6c","C:\Users\ADMINI~1\AppData\Local\Temp\winrm-upload\tmpzip-76cdb2bad9582d23c1f6f4d868218d6c.zip","C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache"
```
