### ISSUE TITLE
Slashes in platform name and using Windows

### ISSUE THREAD

**Issue by jerryaldrichiii** [test-kitchen/test-kitchen#1314]
## Description

When setting:

```
platform:
  - name: chef/windows-server-2012r2-standard
```

Kitchen fails to create the machine with the following error:

```
STDERR: Renaming the Windows guest failed. Most often this is because you've
specified a FQDN instead of just a host name.
                                                                                                                                                                                                                                                                                                                                                                                                                                       
Ensure the new guest name is properly formatted. Standard names may  
contain letters (a-z, A-Z), numbers (0-9), and hypens (-), but no
spaces or periods (.). The name may not consist entirely of digits. 
```

I suspect this is due to the slash in the platform name. The workaround it to define the platform like so:
```
platforms:
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
```

## Kitchen Version
```
Test Kitchen version 1.17.0
```

## ChefDK Version
```
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```
## Platform Version

Arch Linux

## Replication Case

Create a `.kitchen.yml` and specify the following for platform (note `chef/` is private so you will need to substitute it with another Vagrant box identifier likely):

```
platform:
  - name: chef/windows-server-2012r2-standard
```

## Kitchen Output

https://gist.github.com/jerryaldrichiii/3bacc8c8b286c06ea4fe6dff1557a8fa

## Kitchen Diagnose

https://gist.github.com/jerryaldrichiii/395b170a1c838f139ad7d5d28b272740

**Comment by coderanger** [comment]
The workaround isn't really a workaround, that is the correct configuration.

**Comment by jerryaldrichiii** [comment]
Fair point, but as a user I would like a better warning/error or the behavior modified for that configuration to work.

Workaround was poor word choice :smile:

**Comment by tas50** [comment]
@coderanger The first config is in fact wrong, but underlying bug report is still valid. We should sanitize the hostnames when we create names based on the config

**Comment by coderanger** [comment]
Yeah, we should have either cleaned it for you or errored much earlier (if we want to globally disallow `/` in platform names, which I would be fine with)

**Comment by jerryaldrichiii** [comment]
Interesting, this may be another issue.

Changing:
```
platforms:
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
```

To:
```
platforms:
  - name: foo
    driver_config:
      box: chef/windows-server-2012r2-standard
```

Fails with the same error as above...but the following works:

```
platforms:
  - name: winfoo
    driver_config:
      box: chef/windows-server-2012r2-standard
```
