### ISSUE TITLE
Omnibus fails to install on ubuntu-16.04 due to permissions error

### ISSUE THREAD

**Issue by ikari7789** [test-kitchen/test-kitchen#1330]
## Description

Sorry if this isn't the correct place to report this, but since Kitchen is generating the provisioning for Vagrant, I thought this would be a good place to start. This may be a provider issue, but I cannot get just the basic default template to install Chef via omnibus on `bento/ubuntu-16.04`. Using `parallels` as a default provider. I continually get PERMISSION DENIED errors when it attempts to install via the omnibus installer. `bento/centos-7` works as expected. If I try running the same command after it fails through `kitchen login`, it seems to install as expected.  Maybe it's an issue with the Vagrant box. I'm not sure.

## Kitchen Version

```ruby
$ chef exec kitchen --version
Test Kitchen version 1.19.2
```

## ChefDK Version

```ruby
$ chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

```ruby
$ chef exec ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
```

## Platform Version

macOS High Sierra 10.13.22

## Replication Case

Required: chefdk, vagrant, parallels

```shell
chef create cookbook example_cookbook
cd ./example_cookbook
VAGRANT_DEFAULT_PROVIDER="parallels"
kitchen verify
```

## Kitchen Output

```ruby
$ chef exec kitchen verify default-ubuntu-1604
-----> Starting Kitchen (v1.19.2)
-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'parallels' provider...
       ==> default: Registering VM image from the base box 'bento/ubuntu-16.04'...
       ==> default: Cloning new virtual machine...
==> default: Unregistering the box VM image...
       ==> default: Setting the default configuration for VM...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       ==> default: Setting the name of the VM: default-ubuntu-1604_default_1513060674086_6344
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 0: shared
       ==> default: Clearing any previously set network interfaces...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 10.211.55.85:22
           default: SSH username: vagrant
           default: SSH auth method: private key
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for Parallels Tools installed on the VM...
       ==> default: Parallels Tools installed on this VM are outdated! In most cases
       ==> default: this is fine but in rare cases it can cause things such as shared
       ==> default: folders to not work properly. If you see shared folder errors,
       ==> default: please update Parallels Tools within the virtual machine and
       ==> default: reload your VM.
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /YYY/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1604> created.
       Finished creating <default-ubuntu-1604> (0m49.13s).
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 16.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=16.04&m=x86_64
         to file /tmp/install.sh.1880/metadata.txt
       trying wget...
       sha1	968d6f567dc45ab4cd8d8f94a5e43d781a1d5ba1
       sha256	c523feb2494b407d71c56261035a58b6897ec6312f917477ef0b3fc4e27c072d
       url	https://packages.chef.io/files/stable/chef/13.6.4/ubuntu/16.04/chef_13.6.4-1_amd64.deb
       version	13.6.4
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/13.6.4/ubuntu/16.04/chef_13.6.4-1_amd64.deb
         to file /tmp/omnibus/cache/chef_13.6.4-1_amd64.deb
       trying wget...
       trying curl...
       /tmp/install.sh: 139: /tmp/install.sh: cannot create /tmp/omnibus/cache/chef_13.6.4-1_amd64.deb: Permission denied
       grep: /tmp/install.sh.1880/stderr: No such file or directory
       trying perl...
       /tmp/install.sh: 169: /tmp/install.sh: cannot create /tmp/omnibus/cache/chef_13.6.4-1_amd64.deb: Permission denied
       grep: /tmp/install.sh.1880/stderr: No such file or directory
       trying python...
       /tmp/install.sh: 190: /tmp/install.sh: cannot create /tmp/omnibus/cache/chef_13.6.4-1_amd64.deb: Permission denied
       grep: /tmp/install.sh.1880/stderr: No such file or directory
       Unable to retrieve a valid package!
       Version:

       Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
       More Chef support resources can be found at https://www.chef.io/support

       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.

       Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=16.04&m=x86_64
       Download URL: https://packages.chef.io/files/stable/chef/13.6.4/ubuntu/16.04/chef_13.6.4-1_amd64.deb

       DEBUG OUTPUT FOLLOWS:

       STDERR from wget:

       /tmp/omnibus/cache/chef_13.6.4-1_amd64.deb: Permission denied

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Kitchen Diagnose

```yaml
$ kitchen diagnose --all
---
timestamp: 2017-12-12 06:39:27 UTC
kitchen_version: 1.19.2
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.2.1
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.19.2
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.19.2
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.20.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/XXX/example_cookbook/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
      - name: centos-7
      suites:
      - name: default
        run_list:
        - recipe[example_cookbook::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
      - name: centos-7
      suites:
      - name: default
        run_list:
        - recipe[example_cookbook::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
instances:
  default-ubuntu-1604:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 10.211.55.85
      last_action: create
      last_error: Kitchen::ActionFailed
      port: '22'
      ssh_key: "/XXX/example_cookbook/.kitchen/kitchen-vagrant/default-ubuntu-1604/.vagrant/machines/default/parallels/private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: bento/ubuntu-16.04
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      gui:
      kitchen_cache_directory: "/YYY/.kitchen/cache"
      kitchen_root: "/XXX/example_cookbook"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: parallels
      provision: false
      ssh: {}
      synced_folders:
      - - "/YYY/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/XXX/example_cookbook/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-ubuntu-1604.vagrantup.com
    provisioner:
      always_update_cookbooks: true
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      debug:
      deprecations_as_errors: false
      download_url:
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      install_strategy: once
      json_attributes: true
      kitchen_root: "/XXX/example_cookbook"
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[example_cookbook::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/XXX/example_cookbook/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/XXX/example_cookbook"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/XXX/example_cookbook/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: "/XXX/example_cookbook"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/XXX/example_cookbook/test/integration"
  default-centos-7:
    platform:
      os_type: unix
      shell_type: bourne
    state_file: {}
    driver:
      boot_timeout:
      box: bento/centos-7
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      gui:
      kitchen_cache_directory: "/YYY/.kitchen/cache"
      kitchen_root: "/XXX/example_cookbook"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: parallels
      provision: false
      ssh: {}
      synced_folders:
      - - "/YYY/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/XXX/example_cookbook/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-centos-7.vagrantup.com
    provisioner:
      always_update_cookbooks: true
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      debug:
      deprecations_as_errors: false
      download_url:
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      install_strategy: once
      json_attributes: true
      kitchen_root: "/XXX/example_cookbook"
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[example_cookbook::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/XXX/example_cookbook/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/XXX/example_cookbook"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key:
      test_base_path: "/XXX/example_cookbook/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: "/XXX/example_cookbook"
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/XXX/example_cookbook/test/integration"
```
