### ISSUE TITLE
PR #1328 broken the ability to specify symbols in kitchen configs

### ISSUE THREAD

**Issue by tas50** [test-kitchen/test-kitchen#1345]
With #1328 we switched from safe_yaml to the build in safe yaml functionality in Ruby. Unfortunately this breaks our ability to specify symbols in a kitchen config. If you're passing values into the client.rb such as log_level you need a symbol so this is pretty problematic.

### Given:
```yaml
provisioner:
  name: chef_solo
  retry_on_exit_code:
    - 213
  max_retries: 1
  wait_for_retry: 1
  client_rb:
    exit_status: :enabled
    client_fork: false
    log_level: :debug
```

### Resulting Error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Error parsing /Users/tsmith/dev/chef-cookbooks/chef_client_updater/.kitchen.yml as YAML.
Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
