### ISSUE TITLE
Interpolate current cookbook name in the run_list

### ISSUE THREAD

**Issue by scalp42** [test-kitchen/test-kitchen#1362]
## Description

Is there any way to interpolate the current cookbook name in `.kitchen.yml` like `cookbook_name` method in Chef recipe DSL?

## Kitchen Version

```ruby
Test Kitchen version 1.19.2 
```

## ChefDK Version

```ruby
Chef Development Kit Version: 2.4.17
```

## Platform Version

MacOS

## Replication Case

```yaml
suites:
  - name: default
    run_list:
      # - recipe[<%= File.basename(File.dirname(__FILE__)) %>::default]
      - recipe[<%= "#{cookbook_name}" %>::default]
    attributes:
```

Any pointers?
