### ISSUE TITLE
New .kitchen.yml syntax?

### ISSUE THREAD

**Issue by sethvargo** [test-kitchen/test-kitchen#138]
Since we are now using `vagrant-omnibus`, can we switch to a more "matrix-like" configuration:

``` yaml
platforms:
  - ubuntu-10.04
  - ubuntu-12.04
  - centos-5.8
  - centos-6.4
chef:
  - 0.10.10
  - 10.24
  - 11.04
  - master
suite:
  package:
    run_list: 
      - recipe[my_cookbook::package]
  source:
    run_list:
      - recipe[my_cookbook::source]
```

This would actually create 32 builds for truer test suite.
