### ISSUE TITLE
1.21.0 cannot install chef with new provisioner options

### ISSUE THREAD

**Issue by juicemia** [test-kitchen/test-kitchen#1402]
## Description

Kitchen is failing to converge all instances. Seems like there's an issue with `sudo`. This *may* be an issue with our setup (we're using the OpenStack provider). However, we've found that going back to a previous version of Kitchen works. We figured we should give a heads up just in case this is a symptom of a regression.

## Kitchen Version

```
Test Kitchen version 1.21.0
```

Going back to version `1.20` works.

## Ruby Version

```
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
```

## Platform Version

Ubuntu Linux 14.04

## Replication Case

To be honest, our setup is a bit customized. We're using the OpenStack provider.

## Kitchen Output

```
-----> Converging <zookeeper-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       sudo: unable to resolve host hugot-local-snmljbie
       bash: line 1: /tmp/kitchen/chef-installer.sh: Permission denied
       chmod: cannot access ‘/tmp/kitchen/chef-installer.sh’: No such file or directory
       sudo: unable to resolve host hugot-local-snmljbie
       sudo: /tmp/kitchen/chef-installer.sh: command not found
```

When running with version `1.20`, we see the following:

```
Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.2...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       sudo: unable to resolve host ci-228b5ee5c-ipwrqcyv
       sudo: unable to resolve host ci-228b5ee5c-ipwrqcyv
       ubuntu 14.04 x86_64
       Getting information for chef stable 12.2.1 for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=12.2.1&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.1335/metadata.txt
       trying wget...

# at this point, the chef installer is already running
```

**Comment by cheeseplus** [comment]
Can you gist or snippet the `.kitchen.yml`? That and/or `kitchen diagnose --all` output is going to be helpful.

**Comment by tristanmorgan** [comment]
I am having the same issue, on MacOS. On both docker and ec2 driver. Yaml sample provided.
```yaml
---
driver:
  name: ec2
  instance_type: t2.micro
  user_data: files/default/user_data.txt
  skip_cost_warning: true

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 13.8.5

verifier:
  name: inspec
  backend_cache: true

platforms:
  - name: amazonlinux-2017.09
    transport:
      username: ec2-user
    driver:
      image_search:
        name: "amzn-ami-hvm-2017.09.?.????????-x86_64-gp2"
        owner-alias: "amazon"
        virtualization-type: hvm
        state: available
```
```-----> Converging <default-amazonlinux-20>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.2...
       Removing non-cookbook files before transfer
       Preparing solo.rb
       bash: line 1: /tmp/kitchen/chef-installer.sh: Permission denied
       chmod: cannot access ‘/tmp/kitchen/chef-installer.sh’: No such file or directory
       sudo: /tmp/kitchen/chef-installer.sh: command not found
```
