### ISSUE TITLE
cant run kitchen create running on VM

### ISSUE THREAD

**Issue by network20172** [test-kitchen/test-kitchen#1405]
## Description
I am using test kitchen installed on free Virtual enviornment . every thing is fine till kitchen install n all. but after kitchen  test command it says

```
 kitchen test
-----> Starting Kitchen (v1.4.0)
-----> Cleaning up any prior instances of <default-ubuntu-1604>
-----> Destroying <default-ubuntu-1604>...
       Vagrant instance <default-ubuntu-1604> destroyed.
       Finished destroying <default-ubuntu-1604> (0m2.90s).
-----> Testing <default-ubuntu-1604>
-----> Creating <default-ubuntu-1604>...
       [default] Forcing shutdown of VM...[default] Destroying VM and associated                                                                                                  drives...Bringing machine 'default' up with 'virtualbox' provider...[default] I                                                                                                 [default] Matching MAC address for NAT networking...[default] Setting the name o                                                                                                 f the VM...[default] Clearing any previously set forwarded ports...[default] Cle                                                                                                 aring any previously set network interfaces...[default] Preparing network interf                                                                                                 aces based on configuration...[default] Forwarding ports...[default] -- 22 => 22                                                                                                 22 (adapter 1)[default] Booting VM...[default] Waiting for machine to boot. This                                                                                                  may take a few minutes...Timed out while waiting for the machine to boot. This                                                                                                  means that
       Vagrant was unable to communicate with the guest machine within
       the configured ("config.vm.boot_timeout" value) time period. This can
       mean a number of things.

       If you're using a custom box, make sure that networking is properly
       working and you're able to connect to the machine. It is a common
       problem that networking isn't setup properly in these boxes.
       Verify that authentication configurations are also setup properly,
       as well.

       If the box appears to be booting properly, you may want to increase
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit wit                                                                                                 h [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'bento/ubuntu-16.04'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Please help!!!

Briefly describe the issue!!!

I am using chef on vm and able to provision nodes and server on vms but now kitchen is giving me error .what could be the issue as I dont understand why it is not creating instance for me as I have more than 100 gb space avalaible.

## Versions

```
Chef Development Kit Version: 0.5.1
chef-client version: ERROR
berks version: ERROR
kitchen version: 1.4.0
```

## Platform Version

ubuntu1404

## Kitchen Output

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit wit                                                                                                 h [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'bento/ubuntu-16.04'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

KITCHEN Daigonse

```
timestamp: 2018-04-19 13:05:56 UTC
kitchen_version: 1.4.0
instances:
  default-ubuntu-1604:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      port: '2222'
      ssh_key: "/root/.vagrant.d/insecure_private_key"
      username: vagrant
    driver:
      boot_timeout:
      box: bento/ubuntu-16.04
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      gui:
      kitchen_cache_directory: "/root/.kitchen/cache"
      kitchen_root: "/root/chef-repo/git_cookbook"
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - "/root/.kitchen/cache"
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: "/root/chef-repo/git_cookbook/test/integration"
      vagrant_binary: vagrant
      vagrantfile_erb: "/root/.chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-1.3.1/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: default-ubuntu-1604.vagrantup.com
    provisioner:
      attributes: {}
      chef_client_path: "/opt/chef/bin/chef-client"
      chef_metadata_url:
      chef_omnibus_install_options:
      chef_omnibus_root: "/opt/chef"
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: "/root/chef-repo/git_cookbook"
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      require_chef_omnibus: true
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/opt/chef/embedded/bin"
      run_list:
      - recipe[git_cookbook::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/root/chef-repo/git_cookbook/test/integration"
    transport:
      compression: zlib
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/root/chef-repo/git_cookbook"
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: "/root/chef-repo/git_cookbook/test/integration"
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: "/root/chef-repo/git_cookbook"
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: "/root/chef-repo/git_cookbook/test/integration"
      version: busser
```
