### ISSUE TITLE
Docs for Silencing Chef Deprecation Warnings

### ISSUE THREAD

**Issue by cheeseplus** [test-kitchen/test-kitchen#1452]
## Description

Chef 14.3+ can silence deprecation warnings as per https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#silencing-deprecation-warnings

```
provisioner:
  name: chef_solo
  solo_rb:
    treat_deprecation_warnings_as_errors: true
    silence_deprecation_warnings:
    - deploy_resource
    - chef-23
    - recipes/install.rb:22
```
