### ISSUE TITLE
Docs for Reboot

### ISSUE THREAD

**Issue by cheeseplus** [test-kitchen/test-kitchen#1454]
## Description

Explain all the fun idiosyncrasies of rebooting between Windows and *nix operating systems

```
provisioner:
  name: chef_zero
  max_retries: 3 # tweak in conjunction with below
  wait_for_retry: 90 # tweak based on machine shutdown speed
  retry_on_exit_code:
    - 35 # chef-client's reboot scheduled exit status
  client_rb:
    exit_status: :enabled # default in 13+
    client_fork: false # don't fork so we get true exit code
```

`exit_status` in the client.rb is only needed for 12.x clients.  Chef 13 just has the behavior by default.

On Linux, when `client_fork` is enabled, the true exit code does not get passed through.  This is one problem that can be addressed, the other is that the `shutdown` command on linux is blocking and not fired async, so chef blocks until the shutdown command returns and the shutdown has started (https://github.com/chef/chef/issues/5026).

`wait_for_retry` is necessary so that kitchen doesn't try to reconnect before the system reboots (or at least before winrm or ssh stop taking connections).  This is the most likely thing to need tweaking depending on the driver and changes being made to a machine which impact how quickly a specific machine shuts down and reboots.

Now that Chef 13 uses the default exit code behavior, we could probably bake the `retry_on_exit_code` into the chef provisioner.

Migrated from https://github.com/test-kitchen/kitchen-docs/issues/65
