### ISSUE TITLE
Docs for Setting Environment for Chef provisioner

### ISSUE THREAD

**Issue by cheeseplus** [test-kitchen/test-kitchen#1455]
## Description

```
provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: kitchen
```

For posterity we should note `solo_rb` vs `client_rb` even though nobody should need it at this juncture. Also note files in `environments_path` must be JSON

Migrated from https://github.com/test-kitchen/kitchen-docs/issues/73
