### ISSUE TITLE
kitchen login, password prompt

### ISSUE THREAD

**Issue by guskovd** [test-kitchen/test-kitchen#1461]
It seems that kitchen login does not use the password option
```bash
D      [local command] BEGIN (docker >> /dev/null 2>&1)
D      [local command] END (0m0.04s)
D      Login command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=VERBOSE -p 22 vagrant@172.17.0.2 (Options: {})
Warning: Permanently added '172.17.0.2' (ECDSA) to the list of known hosts.
Password:
```

kitchen converge - OK
```bash
 --> kitchen converge  default-macos -l debug
-----> Starting Kitchen (v1.23.2)
D      [local command] BEGIN (docker >> /dev/null 2>&1)
D      [local command] END (0m0.05s)
-----> Converging <default-macos>...
       Preparing files for transfer
D      Creating local sandbox in /tmp/default-macos-sandbox-20180910-22271-1hw4v6s
       Preparing data
D      Using data from /home/guskov/prog/openstack-dev/states/qemu/data
       Preparing script
       No provisioner script file specified, skipping
       Transferring files to <default-macos>
D      TIMING: scp async upload (Kitchen::Transport::Ssh)
D      [SSH] opening connection to vagrant@172.17.0.2<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :verify_host
_key=>false}>                                                                                                                                                                                                                                
D      TIMING: scp async upload (Kitchen::Transport::Ssh) took (0m0.28s)
D      Transfer complete
D      Attempting to execute command - try 1 of 1.
D      [SSH] vagrant@172.17.0.2<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :verify_host_key=>false, :logger=>
#<Logger:0x0000000002bf16a0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000002bf1628 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000002bf15d8 @shift_period_suffix=nil, @shift_size=nil
, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000002bf1588>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000000002bf1560>, :user=>"vagrant"}> (sh -c '                  
TEST_KITCHEN="1"; export TEST_KITCHEN
/tmp/kitchen/data/provision.sh
')
       hello
       Downloading files from <default-macos>
D      Download complete
D      Cleaning up local sandbox in /tmp/default-macos-sandbox-20180910-22271-1hw4v6s
       Finished converging <default-macos> (0m0.34s).
D      [SSH] shutting previous connection vagrant@172.17.0.2<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"vagrant", :veri
fy_host_key=>false, :logger=>#<Logger:0x0000000002bf16a0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000002bf1628 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000002bf15d8 @shift_perio
d_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000002bf1588>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000000002bf1560>, :user=>"vagrant"}
>                                                                                                                                                                                                                                            
-----> Kitchen is finished. (0m0.43s)
```

**Comment by guskovd** [comment]
kitchen diagnose default-macos 
```yaml
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/home/guskov/prog/openstack-dev/states/qemu"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: vagrant
      port: 22
      ssh_gateway: 
      ssh_gateway_port: 22
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: "/home/guskov/prog/openstack-dev/states/qemu/test/integration"
      username: vagrant

```
