### ISSUE TITLE
Problem to set memeory in hyperv

### ISSUE THREAD

**Issue by joydi** [test-kitchen/test-kitchen#1472]
## Description

Hi folks,

i just startet to use test-kitchen and i am hanging on a problem where i can't find any help.
I just want to add more memory to the hyperv vm but it keeps getting 2GB ?
Can u help me please ?

Thank you all in advance

Here is my .kitchen.yml
```
---
driver:
  name: vagrant
  provider: hyperv
  network:
  - ["public_network", bridge: "Extern"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: Windows10
    driver_config:
      box: StefanScherer/windows_10
      memory_startup_bytes: 4GB #here i want to set the memory 
  


suites:
  - name: default
    run_list:
      - recipe[w::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

## Kitchen Version

Test Kitchen version 1.23.2 

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
```

## ChefDK Version

Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112

```ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
```

## Ruby Version

ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]

```ruby
# Copy-paste your results here
```

## Platform Version

Windows 10 Professional

**Comment by cheeseplus** [comment]
What you're looking for is enumerated between https://github.com/test-kitchen/kitchen-vagrant#-customize and https://www.vagrantup.com/docs/hyperv/configuration.html.

```
platforms:
  - name: Windows10
    driver:
      box: StefanScherer/windows_10
      customize: 
        memory: 4096
```
