### ISSUE TITLE
Trying use ruby yaml.load_file in kitchen.yml

### ISSUE THREAD

**Issue by stefanmonkey** [test-kitchen/test-kitchen#1508]
## Description

Trying to load other yaml file with custom variables into kitchen.yml

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.24.0
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.
```bash
Darwin MacMini_Drei 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

## Replication Case
Using the following `.kitchen.yml`
```yaml
<%
repos = "mirrors-yl.bre.dz11.com"

require 'yaml'
def render_yaml(file_path)
  var = YAML.load_file(file_path)
  return var
end
%>
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: http://<%= repos %>/bootstrap-salt.sh
  salt_bootstrap_options: -R <%= repos %>/saltstack -r -l
  bootstrap_url: http://<%= repos %>/bootstrap-kitchen.sh
  formula: prometheus
  grains:
    environment: unp
  state_top:
    base:
      "*":
        - prometheus
  pillars:
    top.sls:
      base:
        "*":
          - prometheus
  pillars-from-files:
    prometheus.sls: pillar.example

platforms:
  - name: ubuntu-16.04
    provisioner:
      salt_apt_repo: 'http://<%= repos %>/saltstack/apt/ubuntu/16.04/amd64'
      init_environment: |
        sudo sed -i "s/archive.ubuntu.com/mirrors.163.com/g" /etc/apt/sources.list
        sudo sed -i "s/security.ubuntu.com/mirrors.163.com/g" /etc/apt/sources.list
      install_after_init_environment: true
  - name: centos-7.5
    provisioner:
      salt_yum_repo: 'http://<%= repos %>/saltstack/yum/redhat/$releasever/$basearch/%s'
      init_environment: |
        sudo sed -i "s/mirrorlist/#mirrorlist/g" /etc/yum.repos.d/CentOS-Base.repo
        sudo sed -i "s/#baseurl/baseurl/g" /etc/yum.repos.d/CentOS-Base.repo
        sudo sed -i "s/mirror.centos.org/<%= repos %>/g" /etc/yum.repos.d/CentOS-Base.repo
      install_after_init_environment: true

suites:
  - name: default

verifier:
  name: "goss"
  sleep: 0
  use_sudo: true
  goss_version: "v0.3.6"
  validate_output: "tap"
  goss_link: "http://<%= repos %>/ops-cmpt-saltfs/goss/goss-linux-${ARCH}"
  goss_download_path: "/tmp/goss-${VERSION}-${DISTRO}-${ARCH}"
  env_vars: <%= render_yaml("prometheus/common.yaml") %>

```
PS: [this code example](https://github.com/komoot/opscommander/blob/master/examples/awesome.yaml.erb) inspire me

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

[kitchen verify -l debug](https://gist.github.com/stefanmonkey/bb95f47163331f5746c4aa2f54749d22#file-kitchen-verify-l-debug)

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.
[kitchen diagnose](https://gist.github.com/stefanmonkey/bb95f47163331f5746c4aa2f54749d22#file-kitchen-diagnose-no-instances-loader)

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
