### ISSUE TITLE
Failing lifecyle hooks when defined outside of multiple suites

### ISSUE THREAD

**Issue by jerryaldrichiii** [test-kitchen/test-kitchen#1539]
## Description

When using lifecycle hooks outside of at least 2 suites the following error is given:

```
#<Thread:0x00000000052413c8@/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
         9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
         8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
         7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:140:in `converge'
         6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
         5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
         4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
         3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
         2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `run'
         1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:75:in `block in run': Unknown lifecycle hook target {} (Kitchen::UserError)
```

This does not occur if you only define 1 suite.

## Kitchen Version

```ruby
Test Kitchen version 1.24.0
```

## ChefDK Version

```ruby
Chef Workstation: 0.2.43
  chef-run: 0.2.4
  chef-client: 14.8.12
  delivery-cli: master (5fb4908da53579c9dcf4894d4acf94d2d9ee6475)
  berks: 7.0.7
  test-kitchen: 1.24.0
  inspec: 3.2.6
```

## Platform Version

Arch Linux

## Replication Case

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

lifecycle:
  pre_converge:
    - remote: echo 'This fails on the second suite'

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

## Kitchen Diagnose

https://gist.github.com/jerryaldrichiii/77233d2cc6e6759d8a36ceb7666f6574
