### ISSUE TITLE
lifecyle hooks skippable true not honored when defined in platforms

### ISSUE THREAD

**Issue by bipinbachhao-lilly** [test-kitchen/test-kitchen#1543]
## Description

Defined Lifecycle hook pre_destroy in Platform as each platform needs different commands, when actual command fails then it causing whole kitchen destroy fails.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
# Copy-paste your results here
```
kitchen --version
Test Kitchen version 1.24.0

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
# Copy-paste your results here
```
Chef Development Kit Version: 3.9.0
chef-client version: 14.12.3
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.24.0
inspec version: 3.9.3

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
# Copy-paste your results here
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

MacOS 10.14.3

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

kitchen.yml
```
platforms:
  - name: centos-7.6
    driver:
      vm_hostname: default-centos-76.temp.com
    lifecycle:
      pre_destroy:
      - remote: sudo adleave
        skippable: true
  - name: ubuntu-16.04
    driver:
      vm_hostname: default-ubuntu-1604.temp.com
    lifecycle:
      pre_destroy:
      - remote: sudo adleave
        skippable: true
  - name: ubuntu-18.04
    driver:
      vm_hostname: default-ubuntu-1804.temp.com
    lifecycle:
      pre_destroy:
      - remote: sudo adleave
        skippable: true
  - name: rhel-7.6
    lifecycle:
      pre_destroy:
      - remote: sudo subscription-manager  unregister; sudo subscription-manager clean; sudo adleave
        skippable: true

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    run_list:
      - recipe[sat_subscription::default]

```
## Kitchen Output

```ruby

kitchen destroy centos
-----> Starting Kitchen (v1.24.0)
       Machine is not joined to any domain.
#<Thread:0x00007fd17e4353a8@/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:173:in `destroy'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `run'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:64:in `each'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:73:in `block in run'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:132:in `run_remote_hook'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.24.0/lib/kitchen/transport/ssh.rb:141:in `execute': SSH exited (10) for command: [sudo adleave] (Kitchen::Transport::SshFailed)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::Transport::SshFailed
>>>>>> Message: SSH exited (10) for command: [sudo adleave]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


```
## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
