### ISSUE TITLE
Test Kitchen 2.2 - License prompt not being accepted via env variable

### ISSUE THREAD

**Issue by ludovicbonivert** [test-kitchen/test-kitchen#1553]
## Description

The prompt for CHEF license acceptance keeps being asked while the environment variables are set

## Kitchen Version

Test-kitchen version 1.17

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby

Chef Development Kit Version: 2.3.3
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.
Running a kitchen-docker centos 

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

.kitchen.yml
```
---
driver:
  name: docker
  use_sudo: false
  chef_version: latest
  use_internal_docker_network: true

provisioner:
  chef_license: accept

verifier:
  name: inspec

platforms:
- name: centos
  driver_config:
    image: centos
    platform: rhel

suites:
  - name: default
    run_list:
    - recipe[vra_chefcookbook_yum::default]
    verifier:
      inspec_tests:
        - test/integration/default
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
Transferring files to <default-centos>
       +---------------------------------------------+
            Chef License Acceptance

       Before you can continue, 2 product licenses
       must be accepted. View the license at
       https://www.chef.io/end-user-license-agreement/

       Licenses that need accepting:
         * Chef Infra Client
         * Chef InSpec

       Do you accept the 2 product licenses (yes/no)?
```

## Additional comments

Basing myself on following docs to automatically accept the licenses
https://docs.chef.io/chef_license_accept.html
https://github.com/test-kitchen/test-kitchen/blob/master/RELEASE_NOTES.md

**Comment by oleg-filiutsich** [comment]
We catch some problems with chef-zero provisioner and chef new version 15.

In chef version 14.12.9 all works fine.
So workaround hardcode chef version in .kitchen.yml

**Comment by The3ngineer** [comment]
Yes we had to hardcode the Chef version as well - in our case like this in the provisioner section:

```
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.10.9
```


With the version 14 client the chef-licence line is redundant and with version 15 just does not seem to work as reported by @ludovicbonivert.
