### ISSUE TITLE
File transfer to Windows Azure VM fails as kitchen temp directory is a file

### ISSUE THREAD

**Issue by dalee-bis** [test-kitchen/test-kitchen#1564]
## Description

I'm attempting to run kitchen to test a cookbook in a Azure SQL Server 2017 on Windows Server 2016 VM. When running `kitchen converge` execution fails with the following errors because an OpenSSH key is created at `C:\Users\azure\AppData\Local\Temp\kitchen` (file), followed by kitchen attempting to extract transferred files to a `C:\Users\azure\AppData\Local\Temp\kitchen` directory. Since both cannot exist at the same time, the command fails.

If I log on to the VM, delete the file and then create the directory, the command will then execute successfully and ignore the creation of the key.

## Kitchen Version

```ruby
Test Kitchen version 1.24.0
```

## ChefDK Version

```ruby
Chef Development Kit Version: 3.7.23
chef-client version: 14.10.9
delivery version: master (64f556d5ebfd7bac2c0b3cc2c53669688b3ea4b5)
berks version: 7.0.8
kitchen version: 1.24.0
inspec version: 3.4.1
```

## Platform Version

Executing kitchen commands on:
Windows 10 64-bit

Running against:
Windows Server 2016 Datacenter 64-bit

## Replication Case

Kitchen file (sensitive information removed):

```yaml
---
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: "14.2.0"
  log_level: 'info'
  data_bags_path: 'test/integration/data_bags'

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: azure-windows-2016
    os_type: windows
    driver:
      name: azurerm
      subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
      location: 'North Europe'
      machine_size: 'Standard_D12_v2'
      image_urn: MicrosoftSQLServer:SQL2017-WS2016:Standard:14.1.190409
      format_data_disks: true

suites:
  - name: default
    run_list:
      - ...
    verifier:
      inspec_tests:
        - test/integration/default
```

## Kitchen Output

```ruby
I, [2019-05-30T15:24:19.207519 #10732]  INFO -- default-azure-windows-2016: Transferring files to <default-azure-windows-2016>
E, [2019-05-30T15:24:41.041740 #10732] ERROR -- default-azure-windows-2016: Converge failed on instance <default-azure-windows-2016>.
E, [2019-05-30T15:24:41.042011 #10732] ERROR -- default-azure-windows-2016: ------Exception-------
E, [2019-05-30T15:24:41.042152 #10732] ERROR -- default-azure-windows-2016: Class: WinRM::FS::Core::FileTransporterFailed
E, [2019-05-30T15:24:41.042282 #10732] ERROR -- default-azure-windows-2016: Message: [WinRM::FS::Core::FileTransporter] Upload failed (exitcode: 0), but stderr present
Cannot create "C:\Users\azure\AppData\Local\Temp\kitchen" because a file or directory with the same name already exists.
At line:12 char:40
+   $path | ? {-not (test-path $_)} | % {$null = mkdir $_}
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\azure\...p\kitchen\cache:String) [New-Item], IOException
    + FullyQualifiedErrorId : CreateDirectoryIOError,Microsoft.PowerShell.Commands.NewItemCommand
Cannot create "C:\Users\azure\AppData\Local\Temp\kitchen" because a file or directory with the same name already exists.
At line:12 char:40
+   $path | ? {-not (test-path $_)} | % {$null = mkdir $_}
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\azure\...tchen\cookbooks:String) [New-Item], IOException
    + FullyQualifiedErrorId : CreateDirectoryIOError,Microsoft.PowerShell.Commands.NewItemCommand
Could not find a part of the path 'C:\Users\azure\AppData\Local\Temp\kitchen\cookbooks\'.
At line:47 char:17
+   dir $unpack | cp -dest "$dst/" -force -recurse
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (metadata.json:FileInfo) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : CopyDirectoryInfoItemIOError,Microsoft.PowerShell.Commands.CopyItemCommand

```
