### ISSUE TITLE
QUESTION: platform name as a variable

### ISSUE THREAD

**Issue by giovtorres** [test-kitchen/test-kitchen#1566]
## Description

Is there a way to access the platform name as a variable?

For example, I would like to do the following:

```yaml
platform:
  - name: foo
  - name: bar

suites:
  - name: mysuite
    driver:
      variables:
        myvar: <%= "myvar-#{PLATFORM_NAME}" %>
```

where `myvar` would resolve to `myvar-foo` and `myvar-bar` per platform.

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.24.0
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin18]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

```
macOS Mojave
```
