### ISSUE TITLE
Deprecation of omnibus parameters

### ISSUE THREAD

**Issue by bobchaos** [test-kitchen/test-kitchen#1628]
## Description
The Cinc project has people use cinc-client with the chef_zero provisioner like so:

```yaml
provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  chef_omnibus_url: https://omnitruck.cinc.sh/install.sh
  chef_omnibus_root: /opt/cinc
```
This raises deprecation warnings on `chef_omnibus_url` and `require_chef_omnibus`. We can't just plain remove the deprecation messages, as they are used to direct Chef Infra users to the correct directives, but leaving them in is confusing to users of 3rd party distributions.

I'm opening this issue so we can discuss publicly of the best course of action here. An ideal solution would:
- direct Chef Infra users to use the new `product_name` and co
- avoid suggesting to users of other distros that the params they use are going away or are bad

I considered simply removing the deprecations, but it leaves no instructions for Chef Infra users

I've considered adding something in `doctor`, but folks get directed to doctor only when there's deprecated attributes used.

I tried making the deprecations themselves conditional on matching "chef.io" in the `chef_omnitruck_url` but couldn't get that to work (it could just be I'm bad at ruby tho o.O )

Thoughts? Ideas?

**Comment by ramereth** [comment]
I've been testing using kitchen with some alpha Cinc Workstation builds which includes our fork of mixlib-install. mixlib-install sets all of the product names, omnitruck URL, etc. From what I understand, the new method kitchen uses relies on mixlib-install so in order for this to work properly you need to use our forked version of mixlib-install.

I can confirm thus far that using Cinc Workstation with our mixlib-install negates the need for using the deprecated options. As long as you don't set the ``product_name`` as ``chef`` in your Kitchen, it should work "out of the box".

However for users of Chef Workstation, that's another issue but I'm not sure if we want to try and fix it. For now it's a big deal since we don't have a proper Cinc Workstation built but in the long run it's not an issue.

**Comment by tas50** [comment]
I'm going to close this one out since it sounds like you don't need the deprecated options to use cinc. I have a few more fixes that need to go into the new options and then we'll start to more aggressively move folks off the legacy options.

**Comment by mromero-convoso** [comment]
commenting here so others that run into this deprecation message will know immediately how to resolve:
```
provisioner:
  name: chef_zero
  product_name: cinc
  download_url: https://omnitruck.cinc.sh/install.sh
```
