### ISSUE TITLE
chef.bat exec kitchen converge|verify|test fails with "The command line is too long" in GitHub Actions Windows runners?

### ISSUE THREAD

**Issue by affrae** [test-kitchen/test-kitchen#1630]
## Description

Hi, I am not sure if this is a ChefDK/test-kitchen bug or not, so apologies for any perceived spam.

I have run into something interesting and I cannot tell what I can be doing wrong. Hope you can provide a pointer as to what I can try, or at least confirm expected behaviours.

I am trying to create a Chef workflow in GitHub Actions and `kitchen` commands `converge`, `test` and `verify` are failing with the error `The command line is too long` on the Windows Runner.

I noticed that https://github.com/test-kitchen/test-kitchen/issues/854 reports on a similar issue around commands that are too long and was subsequently fixed in https://github.com/test-kitchen/test-kitchen/pull/878

However looking at https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/transport/winrm.rb it seems that execute from file is no longer occurring - could this be causing my problem?

Runs and passes on Ubuntu and Mac Runners

## Kitchen Version

`Test Kitchen version 2.3.4`

## ChefDK Version

If you are running test-kitchen via ChefDK or Chef Workstation, `chef --version` will provide additional relevant version details.

ChefDK was installed from chefdk-4.7.73-1-x64.msi using the command:

`           . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chefdk
`

## Ruby Version

If you are not using test-kitchen via ChefDK or Chef Workstation, please provide the output of ruby --version.

I am using ChefDK, but included anyway:

```ruby
ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

```
Run systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List

OS Name             : Microsoft Windows Server 2019 Datacenter
OS Version          : 10.0.17763 N/A Build 17763
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Server
OS Build Type       : Multiprocessor Free
System Boot Time    : 3/4/2020, 7:30:27 PM
System Manufacturer : Microsoft Corporation
System Model        : Virtual Machine
System Type         : x64-based PC
System Directory    : C:\windows\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 4 Hotfix(s) Installed.,[01]: KB4532947,[02]: KB4486153,[03]: KB4523204,[04]: KB4532691
```

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

To replicate - make a change to a file and push to the repo so that the workflow is triggered on `[push]`

Essentially the runner kicks off ChefDK, Kitchen etc is installed and then a `chef.bat kitchen converge` (or `verify` or `test`) is executed.

Unfortunately I do not run Windows so I cannot test locally on my laptop.

GitHub Repository:  https://github.com/Affraes-Organisation/actions-chef-example

`.kitchen.yml` file:

``` yml
---
driver:
  name: exec

provisioner:
  name: chef_zero
  install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: windows-2019
  - name: macos-10.15

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_client:
        chef_license: accept
```

`default.rb`:

``` ruby
#
# Cookbook:: chef-actions
# Recipe:: default
#
# Copyright:: 2019, The Authors, All Rights Reserved.

file '/tmp/HelloWorld.txt' do
 content 'Hello World!'

 verify do |path|
  open(path).read.include? 'Hello World!'
 end

 action :create
end
```

`default_test.rb` file:

``` ruby

# # encoding: utf-8

# Inspec test for recipe chef-actions::default

# The Inspec reference, with examples and extensive documentation, can be
# found at http://inspec.io/docs/reference/resources/

# This is an example test, replace it with your own test.
describe file('/tmp/HelloWorld.txt') do
  it { should exist }
  its('content') { should match("Hello World!") }
end
```

`workflow.yml` file:

``` yml
name: CI

on: [push]

env:
  CHEF_LICENSE: accept

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: |
           . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chefdk
           c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex;

    - name: Check Kitchen Version
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen --version
    - name: Diagnose
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen diagnose --all default-windows-2019
    - name: Converge
      run: c:\opscode\chefdk\bin\chef.bat exec kitchen converge --debug default-windows-2019
#    - name: Verify
#      run: c:\opscode\chefdk\bin\chef.bat exec kitchen verify --debug default-windows-2019
#    - name: Test
#      run: c:\opscode\chefdk\bin\chef.bat exec kitchen test --debug default-windows-2019
# Verify and Test fail as well, also fails with and without –debug flag for all three

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
    - name: Verify
      run: chef exec kitchen verify default-ubuntu-1804

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Chef
      run: curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
    - name: Verify
      run: chef exec kitchen verify default-macos-1015
```

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

https://gist.github.com/affrae/e8f2bcbbd5cd93d0d58c6a09d7cd1d2a

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

https://gist.github.com/affrae/1611eabb0e3c1bc25f7612c8d875fbc9

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.
