### ISSUE TITLE
Allow for multiple default driver definitions

### ISSUE THREAD

**Issue by Triodes** [test-kitchen/test-kitchen#1632]
## Description

This is pretty much the same issue as #459 
Right now it seems is not possible to define multiple drivers in the default driver section of kitchen.yml.
My kitchen configuration is quite complex as I need to run 2 suites over 5 platforms using 3 different drivers. Right now I have to duplicate parts of the config to get this working. Having the ability to define the defaults for multiple drivers would reduce this duplication.

I have included my kitchen.yml below for reference. Maybe I am missing something here so any help would be appreciated. 😃 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).

```ruby
Test Kitchen version 2.3.3
```

## Ruby Version

If you are not using test-kitchen via ChefDK or Chef Workstation, please provide the output of ruby --version.

```ruby
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
```

## Platform Version

rhel7.7

## Replication Case
As you can see below the network and vagrantfile configuration options of the vagrant driver configuration is duplicated across 2 platforms:
```yaml
---
driver:
  name: azurerm
  subscription_id: '<redacted>'
  location: 'West Europe'
  machine_size: 'Standard_DS2_v2'
  vnet_id: '<redacted>'
  subnet_id: trs-10.0.68.0_24
  vm_tags:
    description: 'Kitchen test'

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  install_strategy: always
  environments_path: test/environments
  chef_license: accept
  data_bags_path: test/fixtures/data_bags
  roles_path: test/fixtures/roles
  client_rb:
    environment: kitchen
    rubygems_url: 'http://repos.unix.corp/gems/'
  http_proxy: 'http://proxy.unix.corp:8080'
  https_proxy: 'http://proxy.unix.corp:8080'

verifier:
  name: inspec

lifecycle:
  pre_destroy:
  - remote: /opt/commvault/Base/cvpkgrm -i Instance001
    skippable: true

platforms:
  - name: onprem-rhel7
    driver:
      name: vagrant
      box: rhel7-r2017
      customize:
        default_prefix: "ach_commvault_onprem_#{ENV['USER']}_rhel7"
      vm_hostname: "commvault-test-onprem-rhel7.example.com"
      vagrantfiles: 
        - vagrant/Vagrantfile.rb
      network:
        - ["forwarded_port", {guest: 8400, host: 8400, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8401, host: 8401, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8402, host: 8402, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8403, host: 8403, host_ip: "0.0.0.0"}]
  - name: onprem-sles12
    driver:
      name: vagrant
      box: sles12sp1
      customize:
        default_prefix: "ach_commvault_onprem_#{ENV['USER']}_sles12"
      vm_hostname: "comvault-test-onprem-sles12sp1.example.com"
      vagrantfiles: 
        - vagrant/Vagrantfile.rb
      network:
        - ["forwarded_port", {guest: 8400, host: 8400, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8401, host: 8401, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8402, host: 8402, host_ip: "0.0.0.0"}]
        - ["forwarded_port", {guest: 8403, host: 8403, host_ip: "0.0.0.0"}]
  - name: aix
    driver:
      name: powervc
      server_wait: 100
      openstack_username: "pvcuser"
      openstack_api_key: "<redacted>"
      openstack_auth_url: "https://usl10138.unix.corp:5000/v3"
      openstack_region: "RegionOne"
      openstack_project_domain: "Default"
      openstack_user_domain: "Default"
      openstack_project_name: "ibm-default"
      flavor_ref: "Default"
      network_ref:
        - "KITCHEN PRD 1460"
        - "KITCHEN BCK 1408"
        - "KITCHEN MGT 1423"
      public_key_path: "~/.ssh/id_rsa_powervc.pub"
      private_key_path: "~/.ssh/id_rsa_powervc"
      username: "kitchen"
      disable_ssl_validation: true
    driver_config:
      image_ref: image_aix71
    transport:
      name: ssh
      port: 22
      username: kitchen
      ssh_key: ~/.ssh/id_rsa_powervc
  - name: azure-sles12
    driver:
      name: azurerm
      image_urn: SUSE:SLES-SAP-BYOS:12-SP3:latest
      vm_name: <%= "itweu#{ENV['USER'][2..-1]}vm02" %>
    driver_config:
      hostname: "comvault-test-azure-sles12sp3.example.com"
    transport:
      ssh_key: ~/.ssh/id_rsa
  - name: azure-rhel7
    driver:
      name: azurerm
      image_urn: Redhat:RHEL:7-LVM:latest
      vm_name: <%= "itweu#{ENV['USER'][2..-1]}vm01" %>
    driver_config:
      hostname: "comvault-test-azure-rhel7.example.com"
    transport:
      ssh_key: ~/.ssh/id_rsa


suites:
  - name: onprem
    run_list:
      - recipe[ach_kitchen_data_bags]
      - recipe[atos_baselayer]
      - recipe[ach_consumer]
      - recipe[kitchen]
      - role[onprem_role]
    includes:
      - onprem-rhel7
      - onprem-sles12
      - aix
  - name: azure
    run_list:
      - recipe[ach_kitchen_data_bags]
      - recipe[ach_base]
      - recipe[kitchen]
      - role[azure_role]
    includes:
      - azure-rhel7
      - azure-sles12

```
