### ISSUE TITLE
Unable to run proxy driver on Github Actions 

### ISSUE THREAD

**Issue by damacus** [test-kitchen/test-kitchen#1633]
## Description

I'm trying to use Github Actions to run the Java cookbook on a MacOS runner

When I run `kitchen converge` on the instance using the proxy driver, I receive `[Inappropriate ioctl for device]`. 

For reference: 
- [software installed on MacOS runners](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md)
- Runners run at [MacStaduim.com]( https://www.macstadium.com/)

## Kitchen Version

```bash
Test Kitchen (v2.4.0)
```

## ChefDK Version

```bash
chef-workstation-0.17.5-1
```

## Platform Version

```bash
MacOS
```

## Replication Case

Use the following Github Actions yaml. [Found at this URL](https://github.com/sous-chefs/java/blob/c621d20026eb28f6e50df6c9f641075d3cdb3203/.github/workflows/ci.yml)

```yaml
# .github/workflows/ci.yaml
---
name: ci
'on':
  pull_request:
  push:
    branches:
      - master
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Run Test Kitchen
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.macos.yml
        run: |
          kitchen converge macos
```

## Kitchen Output

```bash
[Inappropriate ioctl for device]
```

## Kitchen Diagnose

[Gist](https://gist.github.com/damacus/4286668484f8315c05f4822bbf63363b)

**Comment by damacus** [comment]
After some digging, it looks like the proxy driver isn't the one I want. The exec driver works great for local exec, though both are undocumented (which I'd like to fix!) 

Here's the fix for running test kitchen against a local node if anyone needs it: 

```yaml
# kitchen.macos.yml
---
driver:
  name: exec
  host: localhost

provisioner:
  require_chef_omnibus: false
  chef_client_path: "/opt/chef-workstation/bin/chef-client"
  name: chef_zero
  deprecations_as_errors: false
  log_level: :info
  install_strategy: skip

suites:
  - name: adoptopenjdk-13-openj9
    run_list:
      - recipe[test::adoptopenjdk-13-openj9]

platforms:
   - name: macos
```
