### ISSUE TITLE
Shell Provisioner runs as Root

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/test-kitchen#1637]
## Description

I am using `test-kitchen` to run an ec2 instance and seems like the user is changed to root during 

`bundle exec kitchen ...`

I was able to print the environment variables during the `bootstrap.sh`

```
      Transferring files to <default-centos-7>
       LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
       SSH_CONNECTION=10.101.20.221 33012 10.160.22.221 22
       _=/bin/env
       LANG=en_US.UTF-8
       SUDO_GID=1000
       USERNAME=root
       SUDO_COMMAND=/tmp/kitchen/bootstrap2.sh
       XDG_SESSION_ID=2
       USER=root
       SELINUX_ROLE_REQUESTED=
       PWD=/home/centos
       HOME=/root
       SSH_CLIENT=10.101.20.221 33012 22
       SUDO_USER=centos
       SELINUX_LEVEL_REQUESTED=
       SSH_TTY=/dev/pts/0
       SUDO_UID=1000
       TERM=xterm
       SHELL=/bin/bash
       SELINUX_USE_CURRENT_RANGE=
       SHLVL=3
       LOGNAME=root
       DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
       XDG_RUNTIME_DIR=/run/user/1000
       TEST_KITCHEN=1
       PATH=/sbin:/bin:/usr/sbin:/usr/bin
       LESSOPEN=||/usr/bin/lesspipe.sh %s
```

## Kitchen Version

Test Kitchen version 2.4.0

```ruby
# Copy-paste your results here
```

## Ruby Version

```ruby
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

## Platform Version

CentOs 7.x

## Replication Case

Using the following `kitchen.yml` I was able to use the `bootstrap.sh` and run the `env` command.

```
---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEYNAME'] %>
  region: us-east-1
  availability_zone: b
  instance_type: <%= ENV['AWS_INSTANCE_TYPE'] %>
  associate_public_ip: false
  interface: private
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  security_group_ids: <%= ENV['AWS_LINUX_SG_ID'] %>
  retryable_tries: 120
  shared_credentials_profile: saml
  user_data: user_data.sh

provisioner:
  name: shell
  script: 'bootstrap.sh'

verifier:
  name: inspec

transport:
    name: ssh
    ssl: true
    ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEYNAME'] %>.pem
    connect_timeout: 60
    connection_retries: 5
    username: centos

platforms:
  - name: centos-7
    driver:
      image_id: <%= ENV['AWS_LINUX_AMI_ID'] %>
      username: centos
suites:
  - name: default
    verifier:
      inspec_tests:
        - test/os_spec.rb

```
