### ISSUE TITLE
Consider declaring the chef_solo provisioner single-threaded to protect berkshelf

### ISSUE THREAD

**Issue by clintoncwolfe** [test-kitchen/test-kitchen#1680]
## :ghost: Brief Description

Important background: [Berkshelf is not thread-safe and we're calling it wrong](#1307). The chef_solo provisioner - which I believe is obliged to use Berkshelf for cookbook resolution as it does not support Policyfiles - is thus highly unstable when used with the `-c` concurrency flag.

The correct long-term fix is as described on #1307 - to correct the way that we interface with Berkshelf. However, if #1678 is accepted, a short term tradeoff becomes possible - we can declare the chef_solo provisioner to be single-threaded.  Test kitchen will then be careful not to multithread that portion of the action chain.

It's a single line of code:
```
  no_parallel_for :converge
```
and would impact only ChefSolo (and anything that inherits from it, of which I am not aware of any). Notably, this change would not impact ChefZero nor the Dokken provisioner (which inherits from ChefZero).

With this change in place, I've had stable convergence runs using a Berksfile process using vagrant, ec2, and vcenter drivers using one platform, 10 suites, and `-c 5`.

There is a tradeoff here, depending on how fast your driver is and how large your converge phase. This slows down the converge phase (by making it run in serial instead of parallel) but at least it will be stable and reliable, allowing you to take advantage of concurrency in the create and destroy phases. In my testing of a 10-suite setup on vcenter run at 5x concurrency, test times increased from 7:30 to 10:15 typical.  A complex converge would have more impact.

## Version

Working on a branch of 2.6.0 with #1678 applied

## Environment

I primarily tested using the vcenter driver because that most often exhibited the error, though the ec2 driver and vagrant driver were also tested.

## Scenario

Have a stable converge stage with the chef_solo provisioner with concurrency enabled

## Steps to Reproduce

I used the following Kitchenfile:
```
driver:
  # Specific driver not important; don't use dokken
  name: vcenter
  vcenter_username: ...
  vcenter_password: ...
  vcenter_host:  ...

provisioner:
  name: chef_solo

platforms:
  - name: centos
    driver:
      cluster: ...
      network_name: VM Network
      folder: cwolfe
      clone_type: full
      datacenter: ...
      template: Templates/centos77-template
    transport:
      username: vagrant
      password: vagrant

suites:
  - name: vm-01
    run_list:
      - recipe[git]
  - name: vm-02
    run_list:
      - recipe[git]
  - name: vm-03
    run_list:
      - recipe[git]
  - name: vm-04
    run_list:
      - recipe[git]
  - name: vm-05
    run_list:
      - recipe[git]
  - name: vm-06
    run_list:
      - recipe[git]
  - name: vm-07
    run_list:
      - recipe[git]
  - name: vm-08
    run_list:
      - recipe[git]
  - name: vm-09
    run_list:
      - recipe[git]
  - name: vm-10
    run_list:
      - recipe[git]
```

With the following Berksfile:
```
source 'https://supermarket.chef.io'

cookbook 'git'
```

Then run 
```
kitchen converge -c 5
```

## Expected Result

Successful converge

## Actual Result
This is typical of errors seen due to Berkshelf being thread-unsafe, see #1307.
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 6 actions failed.
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory @ rb_sysopen - ip-10-0-22-2_us-east-2_compute_internal.crt] on vm-01-centos
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory - getcwd] on vm-07-centos
>>>>>>     Failed to complete #converge action: [An error occurred while reading the Berksfile:

  No such file or directory - getcwd] on vm-06-centos
```
