### ISSUE TITLE
Custom Omnibus API Support

### ISSUE THREAD

**Issue by bdwyertech** [test-kitchen/test-kitchen#1698]
I run my own internal Omnibus API in order to operate within an airgap.  It is pretty much a reverse proxy to omnibus.chef.io which rewrites package URL's and such to point toward our internal repository, which also functions as a caching proxy to packages.chef.io.  It also rewrites the response body for install.sh/ps1 to update all references to omnibus.chef.io to point toward the internal API.

At the moment, something like this works:
```yaml
provisioner:
  name: chef_zero
  require_chef_omnibus: 'latest'
  chef_omnibus_url: 'https://chef-omnitruck.myorg.net/install.sh'
```

If I go down the `product_name`, `product_version` route, I do not have a mechanism to feed in my internal omnibus API endpoint.  I'll take a stab at updating Test-Kitchen interaction `Mixlib::Install` and to pass this through, but wanted to point this out.

cc: @danielcbright @chefbob
