### ISSUE TITLE
multiple_converge not working on Windows

### ISSUE THREAD

**Issue by sandratiffin** [test-kitchen/test-kitchen#1798]
## :ghost: Brief Description

`multiple_converge: 2` results in 2 converges on linux, and 1 converge on Windows. 

## Version

Test Kitchen version: 3.0.0
Chef Workstation version: 21.8.555

## Environment

I am running Test Kitchen on macos (Catalina). 

## Scenario

I am trying to do multiple converges on Windows 2019 in particular, so that I can use `force_idempotency: true`, and it is not working.

## Steps to Reproduce

- `chef generate cookbook multiple_converge_bug`
- Add `multiple_converge: 2` and a couple of Windows platforms, i.e. replace kitchen.yml with:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  multiple_converge: 2

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: centos-8
  - name: windows-2016
    driver:
      box: tas50/windows_2016
  - name: windows-2019
    driver:
      box: tas50/windows_2019

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```
- `kitchen converge`

( I have only tried these 2 Windows versions/images).

## Expected Result

I would expect 2 converges for each platform.

## Actual Result

2 converges for the linux platforms, one for the Windows platforms.

For the linux boxes I get something like:
```
-----> Chef installation detected (install only if missing)
       Transferring files to <default-ubuntu-2004>
       Chef Infra Client, version 17.4.38
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Using Policyfile 'multiple_converge_bug' at revision '252763cd1eb486623f0a6cec6db335f2d2ea132cf8696360a3f7a25767021ae1'
       Resolving cookbooks for run list: ["multiple_converge_bug::default@0.1.0 (7afd775)"]
       Synchronizing cookbooks:
         - multiple_converge_bug (0.1.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Converging 0 resources

       Running handlers:
       Running handlers complete
       Infra Phase complete, 0/0 resources updated in 01 seconds
       Chef Infra Client, version 17.4.38
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Using Policyfile 'multiple_converge_bug' at revision '252763cd1eb486623f0a6cec6db335f2d2ea132cf8696360a3f7a25767021ae1'
       Resolving cookbooks for run list: ["multiple_converge_bug::default@0.1.0 (7afd775)"]
       Synchronizing cookbooks:
         - multiple_converge_bug (0.1.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Converging 0 resources

       Running handlers:
       Running handlers complete
       Infra Phase complete, 0/0 resources updated in 01 seconds
       Downloading files from <default-ubuntu-2004>
       Finished converging <default-ubuntu-2004> (0m18.33s).
-----> Test Kitchen is finished. (0m19.51s)
```

For both Windows boxes, something like:
```
-----> Chef installation detected (install only if missing)
       Transferring files to <default-windows-2019>
       Chef Infra Client, version 17.4.38
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Using Policyfile 'multiple_converge_bug' at revision '252763cd1eb486623f0a6cec6db335f2d2ea132cf8696360a3f7a25767021ae1'
       Resolving cookbooks for run list: ["multiple_converge_bug::default@0.1.0 (7afd775)"]
       Synchronizing cookbooks:
         - multiple_converge_bug (0.1.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Converging 0 resources

       Running handlers:
       Running handlers complete
       Infra Phase complete, 0/0 resources updated in 06 seconds
       Downloading files from <default-windows-2019>
       Finished converging <default-windows-2019> (0m22.48s).
-----> Test Kitchen is finished. (0m23.56s)
```
