### ISSUE TITLE
failing accept-no-persist chef license when using Policyfiles

### ISSUE THREAD

**Issue by logwolvy** [test-kitchen/test-kitchen#1837]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Using `accept-no-persist` as chef_license in chef_zero provisioner blocks the kitchen converge run

## Version

Test Kitchen version: 3.2.2

## Environment

Host OS: macOS Big Sur 11.6.1
VirtualBox version: 6.1.28
desktop-config cookbook version: 3.0.7
Chef Workstation version: 22.1.745
Chef CLI version: 5.5.0
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.26.1
Chef Infra Client version: 17.9.26
Chef InSpec version: 4.52.9

## Scenario

`accept-no-persist` license type should work.

## Steps to Reproduce

```yaml
# example kitchen.yml
provisioner:
  name: chef_zero
  deprecations_as_errors: true
  chef_license: accept-no-persist

platforms:
  - name: macos-chef-stable
    provisioner:
      product_name: chef
      product_version: latest
      channel: stable
    driver:
      box: tas50/macos_10.15
      name: vagrant
      customize:
        memory: 4096
        cpus: 2
```

## Expected Result

Successful kitchen converge

## Actual Result

```
-----> Converging <default-macos-chef-stable>...
       Preparing files for transfer
       Installing cookbooks for Policyfile /Users/tom/projects/desktop-config/Policyfile.rb using `/usr/local/bin/chef-cli install`
       Chef Workstation cannot execute without accepting the license
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Expected process to exit with [0], but received '172'
---- Begin output of /usr/local/bin/chef-cli install /Users/tom/projects/desktop-config/Policyfile.rb ----
STDOUT: Chef Workstation cannot execute without accepting the license
STDERR:
---- End output of /usr/local/bin/chef-cli install /Users/tom/projects/desktop-config/Policyfile.rb ----
Ran /usr/local/bin/chef-cli install /Users/tom/projects/desktop-config/Policyfile.rb returned 172] on default-macos-chef-stable
>>>>>> ----------------------
```

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.
