### ISSUE TITLE
Ability to test recipes that require multiple VMs connected to a chef server

### ISSUE THREAD

**Issue by b-dean** [test-kitchen/test-kitchen#184]
Some cookbooks, such as [opscode-cookbooks/jenkins](https://github.com/opscode-cookbooks/jenkins), have recipes that require more than one chef node. There is no good way to test those with test-kitchen as the combinations of platforms and suites only results in a chef run happening on a single VM (at a time or in parallel).

If one were testing these with a `Vagrantfile`, then the VMs could all be listed in the Vagrantfile in the correct order to run the tests. But then you lose all the advantages of test-kitchen for running the same suite on a bunch of different platforms.

I don't really have any ideas how to solve this problem but I didn't see any issues specifically addressing it either.

Here's a more concrete scenario. Say you wanted to test the jenkins cookbook's ability to have one chef node be a jenkins master and one be a jenkins slave. There are examples of the run lists for jenkins servers in [the jenkins cookbook's .kitchen.yml](https://github.com/opscode-cookbooks/jenkins/blob/master/.kitchen.yml) so I'm not going to type them here but the slave might look something like:

```
suites:
- name: ssh_slave_node
  run_list:
  - recipe[jenkins::node_ssh]
  attributes:
    jenkins:
      server:
        # IP address for the master
        host: 33.33.33.10
```

Any thoughts on how to test these kinds of recipes?
