### ISSUE TITLE
Incompatibility with OpenSS L3.0

### ISSUE THREAD

**Issue by raddessi** [test-kitchen/test-kitchen#1919]
## :ghost: Brief Description

This is a continuation of #1898, it seems that test-kitchen needs to allow net-ssh version 7 to be compatible with openssl 3.0 but the gem is currently locked to `net-ssh<7`. I'm not sure how you all intend for this to work without a patch.

## Version
```
# Gemfile
source 'https://rubygems.org'

gem 'net-ssh', '6.3.0.beta1'
gem 'git', '1.10.2'
gem 'kitchen-docker', :git => 'https://github.com/test-kitchen/kitchen-docker.git', tag: 'v2.12.0'
gem 'kitchen-salt', :git => 'https://github.com/saltstack/kitchen-salt.git', tag: 'v0.7.2'
gem 'test-kitchen', :git => 'https://github.com/test-kitchen/test-kitchen.git', tag: 'v3.3.1'
```

## Environment
Fedora 36
```bash
zsh ❯ rpm -qa | egrep  '(openssl|ruby)' | sort -n
apr-util-openssl-1.6.1-20.fc36.x86_64
openssl1.1-1.1.1q-1.fc36.x86_64
openssl-3.0.5-1.fc36.x86_64
openssl-devel-3.0.5-1.fc36.x86_64
openssl-libs-3.0.5-1.fc36.i686
openssl-libs-3.0.5-1.fc36.x86_64
openssl-pkcs11-0.4.12-2.fc36.i686
openssl-pkcs11-0.4.12-2.fc36.x86_64
ruby-3.1.2-169.fc36.x86_64
ruby-default-gems-3.1.2-169.fc36.noarch
ruby-devel-3.1.2-169.fc36.x86_64
rubygem-bigdecimal-3.1.1-169.fc36.x86_64
rubygem-bundler-2.3.7-169.fc36.noarch
rubygem-io-console-0.5.11-169.fc36.x86_64
rubygem-json-2.6.2-200.fc36.x86_64
rubygem-psych-4.0.3-169.fc36.x86_64
rubygem-rdoc-6.4.0-169.fc36.noarch
rubygems-3.3.7-169.fc36.noarch
ruby-libs-3.1.2-169.fc36.x86_64
rubypick-1.1.1-16.fc36.noarch
xmlsec1-openssl-1.2.33-3.fc36.x86_64
```

## Scenario

Running a converge fails as shown before
```bash
zsh ❯ time kitchen converge mycontainer --destroy=never
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
-----> Starting Test Kitchen (v3.3.1)

<snip>


       Container ID fc5c5ecf9c13a45553cae9fc26139ba6a9eac53867b77d51163f74e62198c777 already exists.
       172.15.6.2
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0] on mycontainer
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Steps to Reproduce

1. docker run -it -v /var/run/docker.sock:/var/run/docker.sock fedora:36 bash
    1. dnf install openssl ruby rubygem-bundler util-linux git passwd ruby-devel dnf-plugins-core -y
    2. dnf groupinstall "Development Tools" -y
    3. dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    4. dnf install docker-ce -y
    5. useradd kitchen
    6. passwd kitchen
    7. usermod -aG wheel kitchen
    8. usermod -aG docker kitchen
    9. chmod 777 /var/run/docker.sock
    10. su - kitchen
        1. vi Gemfile
            1. add:
                ```
                source 'https://rubygems.org'

                gem 'net-ssh', '6.3.0.beta1'
                gem 'git', '1.10.2'
                gem 'kitchen-docker', :git => 'https://github.com/test-kitchen/kitchen-docker.git', tag: 'v2.12.0'
                gem 'kitchen-salt', :git => 'https://github.com/saltstack/kitchen-salt.git', tag: 'v0.7.2'
                gem 'test-kitchen', :git => 'https://github.com/test-kitchen/test-kitchen.git', tag: 'v3.3.1'
                ``` 
        2. vi kitchen.yml
            1. add:
                ```
                driver:
                  name: docker
                  use_sudo: false
                  privileged: false
                  use_internal_docker_network: true
                  username: root
                  volume:
                    - /var/run/docker.sock:/docker.sock
                    - /sys/fs/cgroup:/sys/fs/cgroup:ro
                  cap_add:
                    - cap_sys_admin

                provisioner:
                  name: salt_solo
                  salt_install: bootstrap
                  salt_version: stable
                  salt_bootstrap_url: https://bootstrap.saltstack.com
                  salt_bootstrap_options: -X -p git -p rsync
                  salt_force_color: true
                  log_level: info
                  is_file_root: true
                  require_chef: false
                  sudo: true
                  salt_copy_filter:
                    - '*.pyc'
                    - .bundle
                    - .git
                    - .kitchen
                    - .nox
                    - .tox
                    - __pycache__
                    - artifacts
                    - Gemfile.lock


                platforms:
                  - name: alma-8-salt-3003-1-py3
                    driver:
                      image: almalinux:8
                      platform: centos
                    driver_config:
                      provision_command:
                      run_command: /usr/lib/systemd/systemd
                    provisioner:
                      salt_bootstrap_options: -P -X -x python3 git v3003.1

                suites:
                  - name: kitchen-salt-generic

                verifier:
                  name: shell
                  remote_exec: false
                  command: true
                ```
        4. bundle config set --local path 'vendor/bundle'
        5. bundle install
        6. bundle exec kitchen list
        7. bundle exec kitchen test

## Expected Result

Kitchen converge connects successfully.

## Actual Result

```
       Successfully built ce86bfe160f3
       14049328a8ed28d0d8e056bee83f04b89964a077d3ecd040556238e4a684340b
       172.15.6.4
       Waiting for SSH service on 172.15.6.4:22, retrying in 3 seconds
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [pkeys are immutable on OpenSSL 3.0] on kitchen-salt-generic-alma-8-salt-3003-1-py3
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```
