### ISSUE TITLE
Kitchen silently fails to converge if something underneath fails

### ISSUE THREAD

**Issue by drewhammond** [test-kitchen/test-kitchen#1934]
## :ghost: Brief Description

Test Kitchen silently fails to converge when something underneath, e.g., docker or berkshelf, hits an error.

## Version

- Test Kitchen version 3.5.0
- kitchen-dokken driver/provisioner 2.19.1

## Environment
kitchen-dokken driver/provisioner
MacOS 13.3 / M2 chip

```
➜  ~ /opt/cinc-workstation/bin/kitchen --version
Test Kitchen version 3.5.0

➜  ~ /opt/cinc-workstation/embedded/bin/ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin20]
``` 

## Scenario

I'd like more visibility into errors that are happening under the hood that prevent kitchen from converging as expected. Right now, if something like docker or berkshelf hits an error during `kitchen converge`, kitchen will just silently skip to the end and report that it finished successfully.

Even with debug logging, it's not clear what is failing or why (note: failures like this shouldn't be hidden in debug logs anyway, so   we shouldn't simply improve the debug logs)

This is very frustrating and makes it difficult for users to troubleshoot problems.

## Steps to Reproduce

1. Create simple `test` cookbook that has a bug.

The problem here is that the `27019:27019` port mapping can't be used on multiple running containers, so one of the platform containers will fail to start, and that is the test suite that will hit this bug.

```
# kitchen.yml

...

platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[test::default]
    driver:
      ports:
        - '27019:27019'
```

2.  `kitchen create`

3. `kitchen converge default-ubuntu-2204`

## Expected Result

Kitchen should stop and prominently display a helpful error message if something underneath hits an error.

## Actual Result

`kitchen converge` proceeds, silently skipping all steps after the failure occurs.

```
➜  test git:(master) kitchen converge default-ubuntu-2204
-----> Starting Test Kitchen (v3.5.0)
-----> Converging <default-ubuntu-2204>...
       Creating kitchen sandbox in /Users/drewh/.dokken/kitchen_sandbox/035278cc82-default-ubuntu-2204
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 8.0.5...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Finished converging <default-ubuntu-2204> (0m2.04s).
-----> Test Kitchen is finished. (0m2.93s)
```

## :heavy_plus_sign: Additional context

I hacked in some extra debug logging in `lib/kitchen/transport/base.rb` to print the actual command being run and the exception it hits and then it becomes clear that the problem was due to the container being stopped because of the port mapping conflict. 

```
D      Attempting to execute command - try 1 of 1. command: sh /opt/kitchen/run_command
D      Failed to run command
D      {"message":"Container e9aefb76102369dc176d51cd8efb8db4484f1fa400130262d3b9dac601b58b01 is not running"}
```

Some discussion on the community 

- https://chefcommunity.slack.com/archives/C2B6G1WCQ/p1681921322901749
