### ISSUE TITLE
Azure Hybrid Benefit for Windows Server

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [test-kitchen/test-kitchen#1941]
### :speaking_head: Foreword

Thank you for considering this feature request. Your attention to this matter is vital in enhancing the ease and efficiency of our provisioning process. Implementing this feature will enable us to leverage cost benefits seamlessly and avoid potential issues from being closed without resolution.

## :frowning_person: Problem Statement

I find it cumbersome and inconvenient that when using Test Kitchen for configuring and testing our infrastructure code, there is no option to specify the "License Type" to utilize the "Azure Hybrid Benefit for Windows Server" in the `kitchen.yml` file. This omission leads to unnecessary licensing costs when provisioning Windows servers, even when we could take advantage of existing on-premises licenses.

## :grey_question: Possible Solution

I propose adding functionality to Test Kitchen that allows users to declare their "License Type" for Windows servers directly in the `kitchen.yml` file. By including a new attribute, such as `license_type`, users should be able to specify that they want to use the "Azure Hybrid Benefit for Windows Server". Here is an example of how it could be integrated:

```yaml
driver:
  name: azurerm
  subscription_id: 'your-subscription-id'

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-server
    driver_config:
      image_urn: 'MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest'
      license_type: 'Windows_Server'
      ...

suites:
  - name: default
    ...
```

## :arrow_heading_up: Describe alternatives you've considered

1. **Manual Post-Deployment Adjustment:** One alternative is to manually adjust the license type post-deployment through the Azure portal. However, this is not efficient and can lead to avoidable costs.
   
2. **Custom Scripts:** Creating custom scripts to modify the `license_type` during the provisioning process is another option. While feasible, this approach requires additional setup and maintenance efforts.

## :heavy_plus_sign: Additional context

Integrating the option to specify "License Type" in the `kitchen.yml` file simplifies the provisioning process and ensures cost optimization by utilizing the Azure Hybrid Benefit for Windows Server. This feature request aligns with the objective of making infrastructure as code more efficient, user-friendly, and cost-effective.

By addressing this request, you can help us and many other users streamline the provisioning process and make efficient use of available benefits.
