### ISSUE TITLE
Kitchen verify return code zero with client error

### ISSUE THREAD

**Issue by luckeyca** [test-kitchen/test-kitchen#1977]
## :ghost: Brief Description

When kitchen verifier(inspec in this case) failed with client error, the command return code is still zero

## Version

test kitchen 3.5.1
kitchen-inspec 2.6.2

## Environment

oracle linux 8.10 os image testing on OCI. This issue should not be related to any particular environment, either cloud or on-prem with vagrant etc. as it's specific to the kitchen verify command.

snippet kitchen.yml (the ssh_key line was deliberately commented to generate the kitchen verify client error as it won't be able to ssh into the converged instance without ssh key). with the ssh_key line, everything works perfectly. so the kitchen.yml is valid.
```
---
driver:
  name: oci

transport:
  name: ssh
  username: opc
#  ssh_key: /root/.ssh/id_rsa

provisioner:
  name: shell

platforms:
  - name: oracle-linux-8
    driver:
        <oci driver configuration here>

verifier:
  name: inspec
  reporter:
    - cli
    - junit2:test/reports/%{platform}-%{suite}-inspec.xml

suites:
  - name: default
```

## Scenario

Doing negative testing to make sure all tasks in "kitchen test"(create/converge/setup/verify/destroy) have correct return code to make sure pipeline stage fails if any task fails. 

## Steps to Reproduce

1. Using the example kitchen.yml above, could be any cloud or even with vagrant, make sure kitchen verify command cannot ssh into the VM instance to perform inspec test.
2. run kitchen verify to reproduce the client error as below
```
-----> Verifying <default-oracle-linux-8>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 action failed.
>>>>>>     Failed to complete #verify action: [Client error, can't connect to 'ssh' backend: Your SSH Agent has no keys added, and you have not specified a password or a key file] on default-oracle-linux-8
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
4. run "echo $?" to get the command return code.

## Expected Result

The return code from step 4 should be non-zero

## Actual Result

The return code from step 4 is zero.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.
