### ISSUE TITLE
kitchen converge fails SSH into guest

### ISSUE THREAD

**Issue by msiebuhr** [test-kitchen/test-kitchen#1982]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When running `kitchen converge <something>`, it hangs with repeated `Waiting for SSH service on 127.0.0.1:52731, retrying in 3 seconds` before eventually failing.

After some debugging, it turns out the QEMU is running and has SSH up, but rejects kitchens' connections for some reason. Manually running `ssh kitchen@127.0.0.1 -p 52731` and password `kitchen` works fine, and can dig out a log saying along the lines of "ssh: Too manu authentication attempts".

After manually setting `:verbose => Logger::DEBUG` , the client tries enough of my SSH keys to get banned before getting around to the set password:

```
irb(main):013:0> x = Net::SSH.start('127.0.0.1', 'kitchen', {:user_known_hosts_file=>"/dev/null", :port=>17923, :compressio
n=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :keepalive_maxcount=>3, :timeout=>15, :password
=>"kitchen", :verify_host_key=>:never, :verbose => Logger::DEBUG, :keys => []})
D, [2024-09-04T09:04:41.434942 #248638] DEBUG -- net.ssh.transport.session[2d0b54]: establishing connection to 127.0.0.1:17923                                                                                                                    
D, [2024-09-04T09:04:41.435363 #248638] DEBUG -- net.ssh.transport.session[2d0b54]: connection established             
I, [2024-09-04T09:04:41.435477 #248638]  INFO -- net.ssh.transport.server_version[2d0b68]: negotiating protocol version
D, [2024-09-04T09:04:41.435552 #248638] DEBUG -- net.ssh.transport.server_version[2d0b68]: local is `SSH-2.0-Ruby/Net::SSH_7.2.3 x86_64-linux'                                                                                                    
...
D, [2024-09-04T09:04:41.470376 #248638] DEBUG -- net.ssh.authentication.session[2d0ba4]: beginning authentication of `kitchen'
...
D, [2024-09-04T09:04:41.520697 #248638] DEBUG -- net.ssh.authentication.session[2d0ba4]: allowed methods: publickey,password
...
D, [2024-09-04T09:04:41.526658 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (95:9d:16:8b:ec:de:b8:1b:60:8e:17:f2:b1:2a:5b:f4) alg rsa-sha2-256
...
D, [2024-09-04T09:04:41.537455 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (95:9d:16:8b:ec:de:b8:1b:60:8e:17:f2:b1:2a:5b:f4) alg ssh-rsa
...
D, [2024-09-04T09:04:41.548014 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (f2:a9:fc:08:42:56:f2:a5:cc:10:38:50:64:bd:3c:af) alg rsa-sha2-256
...
D, [2024-09-04T09:04:41.558556 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (f2:a9:fc:08:42:56:f2:a5:cc:10:38:50:64:bd:3c:af) alg ssh-rsa
...
D, [2024-09-04T09:04:41.569649 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (43:fa:4f:3a:a3:d8:38:86:b3:85:b1:85:df:29:7c:43) alg rsa-sha2-256
...
D, [2024-09-04T09:04:41.580471 #248638] DEBUG -- net.ssh.authentication.methods.publickey[2d0bf4]: trying publickey (43:fa:4f:3a:a3:d8:38:86:b3:85:b1:85:df:29:7c:43) alg ssh-rsa
...
/opt/.../embedded/lib/ruby/gems/3.1.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/session.rb:198:in `block in poll_message': disconnected: Too many authentication failures (2) (Net::SSH::Disconnect)
```

Alas, the client can't log in because it tries too many of my SSH keys (it shouldn't; the password is set for a reason :) )

Adding a `default_config :keys_only, true` around https://github.com/test-kitchen/test-kitchen/blob/v3.6.0/lib/kitchen/transport/ssh.rb#L45-L67 so it explicitly doesn't try any SSH keys fixes it for me. (Net::SSH docs: https://www.rubydoc.info/github/net-ssh/net-ssh/Net%2FSSH%2Estart)

## Version

3.6.0

## Environment

* Ubuntu Noble / 24.04
* Latest chef-workstation debian package (???)
* Test kitchen 3.6.0 (from the path having `gems/test-kitchen-3.6.0/lib/...` in it).
* https://github.com/esmil/kitchen-qemu

## Scenario

Running `kitchen converge <something>`

## Steps to Reproduce

Re-production requires a working qcow2 image with some not-so-obvious settings. I am unable to share our internal ones, and I'm not sure the infrastructure to build them is sanely reproducible in the open.

I'll be happy to test out updated versions or patch suggestions (though I am no ruby expert, so I might need a hint or two on getting the gem set up correctly).

## Expected Result

`kitchen verify` and friends helping me get work done

## Actual Result

`kitchen verify` and friends getting needlessly hung up on SSH...

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by Stromweld** [comment]
what does your kitchen.yml file look like?

**Comment by msiebuhr** [comment]
.kitchen.yml up till the attributes:

```yaml
driver:
  name: qemu
provisioner:
  name: chef_zero
  product_name: cinc
  install_strategy: skip
  chef_omnibus_root: /opt/chef
verifier:
  name: inspec
platforms:
  - name: focal
    driver:
      image: focal-all.qcow2
      networks:
        - netdev: user,id=user,net=192.168.1.0/24,hostname=%h,hostfwd=tcp::%p-:22
          # Use below netdev instead to set up port forwarding to ingress nodeports
          #- netdev: user,id=user,net=192.168.1.0/24,hostname=%h,hostfwd=tcp::%p-:22,hostfwd=tcp::10080-:30080,hostfwd=tcp::10443-:30443
          device: virtio-net-pci,netdev=user
        - netdev: socket,id=vlan,mcast=239.0.0.2:1235
          device: virtio-net-pci,netdev=vlan
      memory: 4096
      cpus: 6
      hostname: mymaster.k8s.example.com
    attributes: &...
```
