### ISSUE TITLE
Environment support for Chef Solo

### ISSUE THREAD

**Issue by ekrupnik** [test-kitchen/test-kitchen#199]
My understanding is that test-kitchen is built on Vagrant. Vagrant 1.3.1 and chef-solo 11.6 now supports passing environment and environments_path to read in all attributes for a specific environment, and run the chef-solo provisioner as dev environment for example.

Below is how Vagrant gets configured:

``` ruby
config.vm.provision :chef_solo do |chef|
  chef.log_level = :debug
  chef.data_bags_path = "../../data_bags"
  chef.environments_path = "../../environments"
  chef.roles_path = "../../roles"
  chef.encrypted_data_bag_secret_key_path = "~/.chef/encrypted_data_bag_secret"
  chef.environment = "dev"
end
```

I set the following in my `.kitchen.yml` config file:

``` yaml
suites:
  - name: default
    encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
    data_bags_path: "../../data_bags"
    roles_path: "../../roles"
    environments_path: "../../environments"
    environment: "dev"
    run_list: ["recipe[foo]", "recipe[minitest-handler]"]
```

and it does not appear that any properties/attributes from `../../environments/dev.rb` got pulled in. I also tried setting the environment using attributes, such as shown below.

```
suites:
  - name: default
    encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
    data_bags_path: "../../data_bags"
    roles_path: "../../roles"
    environments_path: "../../environments"
    environment: "dev"
    run_list: ["recipe[foo]", "recipe[minitest-handler]"]
    attributes:
      environment: "dev"
```

Is chef-solo environment support enabled in test kitchen?
