### ISSUE TITLE
Enable shell provisioner to use multiple files during converge.

### ISSUE THREAD

**Issue by 296951** [test-kitchen/test-kitchen#1999]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :frowning_person: Problem Statement

The Shell provisioner only supports one script file copied to the remote host and that file is executed.  I need to be able to copy multiple files that are called from the initial script.

## :grey_question: Possible Solution

The community supported Ansible provisioner provides a way to specify additional paths in the `.kitchen.yml` at converge time.  I propose a similar solution:

```
suites:
  - name: default
     provisioner:
       script: 'myscript.sh'
       additional_copy_path:
         - ./lib
         - ./test/data
       arguments:
         - arg1
         - arg2
```

`./lib`  and `./test/data` are recursively copied to the kitchen root, i.e. `/tmp/kitchen/{lib,test/data}` on converge.

`myscript.sh` is called during converge and can access files in `/tmp/kitchen/{lib,test/data}`

## :arrow_heading_up: Describe alternatives you've considered

None

## :heavy_plus_sign: Additional context

I know the shell provisioner is virtually unchanged for over a decade.  I do not want to fork and maintain my own version of test kitchen and I do think this could be of use to others.

I am willing to do the work and open a PR I am just wondering if it would even be considered before I begin the work.   The change should be backward compatible and not change existing default functionality.
