### ISSUE TITLE
Support an option to add minitest-handler to run list

### ISSUE THREAD

**Issue by jtimberman** [test-kitchen/test-kitchen#22]
To facilitate running tests under minitest-chef handler automatically, the default suite should include `minitest-handler` in the run list if a command-line option to the init command is specified. Currently:

``` yaml
suites:
- name: default
  run_list:
  - recipe[rng-tools]
  attributes: {}
```

Proposed:

``` yaml
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[rng-tools]
  attributes: {}
```
