### ISSUE TITLE
If the project is a cookbook, attempt to use "test" cookbook in the default run list

### ISSUE THREAD

**Issue by jtimberman** [test-kitchen/test-kitchen#24]
The current behavior of test-kitchen will assemble a run list with a "test" cookbook for each configuration if it exists. For example, in Opscode's [erlang](https://github.com/opscode-cookbooks/erlang) cookbook:

```
INFO: Run List is [recipe[test-kitchen::default], recipe[minitest-handler], recipe[erlang_test::default], recipe[erlang::default]]
```

The "test" cookbook is `erlang_test`. The default recipe is used because this is in the default "configuration" (or, suite in jamie).

In the current version of jamie, this requires an addition to each suite's run list. For example, erlang has two Test Kitchen configurations in the [current Kitchenfile](https://github.com/opscode-cookbooks/erlang/blob/master/test/kitchen/Kitchenfile), default and gui_tools. Each of the `erlang_test` recipes does include `recipe[erlang]`, so it is not explicitly necessary.

``` yaml
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[erlang_test]

- name: gui_tools
  run_list:
  - recipe[minitest-handler]
  - recipe[erlang_test::gui_tools]
```

It is important to note that common use of the "test" cookbook is to set node attributes prior to including the appropriate recipe to affect the way the recipe behaves. Also note that the minitest-chef handler will have tests run out of the "test" cookbook to assert the state of the node is reflected as required for the configuration.
