### ISSUE TITLE
Chef environment support missing?

### ISSUE THREAD

**Issue by dgivens** [test-kitchen/test-kitchen#297]
After upgrading from 1.0.0.beta4 to 1.1.1, it seems chef environment support has gone away. Using the same .kitchen.yml that was working in 1.0.0.beta4 with the current version, when I print node.environment to the log output, I get "_default" rather than the configured value. I've been able to produce this with both the chef-solo and chef-zero provisioners.

Note that environment support was added for chef-solo in pull request [235](https://github.com/test-kitchen/test-kitchen/pull/235).

Excerpt from my .kitchen.yml:

``` yaml
- name: api
  encrypted_data_bag_secret_key_path: "../../chef_test/secret-file"
  data_bags_path: "../../chef_test/data_bags"
  roles_path: "../../chef_test/roles"
  environments_path: "../../chef_test/environments"
  environment: "dev"
  run_list:
```

Where I log the environment in my recipe:

``` ruby
Chef::Log.info("RabbitMQ: #{node.environment} #{rabbitmq_creds}")
```

The output from chef-client run:

```
INFO: RabbitMQ: _default #<Chef::EncryptedDataBagItem:...>
```
