### ISSUE TITLE
Unable to override `test_base_path` in test-kitchen v1.2.1

### ISSUE THREAD

**Issue by jhx** [test-kitchen/test-kitchen#377]
I'm using test-kitchen v1.2.1 and attempting to override `test_base_path` in my `.kitchen.yml` file. I prefer to use `spec/integration` instead of the default `test/integration`. Below is an excerpt from my `.kitchen.yml` file:

```yaml
---
test_base_path: spec/integration

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # locally-provisioned opscode-centos-5.10 box with omnibus chef 11.8.2
  - name: centos-5.10-chef-11.8.2
    driver:
      box: opscode-centos-5.10-chef-11.8.2

suites:
  - name: example
    run_list:
      - 'recipe[example_recipe::default]'
    attributes: {}
```

Running `kitchen diagnose` indicates test-kitchen is still using `...test/integration` as the path. I've tried placing the `test_base_path` under `driver`, `provisioner`, and even `busser` without success. I've reviewed the source and it appears that I'm using the correct key. Can you please provide some direction on properly overriding this value?
