### ISSUE TITLE
`kitchen list` failing

### ISSUE THREAD

**Issue by joestump** [test-kitchen/test-kitchen#379]
```
Joes-MacBook-Air:sprint.ly jstump$ bundle exec kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ShellOut::ShellCommandFailed
>>>>>> Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant --version ----
STDOUT: 
STDERR: /Users/jstump/Dropbox/jstump/dev/sprint.ly/Vagrantfile:3:in `<top (required)>': undefined method `require_plugin' for Vagrant:Module (NoMethodError)
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:198:in `load'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:198:in `block in load_config!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:196:in `each'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:196:in `load_config!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:139:in `load!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:35:in `load!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/command.rb:12:in `execute'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/bin/vagrant:7:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/bin/vagrant:23:in `load'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/bin/vagrant:23:in `<main>'
---- End output of vagrant --version ----
Ran vagrant --version returned 1
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
```

My `kitchen.yml` file:

```

---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.0
  node_name: app
  environment_path: chef/environments
  role_path: chef/roles
  data_bag_path: chef/data_bags

platforms:
  - name: ubuntu-12.04

suites:
  - name: app
    run_list:
      - recipe[memcached]
      - recipe[mysql::client]
      - recipe[mysql::server]
      - role[vagrant_node]  
    attributes:
      SPRINTLY_ENV: DEVELOPMENT
      memcached:
        memory: 8
        listen: 127.0.0.1
      mysql:
        server_root_password: secret
        server_debian_password: secret
        server_repl_password: secret
        bind_address: 127.0.0.1
```

Looks like a Vagrant issue running in a bundle?

```
---- End output of vagrant --version ----
Ran vagrant --version returned 1
E, [2014-03-06T17:34:52.318053 #11133] ERROR -- Kitchen: ---Nested Exception---
E, [2014-03-06T17:34:52.318072 #11133] ERROR -- Kitchen: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2014-03-06T17:34:52.318087 #11133] ERROR -- Kitchen: Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant --version ----
STDOUT:
STDERR: /Users/jstump/Dropbox/jstump/dev/sprint.ly/Vagrantfile:3:in `<top (required)>': undefined method `require_plugin' for Vagrant:Module (NoMethodError)
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:198:in `load'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:198:in `block in load_config!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:196:in `each'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:196:in `load_config!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:139:in `load!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/environment.rb:35:in `load!'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/lib/vagrant/command.rb:12:in `execute'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-0.5.4/bin/vagrant:7:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/bin/vagrant:23:in `load'
    from /usr/local/Cellar/ruby/2.0.0-p353/lib/ruby/gems/2.0.0/bin/vagrant:23:in `<main>'
---- End output of vagrant --version ----
```
