### ISSUE TITLE
"I cannot read /tmp/kitchen/client.pem, which you told me to use to sign requests!"

### ISSUE THREAD

**Issue by joestump** [test-kitchen/test-kitchen#407]
```
[2014-04-13T01:46:28+00:00] WARN: Failed to read the private key /tmp/kitchen/client.pem: #<Errno::ENOENT: No such file or directory - /tmp/kitchen/client.pem>       

================================================================================       
Recipe Compile Error in /tmp/kitchen/cookbooks/nagios/recipes/default.rb       
================================================================================       


Chef::Exceptions::PrivateKeyMissing       
-----------------------------------       
I cannot read /tmp/kitchen/client.pem, which you told me to use to sign requests!       


Cookbook Trace:       
---------------       
  /tmp/kitchen/cookbooks/nagios/recipes/client.rb:34:in `from_file'       
  /tmp/kitchen/cookbooks/nagios/recipes/default.rb:23:in `from_file'       


Relevant File Content:       
----------------------       
/tmp/kitchen/cookbooks/nagios/recipes/client.rb:       

        27:  if node.run_list.roles.include?(node['nagios']['server_role'])
        28:    mon_host << node['ipaddress']
        29:  elsif node['nagios']['multi_environment_monitoring']
        30:    search(:node, "role:#{node['nagios']['server_role']}") do |n|
        31:     mon_host << n['ipaddress']
        32:    end
        33:  else
        34>>   search(:node, "role:#{node['nagios']['server_role']} AND chef_environment:#{node.chef_environment}") do |n|
        35:      mon_host << n['ipaddress']
        36:    end
        37:  end
        38:  
        39:  include_recipe "nagios::client_#{node['nagios']['client']['install_method']}"
        40:  
        41:  remote_directory node['nagios']['plugin_dir'] do
        42:    source "plugins"
        43:    owner "root"




Running handlers:       
       [2014-04-13T01:46:28+00:00] ERROR: Running exception handlers

       Running handlers complete


       [2014-04-13T01:46:28+00:00] ERROR: Exception handlers complete

       [2014-04-13T01:46:28+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out

Chef Client failed. 0 resources updated in 4.197894362 seconds       
[2014-04-13T01:46:28+00:00] ERROR: I cannot read /tmp/kitchen/client.pem, which you told me to use to sign requests!       
[2014-04-13T01:46:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)       
>>>>>> Converge failed on instance <app-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/app-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
>>>>>> ----------------------
```

``` yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  node_name: app10-dev
  environments_path: ./chef/environments
  roles_path: ./chef/roles
  data_bags_path: ./chef/data_bags

platforms:
  - name: ubuntu-12.04

suites:
  - name: app
    run_list:
      - role[wasatch_node]
    attributes:
      SPRINTLY_ENV: "DEV"
```
