### ISSUE TITLE
Doc needs updating with existing configuration options

### ISSUE THREAD

**Issue by esciara** [test-kitchen/test-kitchen#409]
Hi there,

There are some features that are not documented anywhere, such as the one introduced in 6e3043191b2c34858ccb97cc87f66ad6e5ce37a7 (which introduced several more):

``` yaml
provisioner:
  name: chef_solo
  solo_rb:
    http_proxy: http://192.168.1.1
    https_proxy: http://192.168.2.2
```

I was looking for that kind of configuration options, but could neither find it on http://kitchen.ci/, nor on http://docs.opscode.com/config_yml_kitchen.html. Took me a while to unearth it.

Is there any other neat stuff hidden like that?
