### ISSUE TITLE
add individual node definitions and global driver configuration to yaml format

### ISSUE THREAD

**Issue by bryanwb** [test-kitchen/test-kitchen#41]
the suite + platforms stanzas don't really fit integration testing i want to reuse the great components in jamie-tk (drivers and concurrency). Perhaps nodes could be used by jamie-tk and broken down into suite + platforms. My example scenario involves one apache webserver, one haproxy load balancer, and one back-end webserver. I want to test communication b/w all 3 nodes.

Here is my current abomination https://github.com/bryanwb/tk-demo/blob/master/.kitchen.yml . It's ugly and confusing. The suite + platforms stanzas don't really fit multi-node integration testing. Perhaps the node definition in my mockup below could be used by jamie-tk and broken down into suite + platforms.

Below is my mockup of what I have in mind. 

https://gist.github.com/4676677

``` YAML

---
provisioner: chef
nodes:
- name: app-server
  run_list: [ "recipe[tk-app]" ]
  attributes: {}
  driver_config:
    vagrant:
      network:
        hostonly: '33.33.33.10'   

- name: load-balancer
  run_list: [ "recipe[tk-haproxy]" ]
  attributes:
    tk_haproxy:
      backend_ips:
      - '33.33.33.10'
  driver_config:
    vagrant:
      network:
        hostonly: '33.33.33.11'   

drivers:
  vagrant:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
    customize:
      memory: 256
```
