### ISSUE TITLE
: Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E /tmp/busser/bin/busser test']

### ISSUE THREAD

**Issue by johntdyer** [test-kitchen/test-kitchen#411]
Hello,

 I am getting the following error when I run verify ( full logs below )

__kitchen verify dynamic-master-centos-510__
```shell
# jdyer at retina.local in ~/Projects/chef/site-cookbooks/bind on git:static_zone x [9:27:39]
$ kitchen verify dynamic-master-centos-510                                                                                                                                         ±[A1●●][static_zone]
-----> Starting Kitchen (v1.2.1)
-----> Verifying <dynamic-master-centos-510>...
       Removing /tmp/busser/suites/bats
       Uploading /tmp/busser/suites/bats/bind.bats (mode=0644)
-----> Running bats test suite
 ✗ named is found in PATH
          (in test file /tmp/busser/suites/bats/bind.bats, line 5)
 ✗ rndc is found in PATH
          (in test file /tmp/busser/suites/bats/bind.bats, line 11)

2 tests, 2 failures
Command [/tmp/busser/vendor/bats/bin/bats /tmp/busser/suites/bats] exit code was 1
>>>>>> Verify failed on instance <dynamic-master-centos-510>.
>>>>>> Please see .kitchen/logs/dynamic-master-centos-510.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E /tmp/busser/bin/busser test']
>>>>>> ----------------------
```

What is strange to me is that I can login to the test instance and run the same command w/o any problem.

#### Passing Example
```bash
# jdyer at retina.local in ~/Projects/chef/site-cookbooks/bind on git:static_zone x [9:28:14]
$ kitchen login dynamic-master-centos-510                                                                                                                                          ±[A1●●][static_zone]
Last login: Mon Apr 21 13:28:13 2014 from 10.0.2.2
[vagrant@dynamic-master-centos-510 ~]$ sudo su -
[root@dynamic-master-centos-510 ~]# sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E /tmp/busser/bin/busser test'
-----> Running bats test suite
 ✓ named is found in PATH
 ✓ rndc is found in PATH

2 tests, 0 failures
[root@dynamic-master-centos-510 ~]#
```

### Full logs

```log
I, [2014-04-21T09:28:13.970700 #16976]  INFO -- dynamic-master-centos-510: -----> Verifying <dynamic-master-centos-510>...
I, [2014-04-21T09:28:14.164067 #16976]  INFO -- dynamic-master-centos-510: Removing /tmp/busser/suites/bats
I, [2014-04-21T09:28:14.325893 #16976]  INFO -- dynamic-master-centos-510: Uploading /tmp/busser/suites/bats/bind.bats (mode=0644)
I, [2014-04-21T09:28:14.778546 #16976]  INFO -- dynamic-master-centos-510: -----> Running bats test suite
[1G   named is found in PATH[K[77G1/2[2GI, [2014-04-21T09:28:14.837464 #16976]  INFO -- dynamic-master-centos-510: [1G[31;1m ✗ named is found in PATH[K
I, [2014-04-21T09:28:14.837525 #16976]  INFO -- dynamic-master-centos-510: [0m[31;22m   (in test file /tmp/busser/suites/bats/bind.bats, line 5)
[0m[1G   rndc is found in PATH[K[77G2/2[2GI, [2014-04-21T09:28:14.840544 #16976]  INFO -- dynamic-master-centos-510: [1G[31;1m ✗ rndc is found in PATH[K
I, [2014-04-21T09:28:14.840600 #16976]  INFO -- dynamic-master-centos-510: [0m[31;22m   (in test file /tmp/busser/suites/bats/bind.bats, line 11)
I, [2014-04-21T09:28:14.840628 #16976]  INFO -- dynamic-master-centos-510: [0m
2 tests, 2 failuresI, [2014-04-21T09:28:14.840962 #16976]  INFO -- dynamic-master-centos-510: 
Command [/tmp/busser/vendor/bats/bin/bats /tmp/busser/suites/bats] exit code was 1I, [2014-04-21T09:28:14.841267 #16976]  INFO -- dynamic-master-centos-510: 
E, [2014-04-21T09:28:14.850959 #16976] ERROR -- dynamic-master-centos-510: Verify failed on instance <dynamic-master-centos-510>.
E, [2014-04-21T09:28:14.851044 #16976] ERROR -- dynamic-master-centos-510: ------Exception-------
E, [2014-04-21T09:28:14.851070 #16976] ERROR -- dynamic-master-centos-510: Class: Kitchen::ActionFailed
E, [2014-04-21T09:28:14.851091 #16976] ERROR -- dynamic-master-centos-510: Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E /tmp/busser/bin/busser test']
E, [2014-04-21T09:28:14.851113 #16976] ERROR -- dynamic-master-centos-510: ---Nested Exception---
E, [2014-04-21T09:28:14.851134 #16976] ERROR -- dynamic-master-centos-510: Class: Kitchen::SSHFailed
E, [2014-04-21T09:28:14.851154 #16976] ERROR -- dynamic-master-centos-510: Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; sudo -E /tmp/busser/bin/busser test']
E, [2014-04-21T09:28:14.851176 #16976] ERROR -- dynamic-master-centos-510: ------Backtrace-------
E, [2014-04-21T09:28:14.851197 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:112:in `rescue in run_remote'
E, [2014-04-21T09:28:14.851217 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:108:in `run_remote'
E, [2014-04-21T09:28:14.851238 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:63:in `block in verify'
E, [2014-04-21T09:28:14.851258 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/ssh.rb:47:in `initialize'
E, [2014-04-21T09:28:14.851279 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:61:in `new'
E, [2014-04-21T09:28:14.851299 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/driver/ssh_base.rb:61:in `verify'
E, [2014-04-21T09:28:14.851320 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/kitchen-vagrant-0.14.0/lib/kitchen/driver/vagrant.rb:85:in `verify'
E, [2014-04-21T09:28:14.851359 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
E, [2014-04-21T09:28:14.851381 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2014-04-21T09:28:14.851402 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
E, [2014-04-21T09:28:14.851424 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
E, [2014-04-21T09:28:14.851445 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
E, [2014-04-21T09:28:14.851466 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
E, [2014-04-21T09:28:14.851487 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
E, [2014-04-21T09:28:14.851509 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
E, [2014-04-21T09:28:14.851530 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:264:in `verify_action'
E, [2014-04-21T09:28:14.851550 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2014-04-21T09:28:14.851571 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
E, [2014-04-21T09:28:14.851591 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
E, [2014-04-21T09:28:14.851612 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:141:in `verify'
E, [2014-04-21T09:28:14.851632 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
E, [2014-04-21T09:28:14.851653 #16976] ERROR -- dynamic-master-centos-510: /Users/jdyer/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2014-04-21T09:28:14.851673 #16976] ERROR -- dynamic-master-centos-510: ----------------------
```

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10
  - name: centos-5.9

suites:
  - name: dynamic_master
    run_list:
      - recipe[base]
      - recipe[bind::master]
    attributes:
      bind:
        slaves: ["192.168.33.21"]
        is_omnibus: true
        runtime_servers: {
          "rt1.runtimes.routing.tropo":{ip: '20.2.0.1'},
          "rt2.runtimes.routing.tropo":{ip: '20.2.0.2'},
          "rt3.runtimes.routing.tropo":{ip: '20.2.0.3'}
        }
        gateway_servers: {
          "gw1.gateways.routing.tropo": {ip: '20.1.0.1'},
          "gw2.gateways.routing.tropo": {ip: '20.1.0.2'}
        }
  - name: static_master
    run_list:
      - recipe[base]
      - recipe[bind::master]
    attributes:
      bind:
        slaves: ["192.168.33.21"]
        is_omnibus: true
        dynamic_routing_zone: false
        runtime_servers: {
          "rt1.runtimes.routing.tropo":{ip: '20.2.0.1'},
          "rt2.runtimes.routing.tropo":{ip: '20.2.0.2'},
          "rt3.runtimes.routing.tropo":{ip: '20.2.0.3'}
        }
        gateway_servers: {
          "gw1.gateways.routing.tropo": { ip: '20.1.0.1'},
          "gw2.gateways.routing.tropo": {ip: '20.1.0.2'}
        }

```
