### ISSUE TITLE
Can't disable ohai plugins using chef-zero provisioner

### ISSUE THREAD

**Issue by jagibson** [test-kitchen/test-kitchen#415]
I see in the changelog that it's possible to pass in settings to client.rb.

I'm trying to disable the 'passwd' plugin for ohai because it tries to query the entire LDAP directory.  This is a problem because subsequent kitchen converg's take forever to run as long as the directory service is up.  Makes it hard to test :(

My understanding is that I should be able to put the setting under provisioner/client_rb, and indeed it seems to write the change to /tmp/kitchen/client.rb.  

However, when I run kitchen converg repeatedly after it still tries to query the entire LDAP directly - so it looks like the config setting is ignored.

If I run ohai -d /tmp/kitchen ohai ignores the passwd plugin as expected/desired.

Am I doing something wrong here?  There isn't much documentation for this feature.

Also, the line it adds to client.rb does not have a newline at the end if that matters.
## .kitchen.yml:

``` yaml

---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero
  client_rb:
    # Following the example at 
    # http://stevendanna.github.io/blog/2013/04/13/passwd-min-ohai-plugin/
    Ohai::Config[:disabled_plugins] =:
      - passwd

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[chef-client]
      - recipe[ohai::default]
      - recipe[authconfig::default]
    # also tried setting via chef-client.  doesn't work either
    attributes:
      ohai:
        disabled_plugins:
          - passwd
```

Here's the generated /tmp/kitchen/client.rb
## client.rb:

``` ruby
node_name "default-centos-65"
checksum_path "/tmp/kitchen/checksums"
file_cache_path "/tmp/kitchen/cache"
file_backup_path "/tmp/kitchen/backup"
cookbook_path ["/tmp/kitchen/cookbooks", "/tmp/kitchen/site-cookbooks"]
data_bag_path "/tmp/kitchen/data_bags"
environment_path "/tmp/kitchen/environments"
node_path "/tmp/kitchen/nodes"
role_path "/tmp/kitchen/roles"
client_path "/tmp/kitchen/clients"
user_path "/tmp/kitchen/users"
validation_key "/tmp/kitchen/validation.pem"
client_key "/tmp/kitchen/client.pem"
chef_server_url "http://127.0.0.1:8889"
encrypted_data_bag_secret "/tmp/kitchen/encrypted_data_bag_secret"
Ohai::Config[:disabled_plugins] = ["passwd"]​
```

Thanks very much!
