### ISSUE TITLE
Idea: enable chef-zero to run on another server than the converged node.

### ISSUE THREAD

**Issue by simonjohansson** [test-kitchen/test-kitchen#437]
Hello.
I have a idea and would like to discuss it before spending time on a PR.

As it is right now, chef-zero is started on the converged node in the chef-client run, which is cool and all. 

But I have a use case where I would like to do integration testing over a couple of cookbooks running on a couple of VMs in tandem, that will require search so it would be neat if Kitchen would support a external chef-zero server, via configuration in the kitchen.yml,

```
---
provisioner:
    name: chef_zero
    host: ip/hostname
    port: well, port
```

Thoughts? If a good idea I can implement support.
