### ISSUE TITLE
Can't add start/report/exception handlers to kitchen's client.rb

### ISSUE THREAD

**Issue by nBerg** [test-kitchen/test-kitchen#452]
I'm trying to add a handler to the test-kitchen run. I tried adding it by doing some variations on this: 

```
provisioner:
  name: chef_zero
  client_rb:
    require: "my_handler"
    start_handlers: "<< MyHandler::Handler.new"
```

Can't seem to get it to work. Is there a way to do this?

I just need it to add the lines `require "my_handler"` and `start_handlers << MyHandler::Handler.new` to the client.rb
