### ISSUE TITLE
Add ability to run multiple drivers in .kitchen.yml

### ISSUE THREAD

**Issue by jagibson** [test-kitchen/test-kitchen#459]
Just toying with this idea - it might be useful to be able to use multiple drivers at the same time for testing - say vagrant and ec2 for example.  I know this can be done with an environment variable, but it might be nice to do it all in .kitchen.yml.

If this is already possible I can't find any docs that mention it.

Thx.

**Comment by kgilpin** [comment]
It would be nice to use Vagrant for local development and debugging, and EC2 for test automation. Since the test automation machines are already VMs, they don't run VirtualBox.

**Comment by justinforce** [comment]
I have a great use case. I want to ensure that my cookbooks work on Mac and Linux. I'm testing on a Mac because that's what I have at work. Obviously, I've got to use VMware Fusion to run on the Mac, but I'd much rather use Docker to test the configuration on Linux. So there we go. Let me use something like

```yaml
drivers:
- name: vagrant
  provider: vmware_fusion
- name: docker

platforms:
- name: ubuntu
  driver: docker
- name: mac
  driver: vagrant
```
