### ISSUE TITLE
How to setup hostname of vm with .kitchen.yml ?

### ISSUE THREAD

**Issue by cvl-skubriev** [test-kitchen/test-kitchen#465]
Should i use driver_config, for example:
```
---
driver:
  name: vagrant
  network:
   - ["public_network", bridge: 'br-eth0']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu1404
    driver_config:
      box: ubuntu1404
      box_url: ~/vagrant-boxes-my/trusty64-updated.box
      hostname: pdcsmb
suites:
  - name: default
    run_list:
      - recipe[csmbpdc::default]
    attributes:
    driver_config:
      hostname: pdcsmb
```
How to setup hostname of vm with .kitchen.yml ?

Previous example does not help me. (

Vm started with no errors but with `default-ubuntu1404` hostname

**Comment by doertedev** [comment]
driver_options:
    vm_hostname: 'asdf'

Or did I oversee smth?

**Comment by afiune** [comment]
@cvl-skubriev @doertedev This was fixed with the following commit: 
https://github.com/test-kitchen/kitchen-vagrant/commit/e50d1460bbb3c7c43a6644e18a6223209ce86194

You can see the README file to get more information: 
https://github.com/test-kitchen/kitchen-vagrant#-vm_hostname

I will go ahead and close this but please feel free to open a new issue if you have more doubts about it. Cheers! :smile:

**Comment by cvl-skubriev** [comment]
Thank you for a tip. I will test new option in future.

**Comment by danielsand** [comment]
mhm

maybe im overseeing something.
```
---
driver:
  name: vagrant
  vm_hostname: tktest

provisioner:
  name: chef_zero
  data_bags_path: ../../data_bags
  nodes_path: ../../nodes
  environments_path: ../../environments
  roles_path: ../../roles
  encrypted_data_bag_secret_key_path: ~/.chef/encrypted_data_bag_secret_key

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
```

virtualbox name is default-ubuntu-14.04

any hint ?

**Comment by doertedev** [comment]
@danielsand  it !!!!MIGHT!!!! make sense to get the hostname on either the provisioner or the suite. Does this work?

**Comment by fnichol** [comment]
@doertedev it looks to me like @danielsand's right on the money--as of the 1.4.0.beta.* releases in the last couple of days, `:vm_hostname` is left unset by default for Windows platforms. However, you can still set this (as above), but note that the Vagrant driver will truncate your `:vm_hostname` to 12 characters to ensure that it doesn't trip over the 15 character max hostname limit on Windows.

**Comment by danielsand** [comment]
FYI

@doertedev: just as feedback i want to change the vm name completely. 
Im building up a CI that checks all company cookbooks with test-kitchen. 

So to support concurrent runs i wanted to use vagrant. Problem is - because of the hostname it only can run one concurrent VM, booting up a second will bash with the first one running.
 
Thats why i wanted to use the vm_hostname: setting inside of the driver options - to have full control over the hostname.

Specifying platform or suites is only doing half of what i want. (tested it also - doesn't work for me)

@fnichol: As of current version test-kitchen Version 1.4.0 - setting vm_hostname this still doesn't work. 
Im on Mac / Ubuntu.

im switching to docker - because of performance reasons. :)

**Comment by doertedev** [comment]
This has disturbed my latest testing as well. Setting up automatic CI machine bootups with test suites for specified gem versions, on application level and on policyfile level. Now when the server recognizes a gem update and tries to boot up a new machine, and the tests fail, you might want to have an extensive list of things that actually failed, and naming the machine in a way that makes sense is totally a must have. TL;DR I completely switched to version numbers. Sadly.

**Comment by xmik** [comment]
I've made a pull request https://github.com/test-kitchen/kitchen-vagrant/pull/170 which sets by default hostname to "kt-{kitchen_root_directory}-{instance_name}", you can override it to whatever you want (`vm_name` option) or you can disable changing hostname at all (`vm_hostname = false`). 

It works for me on Debian/Ubuntu/Windows.

**Comment by davidalpert** [comment]
in Test Kitchen `1.17.0` you can do this:
```
suites:
  - name: default
    driver:
      vm_hostname: pdcsmb.xyz.local
      customize:
        name: pdcsmb
        memory: 6144
        cpus: 4
```
