### ISSUE TITLE
Local platform exclusions

### ISSUE THREAD

**Issue by tejaycar** [test-kitchen/test-kitchen#493]
I'm looking for a way to add a platform to my .kitchen.local.yml, but limit which suites are run against my platform.  Specifically, I have several suites that build upon one another.  As a result, if each one runs from a totally clean state, it takes quite a while to install everything.  However, if I could build a few base boxes that are each part way along the processes, and then use those as my platforms, I could speed the tests considerably.  In looking for a way to do so, I've become aware of what I consider a major limitation of the .kitchen file.

When `.kitchen.yml` and `.kitchen.local.yml` are merged, only the hashes are deep merged.  Arrays are replaced in their entirety.  So:

**.kitchen.yml**
```
platforms:
  - ubuntu-12.04

suites:
  - name: test1
  - name: test2
```
**.kitchen.local.yml**
```
platforms:
  - my-special-platform
```

Results in 
`kitchen list`
```
Instance                             Driver       Provisioner        Last Action
test1-my-special-platform  Vagrant     ChefZero           <Not Created>
test2-my-special-platform  Vagrant     ChefZero           <Not Created>
```

What I'd love to be able to do is this:
**.kitchen.yml**
```
platforms:
  - ubuntu-12.04

suites:
  - name: test1
  - name: test2
```
**.kitchen.local.yml**
```
platforms:
  - my-special-platform

suites:
  - name: test1
    excludes:
      - my-special-platform
```

And end up with:
`kitchen list`
```
Instance                             Driver       Provisioner        Last Action
test1-ubuntu-12.04           Vagrant     ChefZero           <Not Created>
test2-ubuntu-12.04           Vagrant     ChefZero           <Not Created>
test2-my-special-platform    Vagrant     ChefZero           <Not Created>
```

I'm not aware of any way to do this (or similar things) at this point.  If the arrays were deep merged, just like the hashes are, then the local config file could make all sorts of adjustments to the project kitchen file, including changing runlist and attributes of platforms, and adjusting the runlists and exclusions of each suite.  But the merge logic would certainly be more complex, and maintaining the current functionality (where arrays are complete replaced) would be an issue.  

Am I the only one with this problem?  Any ideas on how to approach it without introducing a new config file and without breaking current functionality?
