### ISSUE TITLE
Support for running *_spec.rb according to the hostname or private ipaddress of a node

### ISSUE THREAD

**Issue by StaymanHou** [test-kitchen/test-kitchen#494]
my `.kitchen.yml` file
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: nfs-server-ubuntu
    run_list:
      - recipe[nfs::server]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.33"}]
  - name: nfs-client-ubuntu
    run_list:
      - recipe[nfs::client]
    driver:
      network:
      - ["private_network", {ip: "192.168.33.32"}]

suites:
  - name: nfs
    run_list:
    attributes:
...
```
my spec files
```
`-- test
    `-- integration
        `-- default
            `-- serverspec
                |-- 192.168.33.33
                |   `-- nfs_server_spec.rb
                |-- 192.168.33.32
                |   `-- nfs_client_spec.rb
                `-- spec_helper.rb
```
It runs both spec files on both nodes.
It would be great if the test can be carried out respectively. e.g. `nfs_server_spec.rb` only runs on 192.168.33.33 &  `nfs_client_spec.rb` only runs on 192.168.33.32

**Comment by smurawski** [comment]
@StaymanHou You could use two different suites (one for client and one for server) and break the tests up accordingly.  
e.g.
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: nfs-server-ubuntu
    driver:
      network:
      - ["private_network", {ip: "192.168.33.33"}]
  - name: nfs-client-ubuntu
    driver:
      network:
      - ["private_network", {ip: "192.168.33.32"}]

suites:
  - name: nfs-server
    run_list:
      - recipe[nfs::server]
    excludes:
      - nfs-client-ubuntu

  - name: nfs-client
    run_list:
      - recipe[nfs::client]
    excludes:
      - nfs-server-ubuntu

```
