### ISSUE TITLE
Extend shell_provisioner#data_path

### ISSUE THREAD

**Issue by jsirex** [test-kitchen/test-kitchen#497]
Now it is only possible to specify data directory.

It will be great if provisioner will support some customizations:
- filter files or directories
- uses locations

For example:

``` YAML
provisioner:
  name: shell
  data_path:
    # Hash dst dir in data => source
    .:  my_data/*    # means whole content of directory into data
    bin: other_dir/**/*.sh # only scripts *.sh into data/bin
```

Real use case: I've built project and my target directory contains lots of build files, classes, archives. But I want to transfer into VM only single archive and few scripts.

I known, that kitchen-vagrant can use shared folders but not all driver can do the same (I'm using kitchen-docker).

This changes behavior but it looks more flexible.

If you agree with me I'll try to write patch.
