### ISSUE TITLE
Environment problems again

### ISSUE THREAD

**Issue by ghost** [test-kitchen/test-kitchen#502]
I'm getting the infamous "Data Bag Items must contain a Hash or Mash!" error from test kitchen.  I'm not aware of anything that's changed.  So I've tried pinning `require_chef_omnibus` to an earlier version (matching production) to no avail.  I'm familiar with #317 and `filename.json` <=> `id` requirement.  As far as I can tell, that's not the issue.  

I've also run into problems with the chef-solo provisioner before, related to getting it to accept values from my .kitchen.yml file for environments, data bags, etc. located on my local machine.  I've gone back and double checked my notes, and re-read #199, and I don't believe that's the issue, either.  

`.kitchen.yml`:

``` yaml

---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: root-staging
  ssh_key: <%= File.expand_path('~/.ssh/root-staging.pem') %>
  security_group_ids: ["sg-47987d2e"]
  region: us-east-1
  availability_zone: us-east-1e
  require_chef_omnibus: '11.12.4'

provisioner:
  name: chef_solo
  environments_path: '../../environments'

platforms:
  - name: ubuntu-12.04
    driver:
      image_id: ami-072d3d6e
      username: ubuntu

suites:
  - name: webapp-dev
    driver:
        tags: {
            created-by: test-kitchen,
            Name: webapp-kitchen-dev
        }
    data_bags_path: 'test/integration/webapp-dev/data_bags'
    encrypted_data_bag_secret_key_path: '~/.ssh/encrypted_data_bag_secret'
    run_list:
      - recipe[webapp::default]
      - recipe[memcached::default]
      - recipe[percona::server]
      - recipe[bf-nrpe]
    attributes: {
        webapp: {
            data_bag_secret: '/tmp/kitchen/encrypted_data_bag_secret'
        },
        percona: {
            skip_passwords: 'true'
        }
    }
    provisioner:
        solo_rb:
            environment: development
```

The error follows:

```
===============================================================================
Recipe Compile Error in /tmp/kitchen/cookbooks/webapp/recipes/default.rb
===============================================================================
Chef::Exceptions::ValidationFailed
----------------------------------
Data Bag Items must contain a Hash or Mash!

Cookbook Trace:
---------------
         /tmp/kitchen/cookbooks/webapp/recipes/bf2_config.rb:9:in `from_file'
         /tmp/kitchen/cookbooks/webapp/recipes/default.rb:27:in `from_file'

Relevant File Content:
----------------------
       /tmp/kitchen/cookbooks/webapp/recipes/bf2_config.rb:

         2:  # Recipe:: bf2_config
         3:  #
         4:  # Copyright 2014, BuzzFeed
         5:  #
         6:  # All rights reserved - Do Not Redistribute
         7:
         8:  secret = Chef::EncryptedDataBagItem.load_secret(node['webapp']['data_bag_secret'])
         9>> webapp_keys = Chef::EncryptedDataBagItem.load("webapp", node.chef_environment, secret)
        10:
        11:  template '/opt/buzzfeed/buzzfeed/lib/buzzfeed2/Config.pm' do
        12:      variables(
        13:                  :dbmaster_password => webapp_keys['database']['master'],
```

```
webapp $ kitchen diagnose webapp-dev-ubuntu-1204

---
<snip>
      test_base_path: "/opt/buzzfeed/chef/cookbooks/webapp/test/integration"
      username: ubuntu
    provisioner:
      attributes:
        webapp:
          data_bag_secret: "/tmp/kitchen/encrypted_data_bag_secret"
        percona:
          skip_passwords: 'true'
      chef_omnibus_url: https://www.getchef.com/chef/install.sh
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: "/opt/buzzfeed/chef/cookbooks/webapp/test/integration/webapp/data_bags"
      data_path:
      encrypted_data_bag_secret_key_path: "/Users/Shared/Jenkins/.ssh/encrypted_data_bag_secret"
      environments_path: "/opt/buzzfeed/chef/environments"
      kitchen_root: "/opt/buzzfeed/chef/cookbooks/webapp"
      log_level: :info
      name: chef_solo
      nodes_path:
      require_chef_omnibus: 11.12.4
      roles_path:
      root_path: "/tmp/kitchen"
```

I'd gone as far as logging into the EC2 instance that won't converge and running 'knife data bag' in local mode to confirm that `encrypted_data_bag_secret` is available to my ubuntu user and able to decrypt the data bag that's been uploaded:

```
ubuntu@ip-10-29-34-16:/tmp/kitchen$ knife data bag show -z webapp development --secret-file encrypted_data_bag_secret
WARNING: No knife configuration file found
amzn:
  AMAZON_API_KEY: •••••
aviary:
  key:    *****
  secret: *****
id:               development
```

So I was curious if `node.chef_environment` is being evaluated as "development" in my Chef run.

```
diff --git a/cookbooks/webapp/recipes/bf2_config.rb b/cookbooks/webapp/recipes/bf2_config.rb
index 7c70009..130904e 100644
--- a/cookbooks/webapp/recipes/bf2_config.rb
+++ b/cookbooks/webapp/recipes/bf2_config.rb
@@ -6,7 +6,7 @@
 # All rights reserved - Do Not Redistribute

 secret = Chef::EncryptedDataBagItem.load_secret(node['webapp']['data_bag_secret'])
-webapp_keys = Chef::EncryptedDataBagItem.load("webapp", node.chef_environment, secret)
+webapp_keys = Chef::EncryptedDataBagItem.load("webapp", 'development', secret)
```

And the recipe compiles, test kitchen is happy.  Everyone gets to go home.  Except that I need to be able to evaluate "node.chef_environment" at run time, or else this cookbook will never make it onto a production node.  I've gone back to #199 have a dozen times and re-read it...  Has the `.kitchen.yml` syntax for the chef-solo provisioner changed recently?

```
webapp $ kitchen --version
Test Kitchen version 1.2.2.dev
```
