### ISSUE TITLE
Running two kitchen converges parallely?

### ISSUE THREAD

**Issue by wzin** [test-kitchen/test-kitchen#506]
Hello,

I'm not sure if this is a possible problem with test-kitchen.

When I run following commands in two terminal sessions on the same machine:

``` bash
bundle exec kitchen converge suiteA && bundle exec kitchen verify suiteA
```

and

``` bash
bundle exec kitchen converge suiteB && bundle exec kitchen verify suiteB
```

So exactly when the first (or second) command finishes all my virtualbox machines (even those not managed by vagrant, kitchen or anything else) are suddenly turned to "aborted" mode. Obviously the second converge + verify cannot finish so I get following error during verify (error probably cause by a "dissapearing" vm)

```
I, [2014-09-25T20:11:32.809385 #19093]  INFO -- Kitchen: -----> Creating <suiteB-ubuntu-1404>...
I, [2014-09-25T20:12:09.720616 #19093]  INFO -- Kitchen: -----> Converging <suiteB-master-ubuntu-1404>...
E, [2014-09-25T20:24:42.250269 #19093] ERROR -- Kitchen: ------Exception-------
E, [2014-09-25T20:24:42.254521 #19093] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2014-09-25T20:24:42.254535 #19093] ERROR -- Kitchen: Message: Failed to complete #converge action: [closed stream]
E, [2014-09-25T20:24:42.254545 #19093] ERROR -- Kitchen: ---Nested Exception---
E, [2014-09-25T20:24:42.254554 #19093] ERROR -- Kitchen: Class: IOError
E, [2014-09-25T20:24:42.254564 #19093] ERROR -- Kitchen: Message: closed stream
E, [2014-09-25T20:24:42.254573 #19093] ERROR -- Kitchen: ------Backtrace-------
E, [2014-09-25T20:24:42.254581 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select'
E, [2014-09-25T20:24:42.254590 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
E, [2014-09-25T20:24:42.254599 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:73:in `available_for_read?'
E, [2014-09-25T20:24:42.254758 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:85:in `next_packet'
E, [2014-09-25T20:24:42.254781 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
E, [2014-09-25T20:24:42.254803 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
E, [2014-09-25T20:24:42.254821 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
E, [2014-09-25T20:24:42.254830 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
E, [2014-09-25T20:24:42.254838 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
E, [2014-09-25T20:24:42.254846 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
E, [2014-09-25T20:24:42.254865 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
E, [2014-09-25T20:24:42.254873 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
E, [2014-09-25T20:24:42.254901 #19093] ERROR -- Kitchen: /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
E, [2014-09-25T20:24:42.254911 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/ssh.rb:255:in `exec_with_exit'
E, [2014-09-25T20:24:42.254919 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/ssh.rb:81:in `exec'
E, [2014-09-25T20:24:42.254928 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/driver/ssh_base.rb:150:in `run_remote'
E, [2014-09-25T20:24:42.254936 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/driver/ssh_base.rb:50:in `block in converge'
E, [2014-09-25T20:24:42.254950 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/ssh.rb:70:in `initialize'
E, [2014-09-25T20:24:42.254958 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/driver/ssh_base.rb:45:in `new'
E, [2014-09-25T20:24:42.254966 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/driver/ssh_base.rb:45:in `converge'
E, [2014-09-25T20:24:42.254974 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/kitchen-vagrant-1ce7b52c5791/lib/kitchen/driver/vagrant.rb:75:in `converge'
E, [2014-09-25T20:24:42.254982 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:347:in `public_send'
E, [2014-09-25T20:24:42.254990 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:347:in `block in perform_action'
E, [2014-09-25T20:24:42.254998 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:411:in `call'
E, [2014-09-25T20:24:42.255005 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:411:in `synchronize_or_call'
E, [2014-09-25T20:24:42.255013 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:376:in `block in action'
E, [2014-09-25T20:24:42.255021 #19093] ERROR -- Kitchen: /usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
E, [2014-09-25T20:24:42.255029 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:375:in `action'
E, [2014-09-25T20:24:42.255036 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:347:in `perform_action'
E, [2014-09-25T20:24:42.255053 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:307:in `converge_action'
E, [2014-09-25T20:24:42.255060 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:287:in `block in transition_to'
E, [2014-09-25T20:24:42.255068 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:286:in `each'
E, [2014-09-25T20:24:42.255076 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:286:in `transition_to'
E, [2014-09-25T20:24:42.255084 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/instance.rb:130:in `converge'
E, [2014-09-25T20:24:42.255092 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/command.rb:176:in `public_send'
E, [2014-09-25T20:24:42.255108 #19093] ERROR -- Kitchen: /var/lib/jenkins/.bundler/ruby/1.9.1/test-kitchen-349a728dda45/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2014-09-25T20:24:42.255116 #19093] ERROR -- Kitchen: ----------------------
```

IS this possible that kitchen somehow cripples the VMs after a successful converge + verify?

Kitchen Version 1.2.1
Kitchen Vagrant version 0.15.0

kitchen.yml:

```
provisioner:
  name: chef_zero
  environment: production
  encrypted_data_bag_secret_key_path: ~/.chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: suiteA
    driver:
      name: vagrant
      customize:
        memory: 2048
        cpus: 2
        nic1: 'nat'
        nic2: 'intnet'
        nic3: 'none'
        nic4: 'none'
        intnet2: 'my_netA'
        nicpromisc2: 'allow-all'
      network:
        - ["private_network", {"ip": "10.12.13.1"}]
    data_bags_path: "test/integration/default/data_bags"
    provisioner:
      client_rb:
        environment: production
    run_list:
      - role[my_roleA]
    attributes: { <some attribs > }

  - name: suiteB
    driver:
      name: vagrant
      customize:
        memory: 2048
        cpus: 2
        nic1: 'nat'
        nic2: 'intnet'
        nic3: 'none'
        nic4: 'none'
        intnet2: 'my_netB'
        nicpromisc2: 'allow-all'
      network:
        - ["private_network", {"ip": "10.12.13.1"}]
    data_bags_path: "test/integration/default/data_bags"
    provisioner:
      client_rb:
        environment: production
    run_list:
      - role[my_roleB]
    attributes: { <some attribs > }
```

May this be a kitchen issue or it's something system-wise?
