### ISSUE TITLE
Test Kitchen not seeing cookbooks?

### ISSUE THREAD

**Issue by elocnatsirt** [test-kitchen/test-kitchen#517]
Since installed test-kitchen I haven't been able to get it to work correctly. I can get a box spun up, login, etc., but I cannot get it to run any of my cookbooks. When I add my recipes to kitchen.yml, they are not found. My directory I'm using is /var/chef/cookbooks - I've tried running in that directory as well as descending into one of the cookbook directories and cannot get them working. My .kitchen.yml is as shown:

``` yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[update::default]

    attributes:

```

I get:
ERROR: Cookbook update not found. If you're loading update from another cookbook, make sure you configure the dependency in your metadata

What is the problem? I don't understand why it won't find the cookbooks at all. I apologize if this is the wrong section, it isn't an issue as much as a question.
