### ISSUE TITLE
CONVERGE: Failed to complete #converge action of .git folder

### ISSUE THREAD

**Issue by v1v** [test-kitchen/test-kitchen#544]
Console error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [scp: /tmp/kitchen/ansible-role-chef-client/.git/objects/00/1dabdbd07ae440510976be0867655f14edd83a: Permission denied
]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [scp: /tmp/kitchen/ansible-role-chef-client/.git/objects/00/1dabdbd07ae440510976be0867655f14edd83a: Permission denied
]
```

.kitchen.yml
```yaml
---
driver:
  name: docker
  use_sudo: false
  ssh:
    pty: true

driver_config:
  hostname: kitchen
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: ansible_playbook
  roles_path: ../../
  hosts: localhost
  playbook: site.kitchen.yml
  require_ansible_repo: true
  ansible_verbose: true

platforms:
  - name: centos-6.5
    driver_config:
      box: centos-6.5

suites:
- name: chef-client-sh
  extra_vars:
    type: sh
```

It works perfectly when I run kitchen converge firstly, but it doesn't work when I run again (using the same box)

I wonder if I can ignore that .git folder, if so, how do I do it? I´ve found when I run kitchen converge firstly it does copy those .git folders as below:

```
       Thank you for installing Chef!
D      sudo -E rm -rf /tmp/kitchen/modules /tmp/kitchen/roles /tmp/kitchen/group_vars /tmp/kitchen/host_vars; mkdir -p /tmp/kitchen
D      [SSH] kitchen@192.168.59.103:49160<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :password=>"kitchen", :port=>49160, :user=>"kitchen"}> (sudo -E rm -rf /tmp/kitchen/modules /tmp/kitchen/roles /tmp/kitchen/group_vars /tmp/kitchen/host_vars; mkdir -p /tmp/kitchen)
       Transfering files to <chef-client-sh-centos-65>
D      Uploaded /var/folders/8k/7y3k73s91lbdjmbh5x_47l580000gn/T/chef-client-sh-centos-65-sandbox-20141120-4294-1wuahsa/ansible-role-chef-client/.git/COMMIT_EDITMSG (30 bytes)
```

I've already forked kitchen-ansible and added some bits&pieces in order to remove that .git folder... but it looks like it's part of the kitchen core, Any ideas?

**Comment by davekonopka** [comment]
I ran into this as well. I tracked it down to the file permissions of Git's database. Some files are marked with read only permissions. The first converge is able to write the files and then subsequent converges hit the read-only permission and cause the copy to fail.

I was able to work-around it by including an Ansible task in my test playbook to change the file permissions on the copied git repo:

```
---
- hosts: all

  # Hacky workaround to deal with git repo file permissions being read only
  pre_tasks:
    - command: chmod -R u+w /tmp/kitchen/.git

  roles:
    - { role: "some-role" }
```

It might be nice to be able to exclude paths from the ssh `upload` [implementation](https://github.com/test-kitchen/test-kitchen/blob/5e4fa6baff5d51dc983be3f7b67ffe1bcbf2a8d2/lib/kitchen/transport/ssh.rb#L141). It doesn't appear that would be a simple change since `scp.upload` does not seem to offer [excludes path options](http://net-ssh.github.io/scp/v1/api/classes/Net/SCP.html#M000009). Given that I prefer the somewhat hacky ansible workaround over adding additional complexity to test-kitchen.
