### ISSUE TITLE
Is it possible to specify alternate user for all test-kitchen interaction with a vagrant/virtualbox host?

### ISSUE THREAD

**Issue by daxgames** [test-kitchen/test-kitchen#582]
I have a cookbook that installs software that MUST be able to do things as a REAL root user, sudo does not work.  I need to be able to specify 'username: root' in the .kitchen.yml and have that be used for all of kitchens interaction with the vagrant/virtualbox host.

Currently when I do this I do see root in the 'Vagrantfile' kitchen creates but when kitchen connects to the host it is using the following:

D      [SSH] vagrant@127.0.0.1:2222<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :keys_only=>true, :password=>"vagrant", :port=>"2222", :keys=>["/Users/daxgames/.vagrant.d/insecure_private_key"], :user=>"vagrant"}>

Is there any way to override this?

**Comment by jkleinlercher** [comment]
I have a similar concern. We are not allowed to run chef-client as root on a real machine and we want to have a similiar environment also with test-kitchen. So we need a way to start the chef-client during kitchen converge as a special non-root user.
Did you find a way to set the user in the meantime?

**Comment by trilitheus** [comment]
Hope this helps, I do this in the platforms stanza:
```
platforms:
  - name: centos-6.6
    driver:
      username: vagrant
      password: vagrant
```
Or you can pull in an environment variable if you don;t want to specify your password in the file
```
platforms:
  - name: centos-6.6
    driver:
      username: vagrant
      password: <%= ENV['A_PASSWORD'] %>
```
