### ISSUE TITLE
kitchen does not create needed interface. no errors

### ISSUE THREAD

**Issue by ror6ax** [test-kitchen/test-kitchen#621]
My kitchen.yml features this:

``` suites:
    - name: default
      network:
         - ["forwarded_port", {guest: 80, host: 8080}]
         - ["private_network", {ip: "192.168.1.10"}]
```

It results in your usual forwarding, no private network. What is worse, no errors, all green,
However if I get the whole network part into first driver declaraion, like this:

```

---
driver:
    name: vagrant
    network:
        - ["private_network",{ip: '192.168.1.10'}]
```

...it works fine, my interface is in place.
