### ISSUE TITLE
Unable to parse WinRM response, missing attribute quote

### ISSUE THREAD

**Issue by webframp** [test-kitchen/test-kitchen#635]
Running on Windows 7, using windows-guest-support branch of test-kitchen/test-kitchen@defb15bb0175db6391995957b7d671a89631bf14 and test-kitchen/kitchen-vagrant@feb5cd54c7dce83ef53dbb67c0f9729d2a08c488 to bring up a Server 2012r2 vm.

kitchen setup fails, here's the exception output:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [[Kitchen::Transport::Winrm] Unable to parse WinRM response: #<REXML::ParseException: missing attribute quote
Line: 102
Position: 4329
Last 80 unconsumed characters:
 <STYLE id=L_10>=Content-Type content="text/html; charset=UTF-8">
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:371:in `pull_event'
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rexml/parsers/treeparser.rb:22:in `parse'
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rexml/document.rb:283:in `build'
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rexml/document.rb:43:in `initialize'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:42:in `new'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:42:in `response_xml'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:61:in `raise_if_wsman_fault'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/http/transport.rb:50:in `send_request'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:421:in `send_message'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:126:in `open_shell'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:305:in `run_cmd'
F:/.chefdk/gem/ruby/2.0.0/gems/winrm-1.3.0/lib/winrm/winrm_service.rb:323:in `run_powershell_script'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/transport/winrm.rb:227:in `execute_with_exit'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/transport/winrm.rb:54:in `execute'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:68:in `block in converge'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/transport/base.rb:73:in `connection'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:67:in `converge'
F:/.chefdk/gem/ruby/2.0.0/gems/kitchen-vagrant-0.16.0/lib/kitchen/driver/vagrant.rb:88:in `converge'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `public_send'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `block in perform_action'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:442:in `call'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:442:in `synchronize_or_call'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:407:in `block in action'
C:/opscode/chefdk/embedded/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:406:in `action'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `perform_action'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:338:in `converge_action'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:318:in `block in transition_to'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:317:in `each'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:317:in `transition_to'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:149:in `setup'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
F:/.chefdk/gem/ruby/2.0.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
F:/.chefdk/gem/ruby/2.0.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
...
missing attribute quote
Line: 102
Position: 4329
Last 80 unconsumed characters:
 <STYLE id=L_10v=Content-Type content="text/html; charset=UTF-8">
Line: 102
Position: 4329
Last 80 unconsumed characters:
 <STYLE id=L_10 (502). using shell: [powershell] and command: [ $ProgressPreference='SilentlyContinue';
# @return True if chef path exist, False otherwise
function is_chef_installed { Test-Path /opscode/chef }

# @param $version the requested version of omnibus package
# @return True if omnibus needs to be installed, False otherwise
function should_update_chef($version) {
  if (-Not (is_chef_installed)) { return $true }

  try {
    $chef_version=(chef-solo -v).split(' ',2)[1]
  } catch [Exception] {
    $chef_version = ''
  }

  switch ($version) {
    { 'true', $chef_version -contains $_ } { return $false }
    'latest' { return $true }
    default { return $true }
  }
}

# @param $chef_url The url where we will download chef
# @param $chef_msi Temporal MSI path
function download_chef($chef_url, $chef_msi) {
  Write-Host -NoNewline "`r`tDownloading Chef..."
  $proxy = new-object System.Net.WebProxy
  $proxy.Address = $env:http_proxy
  $wc = new-object system.net.WebClient
  $wc.proxy = $proxy
  $wc.DownloadFile($chef_url, $chef_msi)
  Write-Host -NoNewline "`r`tDone!              "
}

# function to install chef with sort of a nice progress bar
function install_chef {
  $proc_msi = Start-Process -FilePath 'msiexec.exe' -ArgumentList "/qn /i $chef_msi" -Passthru
  $bar = ""
  while (-Not $proc_msi.HasExited ) {
    Write-Host -NoNewline "`r`t[MSI] [$bar"
    Start-Sleep 2
    $bar += "#"
  }

  if ($proc_msi.ExitCode -ne 0) {
    throw "msiexec was not successful. Received exit code $($proc_msi.ExitCode)"
  }
  rm -r $chef_msi
  Write-Host -NoNewline "`r`t[MSI] [$bar] Completed!
"
}

  $chef_msi = $env:systemdrive + "\chef.msi"

  If (should_update_chef true) {
    Write-Host "-----> Installing Chef Omnibus (true)
"
    download_chef "http://www.chef.io/chef/install.msi?" $chef_msi
    install_chef
  } else {
    Write-Host "-----> Chef Omnibus installation detected (true)
"
  }
]]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tyler-ball** [comment]
@fnichol just pushed a large change to the windows-guest-support branch that completely re-wrote this powershell downloader.  Can you try with the latest code in that branch and see if you're still seeing an issue?  If so, please re-open this.

And just to make sure I understand - you're running chefdk on a windows host, correct?

**Comment by webframp** [comment]
I gave this a try and wasn't able to get very far with the latest HEAD on windows-guest-support. I used latest for kitchent-vagrant and test-kitchen with chefdk on windows host, but it seemed like the winrm transport wasn't working. It's probably just something off in my config:

```
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2
  driver_config:
    box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
  transport:
    name: winrm
...
```
But it repeatedly timed out trying to ssh to the box.

I also work on os x and will try it there, also with latest chefdk.

**Comment by tyler-ball** [comment]
Can you try it without the
```
transport:
  name: winrm
```
I haven't tried running from a windows host, but I know others have done it successfully.  I'm going to try reaching out to some people.

**Comment by tyler-ball** [comment]
@btm Has used TK from a Windows host.  Can you post a sample of what your `.kitchen.yml` looks like?

**Comment by webframp** [comment]
I'll try it without that. I'm using the exact config from @mwrock here: http://www.hurryupandwait.io/blog/help-test-the-future-of-windows-infrastructure-testing-on-test-kitchen

**Comment by mwrock** [comment]
I have not tried on a windows host since @fnichol 's latest went through. Hoping to get to it tonight. However I do have that attribute in my `.kitchen.yml`s that I use from linux hosts and have not had a problem. Almost sounds to me like the latest bits are not running. just curious if you run a `kitchen list` do you see the `transport` and `verifier` columns?

Should be a table like this:
```
$ kitchen list
Instance                    Driver   Provisioner  Verifier  Transport  Last Action
middle-tier-windows-2012R2  Vsphere  Environment  Busser    Winrm      <Not Created>
ftp-windows-2012R2          Vsphere  Environment  Busser    Winrm      Set Up
```

**Comment by tyler-ball** [comment]
@webframp Can you post the contents of your `kitchen diagnose`?  Check it for secure passwords just in case any are in there.

**Comment by btm** [comment]
@webframp when you said "But it repeatedly timed out trying to ssh to the box." you meant winrm, not ssh, right?

As everything has moved to winrm 1.3 we're starting to see some issues that I've started attributing to winrm 1.3. I'm following @mwrock's blog to repro. It took a bit to get a working .kitchen.yml and I'm downloading @mwrock's box now. More work tomorrow.

**Comment by btm** [comment]
@ksubrama found a legitimate bug from my winrm 1.3 paranoia, might be related. :)

https://github.com/WinRb/WinRM/issues/131

**Comment by webframp** [comment]
@btm Nope. That's what had me stumped and assuming I made some mistake. I had transport set to Winrm, but it never forwarded Winrm ports and tries to ssh. 

I'll give it a try again from the windows host and see if I get the same result. I'm also just stepping through @mwrock's post since I have an interest in testing that particular cookbook he mentioned. 

@tyler-ball will post it tomorrow when I'm back at the windows machine.

**Comment by mwrock** [comment]
I just now tested for the first time on windows and vagrant since @fnichol 's recent pushes. I'm seeing the same issue as @webframp. Haven't troubleshooted yet and not sure I'll have time until later tonight but wanted to report my observation at least.

**Comment by mwrock** [comment]
here is the output of `kitchen diagnose`:
```
C:\dev\chef-minecraft [windows +0 ~1 -0]> kitchen diagnose
---
timestamp: '2015-03-20 15:16:32 UTC'
kitchen_version: 1.3.2.dev
instances:
  default-windows-2012R2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file: {}
    driver:
      box: mwrock/Windows2012R2
      box_check_update:
      box_url: https://wrock.blob.core.windows.net/vhds/hyperv2012r2.box
      box_version:
      customize: {}
      gui:
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      name: vagrant
      network: []
      password: vagrant
      pre_create_command:
      provider: hyperv
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/dev/chef-minecraft/test/integration
      username: vagrant
      vagrantfile_erb: C:/Users/Matt/.chefdk/gem/ruby/2.0.0/gems/kitchen-vagrant-0.16.0.dev/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: false
    provisioner:
      attributes:
        minecraft:
          accept_eula: true
      chef_client_path: $env:systemdrive\opscode\chef\bin\chef-client.bat
      chef_metadata_url: https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest
      chef_omnibus_install_options:
      chef_omnibus_root: $env:systemdrive\opscode\chef
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: C:/dev/chef-minecraft
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      require_chef_omnibus: true
      roles_path:
      root_path: $env:TEMP\kitchen
      ruby_bindir: $env:systemdrive\opscode\chef\embedded\bin
      run_list:
      - recipe[minitest-handler]
      - recipe[minecraft]
      sudo:
      test_base_path: C:/dev/chef-minecraft/test/integration
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: C:/dev/chef-minecraft/test/integration
      username: .\administrator
    verifier:
      busser_bin: $env:TEMP\verifier\bin\busser.bat
      http_proxy:
      https_proxy:
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      name: busser
      root_path: $env:TEMP\verifier
      ruby_bindir: $env:systemdrive\opscode\chef\embedded\bin
      sudo:
      suite_name: default
      test_base_path: C:/dev/chef-minecraft/test/integration
      version: busser
  default-ubuntu-1204:
    platform:
      os_type: unix
      shell_type: bourne
    state_file: {}
    driver:
      box: hashicorp/precise64
      box_check_update:
      box_url:
      box_version:
      customize: {}
      gui:
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      name: vagrant
      network: []
      password:
      pre_create_command:
      provider: hyperv
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/dev/chef-minecraft/test/integration
      username:
      vagrantfile_erb: C:/Users/Matt/.chefdk/gem/ruby/2.0.0/gems/kitchen-vagrant-0.16.0.dev/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-ubuntu-1204
    provisioner:
      attributes:
        minecraft:
          accept_eula: true
      chef_client_path: /opt/chef/bin/chef-client
      chef_metadata_url:
      chef_omnibus_install_options:
      chef_omnibus_root: /opt/chef
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: C:/dev/chef-minecraft
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      require_chef_omnibus: true
      roles_path:
      root_path: /tmp/kitchen
      ruby_bindir: /opt/chef/embedded/bin
      run_list:
      - recipe[ubuntu]
      - recipe[minitest-handler]
      - recipe[minecraft]
      sudo: true
      test_base_path: C:/dev/chef-minecraft/test/integration
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      test_base_path: C:/dev/chef-minecraft/test/integration
      username: root
    verifier:
      busser_bin: /tmp/verifier/bin/busser
      http_proxy:
      https_proxy:
      kitchen_root: C:/dev/chef-minecraft
      log_level: :info
      name: busser
      root_path: /tmp/verifier
      ruby_bindir: /opt/chef/embedded/bin
      sudo: true
      suite_name: default
      test_base_path: C:/dev/chef-minecraft/test/integration
      version: busser
```

**Comment by mwrock** [comment]
looks like adding `kitchen-vagrant` in the `windows-guest-support` branch is no longer setting the vagrant `communicator` to the kitchen `transport`. 

Adding a `communicator` to the config fixes this:

```
platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2
    box_url: https://wrock.blob.core.windows.net/vhds/hyperv2012r2.box
    vm_hostname: false
    communicator: winrm
  transport:
    name: winrm
```

In this minecraft cookbook I'm getting cookbook resolution errors but I tend to think thats unrelated.

@fnichol maybe we covered this in a standup and I missed it. Is this intentional? Changing transport to communicator?

**Comment by webframp** [comment]
likewise, here's my diagnose output:

```
---
timestamp: '2015-03-20 16:57:34 UTC'
kitchen_version: 1.3.2.dev
instances:
  default-windows-2012R2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 127.0.0.1
      password: vagrant
      username: vagrant
    driver:
      box: opscode-windows-2012R2
      box_check_update: 
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      box_version: 
      customize: {}
      gui: 
      kitchen_root: C:/src/cookbook-appserver
      log_level: :info
      name: vagrant
      network: []
      password: vagrant
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: C:/src/cookbook-appserver/test/integration
      username: vagrant
      vagrantfile_erb: F:/.chefdk/gem/ruby/2.0.0/gems/kitchen-vagrant-0.16.0.dev/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: 
    provisioner:
      attributes: {}
      chef_client_path: $env:systemdrive\opscode\chef\bin\chef-client.bat
      chef_metadata_url: https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest
      chef_omnibus_install_options: 
      chef_omnibus_root: $env:systemdrive\opscode\chef
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: C:/src/cookbook-appserver
      log_file: 
      log_level: :info
      name: chef_zero
      nodes_path: 
      require_chef_omnibus: true
      roles_path: 
      root_path: $env:TEMP\kitchen
      ruby_bindir: $env:systemdrive\opscode\chef\embedded\bin
      run_list:
      - recipe[appserver::default]
      sudo: 
      test_base_path: C:/src/cookbook-appserver/test/integration
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: C:/src/cookbook-appserver
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: 
      port: 5985
      rdp_port: 3389
      test_base_path: C:/src/cookbook-appserver/test/integration
      username: .\administrator
    verifier:
      busser_bin: $env:TEMP\verifier\bin\busser.bat
      http_proxy: 
      https_proxy: 
      kitchen_root: C:/src/cookbook-appserver
      log_level: :info
      name: busser
      root_path: $env:TEMP\verifier
      ruby_bindir: $env:systemdrive\opscode\chef\embedded\bin
      sudo: 
      suite_name: default
      test_base_path: C:/src/cookbook-appserver/test/integration
      version: busser
```

**Comment by webframp** [comment]
I'll give it a try with an adjusted driver config: 
```yml
    driver_config:
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      vm_hostname: false
      communicator: winrm
```

**Comment by fnichol** [comment]
Hey all, the only place that `communicator: winrm` gets used is during the `vagrant up --no-provision` (in `kitchen create`) and `vagrant destroy --force` (in `kitchen destroy`). It's how Vagrant determines whether to SSH into the Vagrant VM or use WinRM. While `:communicator` is an option you can set in kitchen-vagrant (windows-guest-support branch), this was added previously and should **not** be required.

I've been using Vagrant Windows base boxes built from https://github.com/boxcutter/windows which correctly set the following defaults:

* `config.vm.communicator = "winrm"` - tells Vagrant to communicate over WinRM (not SSH)
* `config.vm.guest = "windows"` - tells Vagrant that the Guest is Windows based for shared folders, setting network things, etc.
* `config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct:true` - sets up the WinRM port forwarding (which isn't even strictly necessary for kitchen-vagrant these days)

This means that the .kitchen.yml from the Windows cookbook should work with no additional config needed: https://github.com/opscode-cookbooks/windows/blob/master/.kitchen.yml. That's assuming that `vagrant box list` returns you a box called "windows-8.1"--the box URL probably isn't working.

If the Vagrant basebox isn't set up with `config.vm.communicator = "winrm"` then Vagrant is going to boot the VM via SSH, not WinRM.

As for Test Kitchen, once the Vagrant VM has booted, Test Kitchen treats the VM as a vanilla remote host and talks WinRM if the `"winrm"` Transport is asked for like this, which sets the winrm Transport for all instances:

```yaml
---
transport:
  name: winrm
```

---

Finally, the kitchen-vagrant code on the windows-guest-support branch sets `:vm_hostname` to `nil` by default if your platform name starts with `/^windows/`, meaning that setting it explicitly shouldn't be necessary.

If any of this proves false however, then it shall be fixed :smile:
