### ISSUE TITLE
test-kitchen/lib/kitchen/provisioner/chef/powershell_shell.rb expand_version fails if behind proxy and http_proxy is set

### ISSUE THREAD

**Issue by daxgames** [test-kitchen/test-kitchen#638]
My work network requires the use of a proxy.  When on that network we have http/https_proxy environment setup where we are running test kitchen.  kitchen converge fails with the below output when calling test-kitchen/lib/kitchen/provisioner/chef/powershell_shell.rb expand_version method.

```
D      Cleaning up local sandbox in /var/folders/pj/9nx2vrjd0qd01jsybjbkvnn80000gn/T/win2k12-ge-win-services-w2k12-sandbox-20150315-48963-obyjia
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [getaddrinfo: nodename nor servname provided, or not known (http://www.chef.io:80)]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [getaddrinfo: nodename nor servname provided, or not known (http://www.chef.io:80)]
D      ---Nested Exception---
D      Class: SocketError
D      Message: getaddrinfo: nodename nor servname provided, or not known (http://www.chef.io:80)
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `initialize'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `new'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `create_socket'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:747:in `block in connect'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/powershell_shell.rb:131:in `expand_version'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/powershell_shell.rb:93:in `install_function'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_base.rb:165:in `chef_install_function'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_base.rb:94:in `install_command'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:68:in `block in converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/transport/base.rb:73:in `connection'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/base.rb:67:in `converge'
D      /Users/daxgames/.chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-0.16.0/lib/kitchen/driver/vagrant.rb:82:in `converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `block in perform_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:442:in `call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:442:in `synchronize_or_call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:407:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:406:in `action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:378:in `perform_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:338:in `converge_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:318:in `block in transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:317:in `each'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:317:in `transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:138:in `converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D      ----------------------
```
If I connect to a network where proxy is not required and unset the http/https_proxy variables it works fine.

**Comment by afiune** [comment]
@daxgames Thank you for the feedback! Here is the proxy implementation when we une omnibus to install chef. 

https://github.com/test-kitchen/test-kitchen/commit/3180a069ad99cbe358fa26cb0ff972716f1248a3

Could you share your `.kitchen.yml`?

We will try to look at your configuration in detail. Thanks! :smile:

**Comment by daxgames** [comment]
```
---
driver_plugin: vagrant

driver_config:
  customize:
    natdnshostresolver1: 'on'

transport:
  name: winrm
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['http_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>

provisioner:
  name: chef_zero
  client_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    no_lazy_load: true

platforms:
- name: ge-win-services-w2k12
  provisioner:
    name: chef_zero
    data_path: test/shared_windows
  driver_config:
    box: ge-win2012-r2-std
    box_url: http://acusvinolare001.frictionless.capital.ge.com/virtualbox/ge-win2012-r2-std.box
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    network:
    - [ "forwarded_port", { guest: 3389, host: 3389, id: rdp, auto_correct: true } ]
    vm_hostname: TRSTWPRTSTAPV99
    gui: true
    customize:
      memory: 2048
      clipboard: bidirectional
      draganddrop: bidirectional

- name: ge-win-services-w2k8
  provisioner:
    name: chef_zero
    data_path: test/shared_windows
  driver_config:
    box: ge_windows2008r2
    box_url: http://acusvinolare001.frictionless.capital.ge.com/virtualbox/ge_windows2008r2.box
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    network:
    - [ "forwarded_port", { guest: 3389, host: 3389, id: rdp, auto_correct: true } ]
    vm_hostname: CMFALGAPRWTSTV99
    gui: true
    customize:
      memory: 2048
      clipboard: bidirectional
      draganddrop: bidirectional

suites:
- name: win2k12
  run_list:
  - recipe[ge_win_services]
  attributes: {}
  excludes:
    - ge-win-services-w2k8
- name: win2k8
  run_list:
  - recipe[ge_win_services]
  attributes: {}
  excludes:
    - ge-win-services-w2k12
```

**Comment by fnichol** [comment]
@daxgames Hi there! Could I get you to try upgrading to the latest 1.4.0.beta.* (or later) releases and re-try? I've tried to make the HTTP proxy support better, including additionally setting `$env:HTTP_PROXY` and `$env:HTTPS_PROXY` (the uppercase versions).

I also thought I should point out that we don't currently use/support the `:no_proxy` option, although that seems like a really, really useful thing.

Thank you!

**Comment by daxgames** [comment]
Trying it today, will let you know.  Thanks for the heads up on the
no_proxy.  We do have a use case for it where some devs have setup a local
squid proxy to further speedup converges with large download requirements
and we do not want to proxy to proxy those requests.  As a workaround I
also ad those direct to the client.rb using the .kitchen.yml.  Hope to see
you at Chef.Conf

Dax

On Sun, March 29, 2015 5:11 pm, Fletcher Nichol wrote:
> @daxgames Hi there! Could I get you to try upgrading to the latest
> 1.4.0.beta.* (or later) releases and re-try? I've tried to make the HTTP
> proxy support better, including additionally setting `$env:HTTP_PROXY`
> and `$env:HTTPS_PROXY` (the uppercase versions).
>
> I also thought I should point out that we don't currently use/support the
> `:no_proxy` option, although that seems like a really, really useful
> thing.
>
> Thank you!
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/test-kitchen/test-kitchen/issues/638#issuecomment-87487
> 564


-- 
Dax

**Comment by daxgames** [comment]
It is trying to ssh to the windows box and dying at :+1: 

```
==> default: Setting hostname...
       The following SSH command responded with a non-zero exit status.
       Vagrant assumes that this means the command failed!

       hostname -f

       Stdout from the command:



       Stderr from the command:

       sh: sudo: command not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ge_windows2008r2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: kitchen-ge_win_secedit-windows-kitchen-win-secedit-w2k8r2_default_1427736535081_4668
==> default: Fixed port collision for 3389 => 3389. Now on port 2203.
==> default: Fixed port collision for 22 => 2222. Now on port 2204.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 => 2203 (adapter 1)
    default: 22 => 2204 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2204
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.18
    default: VirtualBox Version: 4.3
==> default: Setting hostname...
STDERR: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sh: sudo: command not found
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by daxgames** [comment]
Actually I was working with the wrong recipe.  Now I am getting: 

win_services - master $> kitchen create
-----> Starting Kitchen (v1.4.0.dev)
-----> Starting Kitchen (v1.4.0.dev)
-----> Starting Kitchen (v1.4.0.dev)
       ==> default: Importing base box 'win2012-r2-std'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen_win_services-win2k12-ge-win-services-w2k12_default_1427737928267_84499
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 => 3389 (adapter 1)
           default: 22 => 2222 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...    default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection timeout. Retrying...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
           default: The guest additions on this VM do not match the installed version of
           default: VirtualBox! In most cases this is fine, but in rare cases it can
           default: prevent things such as shared folders from working properly. If you see
           default: shared folder errors, please make sure the guest additions within the
           default: virtual machine match the version of VirtualBox you have installed on
           default: your host and reload your VM.
           default:
           default: Guest Additions Version: 4.2.16
           default: VirtualBox Version: 4.3
       ==> default: Setting hostname...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds
       Waiting for WinRM service on http://127.0.0.1:5985/wsman, retrying in 3 seconds

**Comment by fnichol** [comment]
@daxgames Hey there, it's looking like Vagrant is trying to bring up win2012-r2-std but hasn't port forwarded a WinRM port back. It also appears to be using Vagrant's internal SSH Communicator to boot the VM. Does this Vagrant base box have a Vagrantfile template in it setting `vm.guest = "windows"` and `vm.communicator`? You can check by looking under `~/.vagrant.d/boxes/win2012-r2-std/` for a Vagrantfile (it may be under further sub-directories).

You can try to to override the base box's defaults yourself in a `.kitchen.yml` with:

```yaml
---
driver:
  name: vagrant

platforms:
  - name: win2012-r2-std
    driver:
      guest: windows
      communicator: winrm
```

Projects like [boxcutter/windows](https://github.com/boxcutter/windows/) set these 2 settings automatically [automatically](https://github.com/boxcutter/windows/blob/master/tpl/vagrantfile-win2012r2-standard.tpl#L9-L14).

You can see if it's the Vagrant base base box that is the issue by creating an empty project directory, running `vagrant init win2012-r2-std` and then calling `vagrant up`. If Vagrant can't boot it with its defaults, Test Kitchen won't be able to either.

Does that help? Thanks for getting back to us!

**Comment by daxgames** [comment]
Below is the Vagrantfile for the box...

```
Vagrant::Config.run do |config|
  # This Vagrantfile is auto-generated by `vagrant package` to contain
  # the MAC address of the box. Custom configuration should be placed in
  # the actual `Vagrantfile` in this box.
  config.vm.base_mac = "0800273440F3"
end

# Load include vagrant file if it exists after the auto-generated
# so it can override any of the settings
include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
```

I will try the .kitchen.yml setings you recommended to see if they help.

**Comment by daxgames** [comment]
Got farther but still failing.  I have not tried to figure out why this is breaking just trying to provide you with as much feedback as possible:

.kitchen.yml file

```
---
driver_plugin: vagrant

driver_config:
  # require_chef_omnibus: 11.16.4
  customize:
    natdnshostresolver1: 'on'

transport:
  name: winrm
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['http_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>

provisioner:
  name: chef_zero
  client_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    no_lazy_load: true

platforms:
- name: win-services-w2k12
  driver:
    guest: windows
    communicator: winrm
  provisioner:
    name: chef_zero
    data_path: test/shared_windows
  driver_config:
    box: win2012-r2-std
    box_url: http://host/virtualbox/win2012-r2-std.box
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    vm_hostname: TRSTWPRTSTAPV99
    gui: true
    customize:
      memory: 2048
      clipboard: bidirectional
      draganddrop: bidirectional

- name: win-services-w2k8
  driver:
    guest: windows
    communicator: winrm
  provisioner:
    name: chef_zero
    data_path: test/shared_windows
  driver_config:
    box: windows2008r2
    box_url: http://host/virtualbox/windows2008r2.box
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    gui: true
    customize:
      memory: 2048
      clipboard: bidirectional
      draganddrop: bidirectional

suites:
- name: win2k12
  run_list:
  - recipe[win_services]
  attributes: {}
  excludes:
    - win-services-w2k8
- name: win2k8
  run_list:
  - recipe[ge_win_services]
  attributes: {}
  excludes:
    - win-services-w2k12

```

Generated Vagrantfile

```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2012-r2-std"
  c.vm.box_url = "http://host/virtualbox/win2012-r2-std.box"
  c.vm.hostname = "TRSTWPRTSTAPV99"
  c.vm.communicator = "winrm"
  c.vm.guest = "windows"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.gui = true
    p.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    p.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end
end
```

Error
```
$$$$$$ The command line is too long.                                                                                                                                                            [183/2657]
>>>>>> Converge failed on instance <win2k12-win-services-w2k12>.
>>>>>> Please see .kitchen/logs/win2k12-win-services-w2k12.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [sh -c '
http_proxy="http://x.x.x.x:3128"; export http_proxy
HTTP_PROXY="http://x.x.x.x:3128"; export HTTP_PROXY
https_proxy="http://x.x.x.x:3128"; export https_proxy
HTTPS_PROXY="http://x.x.x.x:3128"; export HTTPS_PROXY
chef_omnibus_root="/opt/chef"
chef_omnibus_url="https://www.chef.io/chef/install.sh"
install_flags=""
pretty_version="install only if missing"
sudo_sh="sudo -E sh"
version="true"

tmp_stderr="/tmp/stderr";

# capture_tmp_stderr SOURCE
capture_tmp_stderr() {
  # spool up $tmp_stderr from all the commands we called
  if test -f "$tmp_stderr"; then
    output="`cat $tmp_stderr`";
    stderr_results="${stderr_results}\nSTDERR from $1:\n\n${output}\n";
    rm $tmp_stderr;
  fi
}

# do_curl URL FILENAME
do_curl() {
  echo "Trying curl...";
  curl -sL -D "$tmp_stderr" "$1" > "$2";
  ec=$?;
  # check for 404
  grep "404 Not Found" "$tmp_stderr" 2>&1 >/dev/null;
  if test $? -eq 0; then
    http_404_error "$1";
  fi

  # check for bad return status or empty output
  if test $ec -ne 0 || test ! -s "$2"; then
    capture_tmp_stderr "curl";
    return 1;
  else
    echo "Download complete.";
    return 0;
  fi
}

# do_download URL FILENAME
do_download() {
  echo "Downloading ${1} to file ${2}";

  exists wget;
  if test $? -eq 0; then
    do_wget "$1" "$2" && return 0;
  fi

  exists curl;
  if test $? -eq 0; then
    do_curl "$1" "$2" && return 0;
  fi

  exists fetch;
  if test $? -eq 0; then
    do_fetch "$1" "$2" && return 0;
  fi

  exists python;
  if test $? -eq 0; then
    do_python "$1" "$2" && return 0;
  fi

  exists perl;
  if test $? -eq 0; then
    do_perl "$1" "$2" && return 0;
  fi

  unable_to_download "$1" "$2";
}

# do_fetch URL FILENAME
do_fetch() {
  echo "Trying fetch...";
  fetch -o "$2" "$1" 2>"$tmp_stderr";
  ec=$?;
  # check for 404
  grep "Not Found" "$tmp_stderr" 2>&1 >/dev/null;
  if test $? -eq 0; then
    http_404_error "$1";
  fi

  # check for bad return status or empty output
  if test $ec -ne 0 || test ! -s "$2"; then
    capture_tmp_stderr "fetch";
    return 1;
  else
    echo "Download complete.";
    return 0;
  fi
}

# do_perl URL FILENAME
do_perl() {
  echo "Trying perl...";
  perl -e "use LWP::Simple; getprint(\$ARGV[0]);" "$1" > "$2" 2>"$tmp_stderr";
  ec=$?;
  # check for 404
  grep "404 Not Found" "$tmp_stderr" 2>&1 >/dev/null;
  if test $? -eq 0; then
    http_404_error "$1";
  fi

  # check for bad return status or empty output
  if test $ec -ne 0 || test ! -s "$2"; then
    capture_tmp_stderr "perl";
    return 1;
  else
    echo "Download complete.";
    return 0;
  fi
}

# do_python URL FILENAME
do_python() {
  echo "Trying python...";
  python -c "import sys,urllib2 ; sys.stdout.write(urllib2.urlopen(sys.argv[1]).read())" "$1" > "$2" 2>"$tmp_stderr";
  ec=$?;
  # check for 404
  grep "HTTP Error 404" "$tmp_stderr" 2>&1 >/dev/null;
  if test $? -eq 0; then
    http_404_error "$1";
  fi

  # check for bad return status or empty output
  if test $ec -ne 0 || test ! -s "$2"; then
    capture_tmp_stderr "python";
    return 1;
  else
    echo "Download complete.";
    return 0;
  fi
}

# do_wget URL FILENAME
do_wget() {
  echo "Trying wget...";
  wget -O "$2" "$1" 2>"$tmp_stderr";
  ec=$?;
  # check for 404
  grep "ERROR 404" "$tmp_stderr" 2>&1 >/dev/null;
  if test $? -eq 0; then
    http_404_error "$1";
  fi

  # check for bad return status or empty output
  if test $ec -ne 0 || test ! -s "$2"; then
    capture_tmp_stderr "wget";
    return 1;
  else
    echo "Download complete.";
    return 0;
  fi
}

# exists COMMAND
exists() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0;
  else
    return 1;
  fi
}

# http_404_error URL
http_404_error() {
  echo ">>>>>> Downloading ${1} resulted in an HTTP/404, aborting";
  exit 40;
}

# should_update_chef ROOT VERSION
should_update_chef() {
  if test ! -d "$1"; then
    return 0;
  elif test "$2" = "true"; then
    return 1;
  elif test "$2" = "latest"; then
    return 0;
  fi

  chef_version="`${1}/bin/chef-solo -v | cut -d \" \" -f 2`";

  echo "$chef_version" | grep "^${2}" 2>&1 >/dev/null;
  if test $? -eq 0; then
    return 1;
  else
    return 0;
  fi
}

# unable_to_download URL FILE
unable_to_download() {
  echo "Unable to download $1 to $2, aborting";

  if test "x${stderr_results}" != "x"; then
    echo "\nDEBUG OUTPUT FOLLOWS:\n${stderr_results}";
  fi

  exit 10;
}

# main
main() {
  should_update_chef "$chef_omnibus_root" "$version"
  if test $? -eq 0; then
    echo "-----> Installing Chef Omnibus (${pretty_version})";

    # solaris 10 lacks recent enough credentials, so http url is used
    platform="`/usr/bin/uname -s 2>/dev/null`";
    platform_version="`/usr/bin/uname -r 2>/dev/null`";
    if test "x${platform}" = "xSunOS" && test "x${platform_version}" = "x5.10"; then
      chef_omnibus_url=`echo "$chef_omnibus_url" | sed -e "s/https/http/"`;
    fi

    do_download "$chef_omnibus_url" /tmp/install.sh;
    $sudo_sh /tmp/install.sh $install_flags;
  else
    echo "-----> Chef Omnibus installation detected (${pretty_version})";
  fi
}

# augment path in an attempt to find a download program
PATH="${PATH}:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/sfw/bin";
export PATH;

main
']
>>>>>> ----------------------
```
