### ISSUE TITLE
Additional platforms in global/local configs don't get merged

### ISSUE THREAD

**Issue by mconigliaro** [test-kitchen/test-kitchen#650]
I have a global config (`~/.kitchen/config.yml`) like this:

```
platforms:
  - name: aws
    driver:
      name: ec2
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      aws_ssh_key_id: mike
      ssh_key: <%= ENV['HOME'] %>/.ssh/mike.pem
      region: <%= ENV['AWS_DEFAULT_REGION'] %>
      availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>a
      flavor_id: t2.micro
      image_id: ami-6889d200
      username: ubuntu
```

I was hoping this would automagically create an aws platform in all my cookbooks, but these options don't seem to get merged the way I expected. FWIW, the driver options do seem to get merged. For example:

```
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: mike
  ssh_key: <%= ENV['HOME'] %>/.ssh/mike.pem
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>a
  flavor_id: t2.micro
  image_id: ami-6889d200
  username: ubuntu
```

The only problem is now I need to go to all my cookbooks and manually add an aws platform with the driver overridden:

```
platforms:
  - name: aws
    driver:
      name: ec2
```

Also, additional platforms in a `.kitchen.local.yml` seem to completely overwrite the platforms in a `.kitchen.yml` file.
