### ISSUE TITLE
Windows 7 fails with 'maximum number of 15 concurrent operations' on second converge

### ISSUE THREAD

**Issue by amaltson** [test-kitchen/test-kitchen#656]
When I converge my Windows 7 box more than once, I get the following exception.

```
$ KITCHEN_LOCAL_YAML=.kitchen.windows.yml bundle exec kitchen converge
-----> Starting Kitchen (v1.4.0.beta.2)
-----> Converging <default-windows-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-windows-7>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [[WSMAN ERROR CODE: 2150859174]: <f:WSManFault Code='2150859174' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The WS-Management service cannot process the request. This user is allowed a maximum number of 15 concurrent operations, which has been exceeded. Close existing operations for this user, or raise the quota for this user. </f:Message></f:WSManFault>]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I'm using the following `.kitchen.windows.yml` file:

```yaml
---
driver:
  forward_agent: yes
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: windows-7
    transport:
      name: winrm
    driver:
      box: win7x64-enterprise-chef
      require_chef_omnibus: false

suites:
  - name: default
    run_list:
      - recipe[<our recipe>]
```

The workaround so far has been to open up a prompt in the Windows Vagrant box after it's booted up and execute:

```
> winrm set winrm/config/winrs '@{MaxProcessesPerShell="100"}'
```

As per #565, @fnichol mentioned "That could be a bug in the CommandExecutor which should recycle remote shells."
