### ISSUE TITLE
Chef-Solo cache deleted by WinRM transport

### ISSUE THREAD

**Issue by ozenhaman** [test-kitchen/test-kitchen#680]
Hi there,
I noticed that under default configuration, the WinRM transport deletes the destination folder into which it extracts files. By default, this folder is **'/tmp/kitchen'** (provisioner[:root_path]).
The Chef-Solo cache folder is **'/tmp/kitchen/cache'** by default. I believe this is also true for Chef-Client.
When the transport deletes the destination folder, the cache goes away with it.
 
My workaround was to move the cache outside of /tmp/kitchen in .kitchen.yml:
```yaml
  provisioner:
    name: chef_solo
    solo_rb:
      file_cache_path: *anything outside of /tmp/kitchen*
```
I suppose a reasonable solution would be for the transport to extract files elsewhere?

Thanks,
-Omer
