### ISSUE TITLE
Share a test suite with other test suites to support multiple run lists efficiently

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#692]
Hi, 
I want to 
     - run multiple run lists and verify the system for each convergence,
     - share the converged system with other test suites to save time and code complexity.

For example, when we test (1) Java installation, (2) tomcat installation, (3) Derby installation, and (4) application deployment, I would like write `.kitchen.yml` like below.

```
suites:
  - name: java_suite
    run_list:
      - recipe[my_java_cookbook]

  - name: tomcat_suite
    run_list:
      - recipe[my_tomcat_cookbook]
    depends: [java_suite]

  - name: derby_suite
    run_list:
      - recipe[my_derby_cookbook]
    depends: [java_inst]

  - name: app_inst
    run_list:
      - recipe[my_war_cookbook]
    depends: [tomcat_suite, derby_suite]
```

Then test-kitchen can be aware of that the converged box of `java_suite` can be reused with `tomcat_suite` and `derby_suite`. The installation of chef, and Java can be skipped.

To test application deployment, test-kitchen starts with the converged box of `tomcat_suite`, and run the run list in `derby_suite`, and finally run the recipe `my_war_cookbook`. 

This behavior is similar to Rake. I think we can develop this easily by wrapping existing test-suite related code by Rake task.

Multiple run lists support and multiple verifications are also discussed in [162](https://github.com/test-kitchen/test-kitchen/issues/162), [534](https://github.com/test-kitchen/test-kitchen/issues/534), [561](https://github.com/test-kitchen/test-kitchen/issues/561), and [564](https://github.com/test-kitchen/test-kitchen/pull/564). I totally agree with introducing multiple run lists and verifications.

I hope my idea can be a good discussion item.
