### ISSUE TITLE
Unable to run kitchen converge: Server 2012 R2 - WinRM

### ISSUE THREAD

**Issue by djenriquez** [test-kitchen/test-kitchen#695]
I'm able to successfully complete ```kitchen create``` but fails on ```kitchen converge``` with error message:

```
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Converging <default-windows-2012R2>...
$$$$$$ Running legacy converge for 'Vagrant' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
$$$$$$ [WinRM] connection failed, terminating (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Bad HTTP response returned from server ().]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

My Windows Server 2012 R2 box was built with Packer with the help of [joefitzgerald/packer-windows](https://github.com/joefitzgerald/packer-windows). The only modification i made to this process was added an autounattend command to disable windows firewall completely, and added a MSDN iso + product key.

.kitchen.yml
```ruby
driver:
  forward_agent: yes
  name: vagrant
  network:
    - ["forwarded_port", {guest: 5985, host: 5985}]
    - ["private_network", {ip: "192.168.250.250"}]

transport:
  name: winrm
  password: vagrant
  username: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2
  driver_config:
    box: WindowsServ2012R2 
    vm_hostname: false

suites:
  - name: default
    run_list:
      recipe[djiis::default]
```

Generated Vagrantfile
```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "WindowsServ2012R2"
  c.vm.network(:forwarded_port, {:guest=>5985, :host=>5985})
  c.vm.network(:private_network, {:ip=>"192.168.250.250"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
```

```kitchen diagnose --all```
```
timestamp: 2015-04-17 08:30:46 UTC
kitchen_version: 1.3.1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/Users/djenriquez/chef-repo/cookbooks/djiis/.kitchen.yml"
    raw_data:
      driver:
        forward_agent: true
        name: vagrant
        network:
        - - forwarded_port
          - guest: 5985
            host: 5985
        - - private_network
          - ip: 192.168.250.250
      transport:
        name: winrm
        password: vagrant
        username: vagrant
      provisioner:
        name: chef_zero
      platforms:
      - name: windows-2012R2
        driver_config:
          box: WindowsServ2012R2
          vm_hostname: false
      suites:
      - name: default
        run_list: recipe[djiis::default]
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        forward_agent: true
        name: vagrant
        network:
        - - forwarded_port
          - guest: 5985
            host: 5985
        - - private_network
          - ip: 192.168.250.250
      transport:
        name: winrm
        password: vagrant
        username: vagrant
      provisioner:
        name: chef_zero
      platforms:
      - name: windows-2012R2
        driver_config:
          box: WindowsServ2012R2
          vm_hostname: false
      suites:
      - name: default
        run_list: recipe[djiis::default]
instances:
  default-windows-2012R2:
    state_file: {}
    driver:
      box: WindowsServ2012R2
      box_check_update: 
      box_url: 
      box_version: 
      customize: {}
      forward_agent: true
      gui: 
      kitchen_root: "/Users/djenriquez/chef-repo/cookbooks/djiis"
      log_level: :info
      name: vagrant
      network:
      - - forwarded_port
        - guest: 5985
          host: 5985
      - - private_network
        - ip: 192.168.250.250
      port: 22
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      sudo: true
      synced_folders: []
      test_base_path: "/Users/djenriquez/chef-repo/cookbooks/djiis/test/integration"
      vagrantfile_erb: "/Users/djenriquez/.chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-0.16.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: false
    provisioner:
      attributes: {}
      chef_client_path: "/opt/chef/bin/chef-client"
      chef_omnibus_install_options: 
      chef_omnibus_root: "/opt/chef"
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      json_attributes: true
      kitchen_root: "/Users/djenriquez/chef-repo/cookbooks/djiis"
      log_file: 
      log_level: :info
      name: chef_zero
      nodes_path: 
      require_chef_omnibus: true
      roles_path: 
      root_path: "/tmp/kitchen"
      ruby_bindir: "/opt/chef/embedded/bin"
      run_list:
      - recipe[djiis::default]
      sudo: true
      test_base_path: "/Users/djenriquez/chef-repo/cookbooks/djiis/test/integration"
    busser:
      busser_bin: "/tmp/busser/bin/busser"
      kitchen_root: "/Users/djenriquez/chef-repo/cookbooks/djiis"
      root_path: "/tmp/busser"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      suite_name: default
      test_base_path: "/Users/djenriquez/chef-repo/cookbooks/djiis/test/integration"
      version: busser
```

**Comment by djenriquez** [comment]
Tried a pretty barebone .kitchen.yml. Failed on ```kitchen converge``` as well.

Also, when removing ```vm_hostname: false``` from the ```platform: driver_config:```, the time it takes kitchen create to execute goes from ~5 minutes to 20 minutes, is this normal?

```
driver:
  forward_agent: yes
  name: vagrant

transport:
  name: winrm
  password: vagrant
  username: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2
  driver_config:
    box: WindowsServ2012R2 

suites:
  - name: default
    run_list:
      recipe[djiis::default]
```

**Comment by daxgames** [comment]
I have seen this on initial converge, it works for me on a re-converge.

kitchen destroy ; kitchen converge ; kitchen converge

**Comment by djenriquez** [comment]
Thanks for the reply @daxgames , unfortunately, that still did not work for me. Here is the result:

```
DJs-MacBook-Pro-2:djiis djenriquez$ kitchen destroy; kitchen converge; kitchen converge
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Destroying <default-windows-2012R2>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-windows-2012R2> destroyed.
       Finished destroying <default-windows-2012R2> (0m16.67s).
-----> Kitchen is finished. (0m19.31s)
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Creating <default-windows-2012R2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'WindowsServ2012R2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-djiis-default-windows-2012R2_default_1429637325052_88137
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 3389 => 3389 (adapter 1)
           default: 22 => 2222 (adapter 1)
           default: 5985 => 5985 (adapter 1)
           default: 5985 => 55985 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Configuring and enabling network interfaces...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       Vagrant instance <default-windows-2012R2> created.
       Finished creating <default-windows-2012R2> (6m11.56s).
-----> Converging <default-windows-2012R2>...
$$$$$$ Running legacy converge for 'Vagrant' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
$$$$$$ [WinRM] connection failed, terminating (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Bad HTTP response returned from server ().]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

-----> Starting Kitchen (v1.4.0.rc.1)
-----> Converging <default-windows-2012R2>...
$$$$$$ Running legacy converge for 'Vagrant' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
$$$$$$ [WinRM] connection failed, terminating (#<WinRM::WinRMHTTPTransportError: Bad HTTP response returned from server ().>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Bad HTTP response returned from server ().]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tyler-ball** [comment]
Hey @djenriquez - it looks like you have some out of date dependencies.  At the very top kitchen outputs that it is using TK 1.4.0.rc.1, but the `kitchen diagnose` outputs version `1.3.1`.

Can you try installing the latest version of the ChefDK and try again?  This has the latest version of Test Kitchen and kitchen-vagrant.  This should remove the `$$$$$$ Running legacy converge for 'Vagrant' Driver` warning you see at the beginning of your run.

When you update your ChefDK, try moving the `.chefdk` folder inside your home dir to `.old.chefdk`.  This is where gems get installed to when you run `chef gem install` and this could be loading old gems into your environment.

I also use the `joefitzgerald/packer-windows` definitions to roll my Windows images, so I don't think thats an issue.

Here is a slimmer `.kitchen.yml` that _should_ work for Windows:

```yaml
driver:
  name: vagrant

transport:
  password: vagrant
  username: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2
  driver_config:
    box: WindowsServ2012R2 

suites:
  - name: default
    run_list:
      recipe[djiis::default]
```

You shouldn't need the `forward_agent` config in the latest version of kitchen-vagrant, and the transport will be defaulted to `winrm` because your platform name starts with `windows`.  If you run `kitchen diagnose` you should see that the transport is defaulted to `winrm` without having to manually specify it.
