### ISSUE TITLE
How to copy files from box to host machine?

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#716]
Hi, I want to gather test results and merge them. First, I have configured Rspec to write result into local file below.

test/integration/helpers/serverspec/spec_helper.rb

```ruby
RSpec.configure do |c|
  c.add_formatter(:json, "/tmp/result.json")
end
```

Then I tried to copy the `/tmp/result.json` in box to host machine. But I have no idea to get the file via test-kitchen. I would appreciate if you tell me how to do that. Thanks.

**Comment by nogayama** [comment]
If the file is ASCII text, we can get it by `kitchen exec` command. For example, 
```
$ kitchen exec default -c "cat /tmp/resutl.json" > result.at_host.json
```

But if the file consists of only ASCII character without linebreak, this does not work. see this [issue](https://github.com/test-kitchen/test-kitchen/issues/717)

**Comment by sawanoboly** [comment]
Hi,

We can mount host directory from VM when using the Virtualbox to pass files each other.

For example,

```
driver:
  name: vagrant
  synced_folders:
    - ['.', '/home/vagrant/my-project']
    - ['./result', '/tmp/result']
```
