### ISSUE TITLE
Kitchen converge fails if symlink is pointing at a non-existent file.

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#723]
**Failing scenario:**
In a /cookbooks folder there is a symlink that points to a file that no longer exists.

**Note:**
Mounting a folder with 'broken' symlinks works fine in vanilla vagrant
As you can see the cookbook that's causing a failure is not actually consumed by chef client run. It's simply located in the /cookbooks folder.

**Expectation:**
Kitchen shouldn't care if there is a 'broken' symlink. If a cookbook was cloned from github user should not be expected to modify symlinks to make TK converge.

**Error:**

``` ruby
...
(Reading database ... 51095 files and directories currently installed.)
       Unpacking chef (from .../chef_12.3.0-1_amd64.deb) ...
       Setting up chef (12.3.0-1) ...
       Thank you for installing Chef!
       Transferring files to <workstation-hashicorp-precise64>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [No such file or directory @ rb_file_s_stat - 
/var/folders/9r/g1wlns1j29bg0c7b_6fr7b480000gp/T/workstation-hashicorp-precise64-sandbox-
20150522-65419-8nc34u/cookbooks/analytics-cookbooks/clusters.json]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Troubleshooting Details:**

```
/cookbooks/analytics-cookbooks(master)$ ls -la
...
clusters.json -> ../data_bags/analytics/clusters.json
cat ../data_bags/analytics/clusters.json
cat: clusters.json: No such file or directory
```

Kitchen.YML

``` yml
<%
USER = (ENV['USER'] || ENV['USERNAME']).downcase
>%
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
    natdnshostresolver1: 'on'
    natdnsproxy1: 'on'

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3.0

platforms:
  - name: hashicorp/precise64
    attributes:
      chef_workstation:
        user: vagrant
        group: vagrant
        chef_user: "#{USER}"
        berkshelf_client_key: "/chef-repo/.chef/#{USER}.pem"
        berkshelf_chef_user: "#{USER}"

suites:
  - name: workstation
    data_bags_path: ../../data_bags
    environments_path: ../../environments
    driver:
      synced_folders:
        - [ ".", "/chef-repo" ]
    run_list:
      - recipe[chef_workstation::default]
```
