### ISSUE TITLE
Can't set umask in client_rb

### ISSUE THREAD

**Issue by dpetzel** [test-kitchen/test-kitchen#761]
I've been through the docs and discovered the `client_rb` subkey in provisioner. It implies you can configure any client.rb, so I've added this:

```
provisioner:
  client_rb:
    umask: 0022
  solo_rb:
    umask: 0022
```

The problem is what gets written to the actual client.rb is `umask 18` which doesn't work properly. So I tried

```
provisioner:
  client_rb:
    umask: "0022"
  solo_rb:
    umask: "0022"
```

This writes out `umask "0022"` to the client.rb file. This doesn't work as chef-client is expecting it to not be a string.

It seem doesn't possible that you can get the client.rb written with the proper value of `umask 0022`

I'd also be interested if there is a way to set the umask outside the client.rb to have kitchen invoke chef with the proper umask (If you wondering our images have a custom one which is to strict in some cases).

**Comment by tonyhburns** [comment]
Here's the hack that I used for this:

```yaml
provisioner:
  client_rb:
    ;: :dummy; umask 0022
```
