### ISSUE TITLE
Can we copy .kitchen.yml into vagrant box?

### ISSUE THREAD

**Issue by nogayama** [test-kitchen/test-kitchen#763]
I want to verify whether or not the system has been converged to be following a given attributes in .kitchen.yml by parsing the yaml file in rspec/serverspec code. To do that we need to push .kitchen.yml into box. 

I first looked for .kitchen.yml in directory 'box:/tmp/kitchen/cookbooks/mycookbook'. But I could not find it. This is because .kitchen.yml is hidden file. I also tried `data_path` option. But it was not transferred into the box.

I think two ways to do this 
-  move and rename .kitchen.yml to kitchen.yml 
```yaml
driver:
  name: vagrant
  pre_create_command: cp .kitchen.yml test/kitchen.yml

provisioner:
  name: chef_solo
  data_path: "test"
```

- use sync folder like below
```yaml
driver:
  name: vagrant
  synced_folders:
    - ['.', '/tmp/mycookbook']
```

But both look like workarounds. Is this an official way to copy .kitchen.yml into box?
