### ISSUE TITLE
Trouble provisioning with chefdk

### ISSUE THREAD

**Issue by seth** [test-kitchen/test-kitchen#767]
I'd like to bring up test nodes with chefdk installed and use the chef-client included in chefdk for converging the node.

I've tried specifying the provisioner as follows:

```
provisioner:
  name: chef_zero
  require_chef_omnibus: 0.6.2
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk
```

When I converge the node, chefdk is indeed installed, however, things bomb out after that.
Here's an example (see log2) of the failure trace I see: https://gist.github.com/seth/54e2d2c90fca0b30383e#file-log2
