### ISSUE TITLE
attempting to copy file from /var/folders that does not exist

### ISSUE THREAD

**Issue by TemporarilyOffline** [test-kitchen/test-kitchen#774]
I'm not sure if this is a kitchen problem or even really where to start with this one.

Host OS: MacOSX Yosemite
GuestOS:  Either Windows 2008r2 Standard or Windows 2012r2 Standard built with Boxcutter
Cookbook: Empty
Error Message: 

```
Message: Failed to complete #converge action: [Invalid argument @ io_write - /var/folders/b5/6syhwtfs64j98cl92blfjm2m0000gn/T/tmpzip-20150710-434-192idjr.zip
```

That file does not exist to be copied, nor am I asking for it to be copied.

The problem comes and goes at random.  Removing the contents of /var/folders and rebooting does not help.

.kitchen.yml:
```
---
driver:
  name: vagrant
    
provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[wbe-test::default]
    attributes:
```

Troubleshooting steps:
remove /var/folders and reboot
R&R different versions of ChefDK, currently on 0.6.2.
Create New Box using boxcutter
Create Box of different version of guest OS using box cutter
R&R vagrant
Build recipe under Centos - Works fine

Any suggestions on how to proceed?
