### ISSUE TITLE
Merge platform and suite run_list between project_config and local_config

### ISSUE THREAD

**Issue by patcon** [test-kitchen/test-kitchen#778]
I keep a `.kitchen.digitalocean.yml` file that I copy to `.kitchen.local.yml` for doing travis tests. I keep all the digitalocean-specific things there, so I override the named platform versions with a new hash that has the `image` key:

``` yaml
# .kitchen.yml
driver: vagrant

platforms:
- name: centos-6
  driver_config:
    box: chef/centos-6.6
  run_list:
  - recipe[yum]
```

``` yaml
# .kitchen.digitalocean.yml
driver: digitalocean

platforms:
- name: centos-6
  driver_config:
    image: centos-6-5-x64
```

It seems that the run_list in the project_config is overridden by the empty run_list in local_config.

Before I dig in, is this expected behaviour? The merging seems to be pretty seamless and as-expected everywhere else :)

Thanks!

**Comment by cheeseplus** [comment]
This seems like a bug to me but I'll have to ask some folks who know the code better. Can this be repro'd still?

**Comment by ghostsquad** [comment]
Oh please... deep merge of all the things is so needed!
As an example:

`.kitchen.yml`

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.1
  always_update_cookbooks: true
  cookbooks_path:
    - ../../site-cookbooks
    - ../../librarian-cookbooks

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[foo::default]
    verifier:
      inspec_tests:
        - spec/integration/recipes/default_spec.rb
    attributes:
      hello: world
      username: bob
      password: <redacted>
```

I would very much like to be able to do this:
`.kitchen.local.yml`

```yaml
---
suites:
  - name: default
     attributes:
       password: mypassword
```
