### ISSUE TITLE
Converge fails on "Configuring netowrk adapters within the VM..."

### ISSUE THREAD

**Issue by aem** [test-kitchen/test-kitchen#789]
I've got an Atlas-hosted box (amarkon/windows-7-ult-n-x64) that has been converging fine the last few days. Today I modified my configuration and tried to re-converge, but each time I try it fails with the following error:
```
==> default: Setting hostname...
==> default: Configuring network adapters within the VM...
STDERR: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```
Just following instructions :)

My .kitchen.yml is as follows:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

transport:
  name: winrm
  username: vagrant
  password: vagrant

platforms:
  - name: amarkon/windows-7-ult-n-x64
    driver_config:
      box: amarkon/windows-7-ult-n-x64
      communicator: winrm

suites:
  - name: default
    run_list:
      - recipe[windows_default]
```
