### ISSUE TITLE
kitchen exec -c "ipconfig" fails on winrm (any other command too) with Winrm authorization error. 

### ISSUE THREAD

**Issue by puneetloya** [test-kitchen/test-kitchen#795]
_From @puneetloya on July 29, 2015 6:33_

Because it is using username "administrator" by default and password "nil" (empty). I have tried setting username and password combination (existing on the system) under transport in kitchen yml but it still uses administrator/nil combination.

Eg:
transport:
  name: winrm
  username: "xyz"
  password: "abc"

Have also tried the other way by putting the username and password in driver_config but to no avail.
But the kitchen instance successfully converges using the username/password in the driver_config.

_Copied from original issue: test-kitchen/winrm-transport#12_

**Comment by sawanoboly** [comment]
Hi, Could you put all of kitchen.yml or output of kitchen diagnose ?

**Comment by sawanoboly** [comment]
I've succeeded passing username and password from kitchen.yml with `Test Kitchen version 1.4.2.dev.0(current master) and winrm-transport (1.0.2).` 

```
# .kitchen.yml
---
driver:
  name: dummy

provisioner:
  name: dummy

platforms:
  - name: windows

transport:
  name: winrm
  username: foo
  password: var

suites:
  - name: default
    run_list:
    attributes:
```

Result:

```
$ kitchen exec -c 'ipconfig' -l debug
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.2 library loaded
-----> Execute command on default-windows.
D      [WinRM] plaintext::http://ec2-54-250-xx-xx.ap-northeast-1.compute.amazonaws.com:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"foo", :pass=>"var"}> (ipconfig)
D      [WinRM] opening remote shell on plaintext::http://ec2-54-250-xx-xx.ap-northeast-1.compute.amazonaws.com:5985/wsman<{:disable_sspi=>true, :basic_auth_only=>true, :user=>"foo", :pass=>"var"}>

...
```

Maybe, you set wrong syntax for yaml. Could you add indent ? @puneetloya 
Or, please check statefile which is placed at `.kitchen/*.yml`.  username and password will overwrite by it.
