### ISSUE TITLE
forward_agent kitchen.yml config not honored

### ISSUE THREAD

**Issue by kbruner** [test-kitchen/test-kitchen#807]
It looks like, even when I set this in the driver config section (next to ssh_key, which does get honored), this doesn't get used.

I think it's because the option is never passed to the transport object at instance creation time, so it's not written to the state file, and the state file becomes the source of truth for the ssh options on subsequent calls to kitchen login.  If I manually add it to the .kitchen/<instance>.yml file after creation, it shows up in the ssh command line.

Note that this is different from the ssh.forward_agent option, which does seem to work (it gets written in the Vagrantfile as `config.ssh.forward_agent: true`), but since kitchen constructs its own ssh command line rather than using `vagrant ssh`, that has no net effect.

**Comment by kbruner** [comment]
Ah, it does work if I explicitly create a `transport` config block.  This may just be a case of "needs better documentation," as the ssh_key option works fine in the `driver` block, and I've never actually seen a standalone transport block in a .kitchen.yml file.

**Comment by asimy** [comment]
As an example @kbruner's workaround, this is the `.kitchen.yml` that worked for me:
```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      ssh:
        forward_agent: true # did not work

suites:
  - name: default
    run_list:
      - recipe[blah::default]
    attributes:

transport:
  forward_agent: true #worked
```
