### ISSUE TITLE
Windows guests ignore chef_omnibus_url, require override of chef_metadata_url

### ISSUE THREAD

**Issue by gh2k** [test-kitchen/test-kitchen#820]
I'm trying to use a custom omnibus url on Windows, as I've needed to patch a file in chef in order for something to work.

Here's a sample kitchen.yml:

``` yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    transport:
      name: winrm
    provisioner:
      chef_omnibus_url: https://myhost/chef-client-12.4.1-1-patched.msi

suites:
  - name: default
    run_list:
      - recipe[symboliser::default]
```

Here's what `kitchen diagnose` has to say about that:

```

---
timestamp: 2015-08-21 14:12:01 UTC
kitchen_version: 1.4.2
instances:
  default-opentable-win-2012r2-standard-amd64-nocm:
    platform:
      os_type: windows
      shell_type: powershell
    state_file: {}
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      box_check_update: 
      box_url: 
      box_version: 
      customize:
        memory: 2048
        cpus: 4
      gui: 
      kitchen_root: "/home/simon/code/cookbooks/symboliser-cookbook"
      log_level: :info
      name: vagrant
      network: []
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: "/home/simon/code/cookbooks/symboliser-cookbook/test/integration"
      vagrantfile_erb: "/home/simon/.rvm/gems/ruby-2.2.1/gems/kitchen-vagrant-0.18.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: 
    provisioner:
      attributes: {}
      chef_metadata_url: https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest
      chef_omnibus_install_options: 
      chef_omnibus_root: "$env:systemdrive\\opscode\\chef"
      chef_omnibus_url: https://myhost/chef-client-12.4.1-1-patched.msi
      chef_solo_path: "$env:systemdrive\\opscode\\chef\\bin\\chef-solo.bat"
      clients_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/home/simon/code/cookbooks/symboliser-cookbook"
      log_file: 
      log_level: :info
      name: chef_solo
      nodes_path: 
      require_chef_omnibus: true
      roles_path: 
      root_path: "$env:TEMP\\kitchen"
      run_list:
      - recipe[symboliser::default]
      solo_rb: {}
      sudo: 
      sudo_command: 
      test_base_path: "/home/simon/code/cookbooks/symboliser-cookbook/test/integration"
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/home/simon/code/cookbooks/symboliser-cookbook"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: 
      port: 5985
      rdp_port: 3389
      test_base_path: "/home/simon/code/cookbooks/symboliser-cookbook/test/integration"
      username: administrator
    verifier:
      busser_bin: "$env:TEMP\\verifier\\bin\\busser.bat"
      http_proxy: 
      https_proxy: 
      kitchen_root: "/home/simon/code/cookbooks/symboliser-cookbook"
      log_level: :info
      name: busser
      root_path: "$env:TEMP\\verifier"
      ruby_bindir: "$env:systemdrive\\opscode\\chef\\embedded\\bin"
      sudo: 
      sudo_command: 
      suite_name: default
      test_base_path: "/home/simon/code/cookbooks/symboliser-cookbook/test/integration"
      version: busser
```

Here's what `kitchen test` does:

```
-> be kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-opentable-win-2012r2-standard-amd64-nocm>
-----> Destroying <default-opentable-win-2012r2-standard-amd64-nocm>...
       Finished destroying <default-opentable-win-2012r2-standard-amd64-nocm> (0m0.00s).
-----> Testing <default-opentable-win-2012r2-standard-amd64-nocm>
-----> Creating <default-opentable-win-2012r2-standard-amd64-nocm>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opentable/win-2012r2-standard-amd64-nocm'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'opentable/win-2012r2-standard-amd64-nocm' is up to date...
       ==> default: Setting the name of the VM: kitchen-symboliser-cookbook-default-opentable-win-2012r2-standard-amd64-nocm_default_1440166508782_409
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 5985 => 55985 (adapter 1)
           default: 22 => 2222 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       [WinRM] Established
       Vagrant instance <default-opentable-win-2012r2-standard-amd64-nocm> created.
       Finished creating <default-opentable-win-2012r2-standard-amd64-nocm> (1m54.62s).
-----> Converging <default-opentable-win-2012r2-standard-amd64-nocm>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.3.0...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.4.1-1.msi
```

If I create a file that says:

```
url https://myhost/chef-client-12.4.1-1-patched.msi
md5 5d186fb37cc254b7f0da345ef8fa5757
sha256  82961bc0374ac684f8b1d4a66a8c719182a06b6c70f3aa089bb51708310abc2d
```

and update my .kitchen.yml to say:

``` yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    os_type: windows
    shell_type: powershell
    transport:
      name: winrm
    provisioner:
      chef_metadata_url: https://myhost/chef-metadata.txt

suites:
  - name: default
    run_list:
      - recipe[symboliser::default]
```

then it installs the msi that I want.

This is not what it says in the documentation... I would expect that if chef_omnibus_url is provided then it skips the metadata request and downloads the specified msi instead.

**Comment by cheeseplus** [comment]
Not sure where the documentation says otherwise - currently it says that it points to an install.sh and we don't claim that that URL can be set to an arbitrary installer. Is there an issue still here that we can resolve?

**Comment by vinyar** [comment]
I am sure I read somewhere at some point in that that arbitrary URLs work. I got a bunch of kitchen files locally.

The trick, is that you specify the version, and location, but not the actual file name
chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh or in vargant: `config.omnibus.install_url = 'c:\\parent_binaries\\chef_client'`

**Comment by DavidMcGrathUnionStreet** [comment]
Hi Everyone. I am trying to stop test kitchen downloading chef-client from the internet when I converge a node. I am running chefdk on windows converging windows nodes. I am using the kitchen-hyperv driver. 

My initial idea was to host chef-client in IIS on the machine running chefdk.

I have tried the suggestions above relating to the undocumented feature but cannot get it to work as well as vinyar's suggestion above.

My .kitchen.yml is 


```
---
driver:
  name: hyperv
  parent_vhd_folder: C:\Hyper-V
  parent_vhd_name: WindowsServer2012R2_MutliDrive.vhdx
  vm_switch: InternalSwitch
  memory_startup_bytes: 1.5GB
  processor_count: 1

provisioner:
  name: chef_zero_scheduled_task
  require_chef_omnibus: 12.8.1
  chef_omnibus_url: http://1084-w10-lap/

verifier:
  name: inspec

transport:
  password: P@ssw0rd.1

platforms:
  - name: windows-2012r2

suites:
  - name: member
    run_list:
      - recipe[event_log::default]
    attributes:
        options:
```
`

and the output from test kitchen is 

```
PS C:\chef\chef-test\cookbooks\event_log> kitchen converge
-----> Starting Kitchen (v1.6.0)
-----> Converging <member-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.2.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.8.1)

       Downloading package from

       Skipping md5 verification

       Installing Chef Omnibus package C:\Users\ADMINI~1\AppData\Local\Temp\chef-12.8.1.msi

       Creating the scheduled task.
       SUCCESS: The scheduled task "chef-tk" has successfully been created.
       Transferring files to <member-windows-2012r2>
       SUCCESS: Attempted to run the scheduled task "chef-tk".
       Connected to the scheduled task.

       Finished converging <member-windows-2012r2> (0m12.28s).

```

Thanks in Advance

David
