### ISSUE TITLE
http proxy for "Installing Chef Omnibus" part?

### ISSUE THREAD

**Issue by jblaine** [test-kitchen/test-kitchen#867]
What am I missing here? How do I specify the proxy to use for what's failing below?

Test Kitchen version 1.4.2 (ChefDK 0.9.0)

```
---
driver:
  name: vagrant
  driver_config:
    http_proxy: http://gate.our.org:80
    https_proxy: https://gate.our.org:80
  network:
    - ["private_network", {ip: "192.168.1.2"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
```

```
       [SSH] Established
       Vagrant instance <default-centos-67> created.
       Finished creating <default-centos-67> (4m16.19s).
-----> Converging <default-centos-67>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Trying curl...
       grep: /tmp/stderr: No such file or directory
       Trying python...
       Unable to download https://www.chef.io/chef/install.sh to /tmp/install.sh, aborting
       \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2015-10-27 18:44:30--  https://www.chef.io/chef/install.sh
       Resolving www.chef.io... 23.235.46.65
       Connecting to www.chef.io|23.235.46.65|:443... failed: Connection refused.\n\nSTDERR from python:\n\nTraceback (most recent call last):
```
