### ISSUE TITLE
Berkshelf not managing dependencies

### ISSUE THREAD

**Issue by trekr5** [test-kitchen/test-kitchen#869]
Hello,

Hoping someone can help.

I've installed test-kitchen on Ubuntu-14.04 and as long as my cookbook doesn't require dependcies, test-kitchen runs fine.

When I do a kitchen converge, I receive the following

#metadata.rb

    name            'my-cookbook'
    maintainer      'mycompany.com'
    version         '0.0.1'

       depends 'java'
       depends 'partial_search'
       depends 'chef_handler'
       depends 'chef_client'

#Berksfile 

    source "https://supermarket.chef.io"

    metadata

    cookbook 'partial_search'
    cookbook 'java'
    cookbook 'chef_handler'
    cookbook 'chef_client'

   Error message
   ===========

     Starting Kitchen (v1.4.2)
     Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
      -----Exception-------
      Class: Kitchen::ActionFailed
      Message: Failed to complete #converge action: [Required artifacts do not exist at the desired      version
      Missing artifacts: chef_client
     Unable to find a solution for demands: chef_client (>= 0.0.0), chef_handler (>= 0.0.0), gg-fri (0.0.1),     java (>= 0.0.0), partial_search (>= 0.0.0)]
    Please see .kitchen/logs/kitchen.log for more details
    Also try running `kitchen diagnose --all` for configuration

Can you please tell me what I need to do to get my recipe to converge? I've installed the berksfile gem.

**Comment by xmik** [comment]
I don't know about `chef_client` cookbook, but `chef-client` definitely exists. Also, you don't have to list cookbooks in Berksfile.

**Comment by gauravdott** [comment]
Same problem

Berksfile
```
source "https://api.berkshelf.com"


metadata
```

#metadata.rb

```
name 'django'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures django'
long_description 'Installs/Configures django'
version '0.1.0'

depends 'application_python', '~> 4.0.0'
depends 'ssh'

```

Error
```
       [2015-11-13T13:53:21+00:00] ERROR: Cookbook application_python not found. If you're loading application_python from another cookbook, make sure you configure the dependency in your metadata
       [2015-11-13T13:53:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Also berksfile location is default and all dependencies are resolved on

```
berks install
```

Any suggestions ?

**Comment by mwrock** [comment]
You might try running kitchen with debug logging. Also, on modern versions of berkshelf, kitchen will perform a berks `vendor` and not an `install` so you might try running `berks vendor <some temp path>` from the root of your cookbook and see if that meets with a similar failure.

**Comment by cheeseplus** [comment]
@trekr5 your issue is the cookbook name chef_client -> chef-client

@gauravdott at this juncture everyone should be using source "https://supermarket.chef.io" - that example works fine for me now.

Closing this as the issues were unrelated and I am unable to verify the behaviour.

**Comment by timurb** [comment]
I see the same issue:
* I have a Berksfile with a line like following and a recipe using that cookbook.
```
cookbook 'mycheflib', path: '../chef-mycheflib'
```
* Berkshelf is run (it crashes if the above line is incorrect) but the cookbooks are not uploaded to test kitchen VM and hence chef-client can't find the required recipe.

Most likely it is the issue with `.kitchen.yml`, here it is:
```
---
driver:
  name: docker
  use_sudo: false
  use_cache: true
  disable_upstart: false
  run_command: /sbin/init

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04-11
    driver:
      image: ubuntu-upstart:12.04   # upstart doesn't work in stock ubuntu image
    provisioner:
      require_chef_omnibus: 11.18.6

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```
