### ISSUE TITLE
(Win2012r2) Chef-client version to install seems to be ignored

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#882]
__Bug:__
It doesn't seem to matter what version is specified in the .kitchen.yml file. That version is reported as having been detected.

__Example:__
.kitchen.yml
```yml
---
driver:
  name: vagrant
provisioner:
  require_chef_omnibus: 57.24.0
platforms:
  - name: win2012_chef11_14_2
suites:
  - name: default
    run_list:
      - recipe[ces_chefworkstation::default]
    attributes:
```
output:
```ruby
-----> Converging <default-win2012-chef11-14-2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Chef Omnibus installation detected (57.24.0)
       Transferring files to <default-win2012-chef11-14-2>
....
       * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
       Starting Chef Client, version 11.14.2
       Compiling Cookbooks...
```

__Dev env info:__
$ chef -v
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
$ vagrant plugin list
kitchen-nodes (0.5.0)
vagrant-azure (1.3.0)
vagrant-berkshelf (4.1.0)
vagrant-cachier (1.2.1)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.4, system)
vagrant-winrm (0.7.0)

Notes:
*  :latest resolves to correct latest version available on chef.io, however the error remains the same.
*  I poked around the code, and didnt see anything obvious. chef-solo -v returns correct version presently on the box `11.14.2` (https://github.com/chef/vagrant-omnibus/blob/00c19b5ba0c76c2a1684580d4c0c9db4703f0fd7/lib/vagrant-omnibus/action/install_chef.rb#L139)
* complete guess, but perhaps the error is in this variable: https://github.com/chef/vagrant-omnibus/blob/00c19b5ba0c76c2a1684580d4c0c9db4703f0fd7/lib/vagrant-omnibus/action/install_chef.rb#L45

reference: https://github.com/chef/vagrant-omnibus/issues/125
