### ISSUE TITLE
Windows tests broken - mkdir -p

### ISSUE THREAD

**Issue by manuelmazzuola** [test-kitchen/test-kitchen#886]
Something goes wrong when I try to execute kitchen on windows.
It tries to do `mkdir -p` (on Windows ?)
Any ideas ?

Here the .kitchen.yml
```
---                                                                                                                             
driver:                                                                                                                         
  name: vagrant                                                                                                                 
                                                                                                                                
platforms:                                                                                                                      
  - name: windows-2012r2                                                                                                        
    driver:                                                                                                                     
      gui: false                                                                                                                
      communicator: winrm                                                                                                       
      network:                                                                                                                  
        - ["forwarded_port", {guest: 5985, host: 5985}]                                                                         
      username: vagrant                                                                                                         
      password: vagrant                                                                                                         
      driver_config:                                                                                                            
        winrm_username: vagrant                                                                                                 
        winrm_password: vagrant                                                                                                 
        username: vagrant                                                                                                       
        password: vagrant                                                                                                       
      customize:                                                                                                                
        memory: 2048
```

and the log
```
-----> Cleaning up any prior instances of <cd-aspnet-windows-2012r2>                                                    [24/130]
-----> Destroying <cd-aspnet-windows-2012r2>...
       Finished destroying <cd-aspnet-windows-2012r2> (0m0.00s).
-----> Testing <cd-aspnet-windows-2012r2>
-----> Creating <cd-aspnet-windows-2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'windows-2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-cd-aspnet-cd-aspnet-windows-2012r2_default_1449141053842_71814
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 5985 => 5985 (adapter 1)
           default: 5985 => 55985 (adapter 1)
           default: 5986 => 55986 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: WinRM address: 127.0.0.1:5985
           default: WinRM username: vagrant
           default: WinRM transport: plaintext
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [WinRM] Established
       Vagrant instance <cd-aspnet-windows-2012r2> created.
       Finished creating <cd-aspnet-windows-2012r2> (4m45.33s).
-----> Converging <cd-aspnet-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/i386/chef-client-12.5.1-1-x86.m
si
       Download complete.
       Successfully verified C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
       
       Installing Chef Omnibus package C:\Users\vagrant\AppData\Local\Temp\chef-true.msi
       Installation complete
$$$$$$ mkdir : Parameter cannot be processed because the parameter name 'p' is
$$$$$$ ambiguous. Possible matches include: -Path -PipelineVariable.
$$$$$$ At line:1 char:7
$$$$$$ + mkdir -p $env:TEMP\kitchen
$$$$$$ +       ~~
$$$$$$     + CategoryInfo          : InvalidArgument: (:) [mkdir], ParameterBindingEx
$$$$$$    ception
$$$$$$     + FullyQualifiedErrorId : AmbiguousParameter,mkdir
>>>>>> Converge failed on instance <cd-aspnet-windows-2012r2>.
>>>>>> Please see .kitchen/logs/cd-aspnet-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [mkdir -p $env:TEMP\kitchen]
>>>>>> ----------------------
```

Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
Test Kitchen version 1.4.2
