### ISSUE TITLE
"kitchen list" breaks if suits: & - name: fields are missing

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#893]
Example:
`kitchen list`

Error:

```
>>>>>>
No instances for regex `', try running `kitchen list'
```

.kitchen.yml:

```

---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: win2012_chef11_14_2
# suites:
#   - name: default
```
