### ISSUE TITLE
ability to pass arguments to shell provisioner

### ISSUE THREAD

**Issue by mmckinst** [test-kitchen/test-kitchen#917]
It would be great if you could specify a list of arguments for the shell provisioner to pass to the script. Something like this config would run the script below:

``` yaml
provisioner:
  name: shell
  arguments:
    - -t foobar
    - -n 6
    - --assume-yes
    - build
```

``` shell
bootstrap.sh -t foobar -n 6 --assume-yes build
```

**Comment by cheeseplus** [comment]
If you'd like to make a PR we're happy to review.

**Comment by mmckinst** [comment]
I ended up doing it so its just a key:value instead of an array, so it looks more like this and will result in the below script

```yaml
provisioner:
  name: shell
  arguments: '--php 70 --mysql 57'
```

```bootstrap.sh --php 70 --mysql 57```

I don't know if this works with Powershell or not, nor do I have a way of testing.

Let me know if it looks good and I can document it too if you want.

**Comment by mmckinst** [comment]
regarding the failing tests, it appears all the pull requests are failing for that tests.

**Comment by mmckinst** [comment]
Also, here's a better example of how this might be used IRL if you have a script to install a certain version of PHP on a bunch of different platforms.

I don't think the fact you get set attributes for the provisioner inside the suite is well documented, but its a great feature.

```yaml
provisioner:
  name: shell
  script: install.sh

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-14.04
  - name: debian-7
  - name: debian-8

suites:
  - name: php56
    provisioner:
      arguments: '--php 56'  
  - name: php70
    provisioner:
      arguments: '--php 70'
```
