### ISSUE TITLE
Custom Config for Busser Plugins 

### ISSUE THREAD

**Issue by neillturner** [test-kitchen/test-kitchen#945]
I'd like to be able to pass custom config to busser plugins. 
something like a custom_config when any yaml could be specified:  

```
suites:
  - name: mytest
    custom_config:
       extra_vars:
          ROLE: a_role
```

then busser would take the custom_config 
and put in a file say config.yml 
say something like: 

```
---
- extra_vars:
     ROLE: a_role
```
and store it in /tmp/verifier directory so that the a busser plugin could read it. 

I'll have a go at a custom busser for this and a  pull request for this when i get time. 

Ofcourse i'm open to anyway to pass custom config to a busser_plugin -)
