### ISSUE TITLE
Instance not treated as Windows unless Vagrant box starts with 'win'

### ISSUE THREAD

**Issue by crerwin** [test-kitchen/test-kitchen#949]
This is despite the settings in kitchen.yml.  I assume this isn't expected behavior, but I could be wrong.  Here's my kitchen.yml as it is now, after trying variations of putting winrm under driver: driver_config: and transport:.  Converging works with this kitchen.yml when the Vagrant box is named windows2012R2-tfs.
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows2012R2-tfs
    driver:
      guest: windows
      communicator: winrm
    driver_config:
      guest: windows
      communicator: winrm
      vm_hostname: false
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[nsclient::default]
    attributes:
```

Converging does not work when the Vagrant box is named tfs-windows2012R2, with the same kitchen.yml (except of course -name: tfs-windows2012R2).  Here's a snip of default-tfs-windows2012R2.log with that box name.  Looks like it's trying to use sh and put files in /opt/chef.
[default-tfs-windows2012R2.log.txt](https://github.com/test-kitchen/test-kitchen/files/145402/default-tfs-windows2012R2.log.txt)

```

I, [2016-02-24T15:46:44.353932 #11088]  INFO -- default-tfs-windows2012R2: Resolving cookbook dependencies with Berkshelf 4.0.1...
I, [2016-02-24T15:46:44.786051 #11088]  INFO -- default-tfs-windows2012R2: Removing non-cookbook files before transfer
I, [2016-02-24T15:46:44.817333 #11088]  INFO -- default-tfs-windows2012R2: Preparing validation.pem
I, [2016-02-24T15:46:44.819307 #11088]  INFO -- default-tfs-windows2012R2: Preparing client.rb
W, [2016-02-24T15:46:45.099326 #11088]  WARN -- default-tfs-windows2012R2: The command line is too long.
E, [2016-02-24T15:46:45.141348 #11088] ERROR -- default-tfs-windows2012R2: Converge failed on instance <default-tfs-windows2012R2>.
E, [2016-02-24T15:46:45.141348 #11088] ERROR -- default-tfs-windows2012R2: ------Exception-------
E, [2016-02-24T15:46:45.141348 #11088] ERROR -- default-tfs-windows2012R2: Class: Kitchen::ActionFailed
E, [2016-02-24T15:46:45.141348 #11088] ERROR -- default-tfs-windows2012R2: Message: WinRM exited (1) for command: [sh -c '

chef_omnibus_root="/opt/chef"
chef_omnibus_url="https://www.chef.io/chef/install.sh"
install_flags=""
pretty_version="install only if missing"
sudo_sh="sudo -E sh"
version="true"

tmp_stderr="/tmp/stderr";

# capture_tmp_stderr SOURCE
capture_tmp_stderr() {
  # spool up $tmp_stderr from all the commands we called
  if test -f "$tmp_stderr"; then
    output="`cat $tmp_stderr`";
    stderr_results="${stderr_results}\nSTDERR from $1:\n\n${output}\n";
    rm $tmp_stderr;
  fi
}
```
I can reproduce the error and successfully converge consistently by changing the Vagrant box name back and forth (by simply changing the box directory name).  The last comment in [this issue](https://github.com/test-kitchen/test-kitchen/issues/638) led me to try starting the box name with 'win' after fighting with the issue.

Test Kitchen version 1.4.2, Vagrant version 1.8.1.
