### ISSUE TITLE
Using the kitchen-ec2 driver and shell provisioner yields missing credentials

### ISSUE THREAD

**Issue by lfjewett** [test-kitchen/test-kitchen#951]
I'm trying to setup our testing framework to take advantage of the new features in the latest kitchen release for shell provisioners.  I'm following along almost exactly with the cookbook example found in the merged change @ https://github.com/cl-lab-k/apache2-take.   However we are using the ec2 driver for test kitchen, not vagrant.  The KITCHEN_USERNAME and KITCHEN_SSH_KEY variables are not getting set, and thus can't be passed to rspec.

Adding "username:" and "ssh_key:" to the ./kitchen/name.yml file after a node is converged does in fact create the correct ENV variables on the NEXT kitchen verify run.  Also pre-setting the above 2 variables in your shell also works fine.   Unless I'm missing something in my kitchen.yml config, which works fine otherwise, nothing is populating these two keys automatically for us.

Is this a bug or working as intended?

**Comment by cheeseplus** [comment]
This is likely because those env variables are only keyed by the shell _verifier_ and nowhere else that I can find:

https://github.com/test-kitchen/test-kitchen/blob/0ba6f2116d8dd2b65396b4e352236106b922b918/lib/kitchen/verifier/shell.rb#L95

In that sense it is working as intended.

**Comment by xsmaster** [comment]
@lfjewett I think i have a fix for you. I'm using the a simular setup you are. Test Kitchen with EC2.

here is my kitchen.yml file
```
driver_plugin: ec2
driver_config:
  aws_ssh_key_id: PEM_FILE
  security_group_ids: ["sg-xxxxxxxx"] # Security group
  region: us-east-1
  availability_zone: a
  require_chef_omnibus: true
  subnet_id: subnet-xxxxxxxx
  instance_type: t2.medium
  http_proxy:  # <-- Proxy for busser. kitchen verify command.
  https_proxy: # <-- Proxy for busser

provisioner:
  name: chef_solo
  http_proxy:  # <-- Proxy for getting chef client upon boot.
  https_proxy: # <-- Proxy for getting chef client upon boot.

platforms:
  - name: RHEL # Name used by Test Kitchen
    driver:
      image_id: ami-XXXXXXXX # AMI ID. You can also provide search terms.
      tags: # Put as many tags as you like.
        Name: test-kitchen-rhel67
        TEAM: BT
      block_device_mappings: # EBS Volume information
      # more junk...

transport: # What SSH user do you want to use.
  username: ec2-user
  ssh_key: ~/ssh_keys/PEM_FILE.pem # Location of where the pem is stored.
```

So I will be posting blog post on what I have learned soon. I hope this helps you and others out.

James
