### ISSUE TITLE
Advanced support for chef_metadata_url to override chef omnibus installation

### ISSUE THREAD

**Issue by edehde** [test-kitchen/test-kitchen#965]
## Description

Would be helpful to be able to use ``chef_metadata_url`` (and complete [omnitruck api](https://docs.chef.io/api_omnitruck.html)) to override chef omnibus installation, e.g. to reuse (cached) chefdk "el6" rpm for both centos 6.x and 7.x.:

```yaml
provisioner:
  name: chef_solo
  chef_metadata_url: https://www.chef.io/chef/metadata-chefdk?p=el&pv=6&m=x86_64&v=latest&prerelease=false
  chef_omnibus_root: /opt/chefdk
```

Seems to be an [undocumented feature](https://docs.chef.io/config_yml_kitchen.html) only used in omnibus chef windows setups:

https://github.com/test-kitchen/test-kitchen/blob/v1.6.0/support/chef_base_install_command.ps1#L77

See also https://github.com/test-kitchen/test-kitchen/issues/820 (and https://github.com/test-kitchen/test-kitchen/issues/809)

## Kitchen Version

Currently using e.g.

```yaml
- name: blablupp
  provisioner:
    name: chef_solo
    require_chef_omnibus: 0.11.2
    chef_omnibus_root: /opt/chefdk
    chef_omnibus_install_options: -P chefdk -d /tmp/vagrant-cache/chef-omnibus
  run_list:
    - recipe[coremedia-ci::blablupp]
  includes:
    - centos6-vagrant
    - centos7-vagrant
    - amzn-linux
```

```bash
$ /opt/chefdk/embedded/bin/kitchen -v
Test Kitchen version 1.6.0
```

```bash
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```

**Comment by hanselmahlaola** [comment]
I have the same issue and it make testing to take too long

**Comment by mwrock** [comment]
This comes with https://github.com/test-kitchen/test-kitchen/pull/976

Then you can do:
```
provisioner:
  name: chef_zero
  product_name: chefdk
  product_version: latest
  platform: mac_os_x
  platform_version: 10.9
  channel: stable
```
