### ISSUE TITLE
chef_metadata_url is ignored

### ISSUE THREAD

**Issue by alexmanly** [test-kitchen/test-kitchen#985]
## Description

I want to use a local copy of the chef-client.msi file to install the chef client rather than download from the internet to save time.

However the **chef_metadata_url** is ignored in the .kitchen.yml file and the chef-client package is always downloaded from https://packages.chef.io/stable/windows/2012r2/chef-client-12.8.1-1-x86.msi

If I log into the vagrant box and modify the script: C:\Users\vagrant\AppData\Local\Temp\kitchen\default-win-long_script.ps1 at line 4 from:

$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v="

to 

$chef_metadata_url = "file:///c:/share/chef/windows/windows_v12.8.1.1.txt"

Then run that script, the chef-client gets downloaded from the local filesystem and installed, which is the correct result.

here is the full **.kitchen.yml** file:

```
---
driver:
  forward_agent: yes
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_metadata_url: 'file:///c:/share/chef/windows/windows_v12.8.1.1.txt'
  roles_path: '../../roles'
  data_bags_path: '../../data_bags'
  environments_path: '../../environments'

transport:
  name: winrm

platforms:
  - name: win
    transport: 
      name: winrm 
      max_threads: 1 
    driver:
      box: windows-2012r2
      username: Administrator 
      password: Admin123 
      vm_hostname:
      # Mount local ~/chef-kits folder as c:\share on the VM  
      synced_folders:
      - ['~/chef-kits', 'c:/share', 'disabled: false']
      customize:
        cpus: 2
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[wsus_client::default]
    includes: windows-2012r2
```

This is the contents of the **windows_v12.8.1.1.txt** file:
```
sha1=90262264e2f63b4c38cfca2bc5623d78cc014d0d
sha256=8206e7027c15465131721ccc4cec2a0a8a0c5163b35c859dd362b196c07040fa
url=file:///C:/share/chef/windows/2012r2/chef-client-12.8.1-1-x86.msi
version=12.8.1
```

## Kitchen Version

chef --version
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
